/* Comparison pages.
 *
 * Rule for this file: never misrepresent a competitor, always name
 * the cases where they are the better choice, and only cite prices
 * actually verified (Instantly / Smartlead / lemlist, July 2026).
 * A comparison that reads as a hit piece converts worse than an
 * honest one and is far easier to discredit. */

const PRICE_NOTE = { note: 'Prices are the vendors\' published rates as at July 2026 and change frequently — check their own pricing page before deciding. Where we have not verified a figure, we say so rather than guessing.' };

export default [

{
  slug: 'instantly-alternative',
  title: 'An Instantly Alternative You Buy Once — Honest Comparison',
  description: 'How the Cold Outreach Machine compares to Instantly: subscription versus one-time purchase, where Instantly is genuinely the better tool, and who each one actually suits.',
  keywords: 'Instantly alternative, Instantly.ai alternative, cold email tool alternative, Instantly vs',
  eyebrow: 'Comparison',
  short: 'Instantly alternative',
  h1: 'Looking for an Instantly alternative? <span style="color:var(--grey-4);font-weight:300;">Here is the honest comparison.</span>',
  cta: 'product',
  body: [
    { lead: 'Instantly is a capable platform, and for a lot of outbound teams it is the right choice. This page exists for the specific case where it is not: when you would rather buy a system once than rent one indefinitely, and when the work you need done is finding and writing rather than sending.' },
    { h: 'The core difference' },
    { table: {
      minWidth: 620,
      head: ['', 'Instantly', 'Cold Outreach Machine'],
      rows: [
        ['Pricing model', 'Subscription, from about $37/month', 'US$499, paid once'],
        ['If you stop paying', 'Access ends', 'It keeps running — the code is yours'],
        ['Where it runs', 'Their platform', 'Your machine or your server'],
        ['Your prospect data', 'Stored on their servers', 'Stays with you'],
        ['Finds companies for you', 'Lead database available on higher tiers', 'Yes, from a profile you describe'],
        ['Writes each email', 'AI assistance for copy', 'Yes — individually, per company'],
        ['Inbox warm-up', 'Managed, across many mailboxes', 'Manual, documented process'],
        ['Support', 'Support team', 'Direct email, 30 days, from the person who wrote it'],
      ],
    }},
    PRICE_NOTE,
    { h: 'Where Instantly is the better choice' },
    'This is not a formality — there are real cases where you should pick them:',
    { list: [
      '**You run many mailboxes.** Managed warm-up across dozens of inboxes is genuinely hard to replicate by hand, and it is one of the things a subscription buys you properly.',
      '**You have a team.** Shared dashboards, permissions, reporting and handoffs are built in. Rebuilding that yourself is not worth it.',
      '**You want support within minutes.** A support desk is a real product feature, and a one-person business cannot match its response time.',
      '**You need very high volume.** At thousands of sends a day, platform infrastructure earns its subscription.',
    ]},
    { h: 'Where buying once makes more sense' },
    { list: [
      '**You are one person, or a handful.** The team features you are paying for go unused.',
      '**Outbound is permanent for you.** If you will still be prospecting in two years, a repeating fee against a one-time cost stops being close.',
      '**Your prospect list is a commercial asset.** Recruiters, consultants and agencies often have real reasons not to store it on someone else\'s platform.',
      '**The bottleneck is research and writing, not sending.** This is the common case, and it is the one most tools do not address — a sending platform does not give back the eight to twelve minutes per company that research takes.',
    ]},
    { h: 'The break-even, plainly' },
    'Against Instantly\'s entry tier at about $37 a month, a $499 purchase pays for itself in roughly eight months. Against the higher tier near $97, in about three. After that the licence line is zero — though infrastructure costs (domain, sending, AI writing) continue in both models, so the saving is on the fee rather than the total. [Full cost breakdown here.](/blog/cold-email-subscription-vs-one-time-cost/)',
    { note: 'If you are currently testing whether outbound works for your business at all, rent for a quarter. Buying makes sense once you know the channel is worth keeping — that is a genuinely better sequence than committing up front.' },
  ],
  faq: [
    { q: 'Is the Cold Outreach Machine a direct replacement for Instantly?', a: 'For a solo operator or small business doing moderate-volume outbound, largely yes — with the difference that it also finds companies and writes each message, which is work Instantly leaves to you or to its higher tiers. For a team running many mailboxes with managed warm-up and shared reporting, no; that is what a platform subscription is for and you would be downgrading.' },
    { q: 'Can I migrate my existing campaigns?', a: 'Your prospect lists export as CSV from any platform and import cleanly. Campaign sequences do not transfer as such, because the machine generates messages per company rather than running fixed sequence templates — you describe your ideal customer and it writes from that instead.' },
    { q: 'What about inbox warm-up?', a: 'This is the genuine gap. Instantly bundles automated warm-up across mailboxes; the Cold Outreach Machine documents a manual warm-up process instead. At one or two mailboxes, manual warm-up is a few minutes a day for a few weeks and works fine. At twenty mailboxes it does not scale, and a platform is the better tool.' },
    { q: 'Do I need technical skills?', a: 'No coding, but you will run a command in a terminal and paste DNS records into your domain. A guided installer asks for what it needs and tests each connection, and a live setup call is included — most buyers finish that call with the machine already running.' },
  ],
  related: [
    ['/smartlead-alternative/', 'Smartlead alternative'],
    ['/lemlist-alternative/', 'lemlist alternative'],
    ['/best-cold-email-software/', 'How to choose cold email software'],
    ['/cold-email-software-one-time-payment/', 'Buy once vs subscribe'],
  ],
},

{
  slug: 'smartlead-alternative',
  title: 'A Smartlead Alternative Without the Monthly Fee — Honest Comparison',
  description: 'Smartlead compared with a one-time-purchase alternative: where Smartlead\'s scale and rotation genuinely win, where owning the system wins, and the real break-even.',
  keywords: 'Smartlead alternative, Smartlead vs, cold email software alternative, one time payment cold email',
  eyebrow: 'Comparison',
  short: 'Smartlead alternative',
  h1: 'A Smartlead alternative <span style="color:var(--grey-4);font-weight:300;">without the monthly fee.</span>',
  cta: 'product',
  body: [
    { lead: 'Smartlead is built for scale — unlimited mailbox rotation, high volume, agencies running campaigns for many clients. If that is your situation, this page will probably talk you out of switching, and it should. If you are one person who wants outbound running quietly in the background, keep reading.' },
    { h: 'The comparison' },
    { table: {
      minWidth: 620,
      head: ['', 'Smartlead', 'Cold Outreach Machine'],
      rows: [
        ['Pricing model', 'Subscription, from about $39/month', 'US$499, paid once'],
        ['Built for', 'Scale, agencies, many clients', 'One business, steady volume'],
        ['Mailbox rotation', 'Core strength', 'Single mailbox by design'],
        ['Warm-up', 'Automated across mailboxes', 'Manual, documented'],
        ['Finding companies', 'You supply the list', 'It builds the list from your profile'],
        ['Writing each email', 'Sequence templates with variables', 'Individual message per company'],
        ['Data location', 'Their platform', 'Your machine'],
        ['Ends when you stop paying', 'Yes', 'No'],
      ],
    }},
    PRICE_NOTE,
    { h: 'Where Smartlead genuinely wins' },
    { list: [
      '**Agencies with multiple clients.** Separate workspaces, client reporting, and campaign isolation are things you would otherwise build badly yourself.',
      '**High-volume sending.** Rotating across many mailboxes to distribute load is exactly what it is designed for, and it does it well.',
      '**Automated warm-up at scale.** Warming twenty mailboxes by hand is not realistic.',
      '**A team that needs shared visibility.** Multiple people working the same pipeline need shared state.',
    ]},
    { h: 'Where a one-time purchase wins' },
    { list: [
      '**Solo operators and small businesses.** You are not using rotation across twenty inboxes, so you are paying for capability you do not touch.',
      '**Long time horizons.** A repeating fee against a fixed cost stops being a close call after the first year.',
      '**Data sensitivity.** The list stays on your hardware, and the AI writing can run locally so prospect details never reach any third party — see [self-hosted cold email](/self-hosted-cold-email/).',
      '**When the bottleneck is upstream.** Smartlead sends what you give it. If your constraint is finding companies and writing to them individually — which for most small businesses it is — sending was never the expensive part.',
    ]},
    { h: 'The honest summary' },
    'Smartlead is a scale tool. The Cold Outreach Machine is a one-business tool. They are not really competing for the same buyer, and if you are running an agency sending on behalf of eight clients, buying this would be a mistake — say so to yourself before switching on price alone.',
    { note: 'Break-even against Smartlead\'s entry tier is roughly eight months; against its Pro tier near $94, roughly three. [The full cost picture](/blog/cold-email-subscription-vs-one-time-cost/) includes the infrastructure both models require.' },
  ],
  faq: [
    { q: 'Does the Cold Outreach Machine rotate mailboxes?', a: 'No — it is built around a single sending mailbox at deliberately moderate volume. That is a real limitation if you need scale. The design assumption is that most small businesses are better served by twenty well-researched emails a day from one credible address than by hundreds rotated across many.' },
    { q: 'Can I use it for multiple clients as an agency?', a: 'The licence does not permit operating it as a service for third parties — it grants use inside one legal entity. If you are an agency running outbound on behalf of clients, a platform subscription is both the appropriate tool and the appropriate licence.' },
    { q: 'What if I outgrow it?', a: 'Then you have a good problem and a platform subscription is the right next step. Buying once at $499 and later moving to a subscription because volume demands it is a reasonable path — you will have learned what your market responds to, which is the expensive knowledge.' },
    { q: 'How does the AI writing compare to sequence templates?', a: 'Different approach entirely. Templates with variables produce recognisable structure across recipients; the machine writes each message from what that specific company publishes, and checks the batch for repeated phrasing before sending. The trade-off is that it needs a good description of who you are targeting to write well.' },
  ],
  related: [
    ['/instantly-alternative/', 'Instantly alternative'],
    ['/best-cold-email-software/', 'How to choose cold email software'],
    ['/self-hosted-cold-email/', 'Self-hosted cold email'],
  ],
},

{
  slug: 'lemlist-alternative',
  title: 'A lemlist Alternative for Solo Operators — Honest Comparison',
  description: 'lemlist compared with a one-time-purchase alternative: how per-seat pricing changes the maths, where lemlist\'s multichannel sequences win, and who each tool actually fits.',
  keywords: 'lemlist alternative, lemlist vs, cold email tool per seat, lemlist pricing alternative',
  eyebrow: 'Comparison',
  short: 'lemlist alternative',
  h1: 'A lemlist alternative <span style="color:var(--grey-4);font-weight:300;">for people who work alone.</span>',
  cta: 'product',
  body: [
    { lead: 'lemlist is strong on multichannel sequences and personalisation features, and its per-seat pricing model is the thing that most often sends people looking for alternatives. If you are one person, the maths is simpler than it looks.' },
    { h: 'The comparison' },
    { table: {
      minWidth: 620,
      head: ['', 'lemlist', 'Cold Outreach Machine'],
      rows: [
        ['Pricing model', 'Subscription, from about $39/month; multichannel tiers priced per user', 'US$499, paid once, one business'],
        ['Cost as the team grows', 'Rises per seat', 'Unchanged'],
        ['Channels', 'Email plus LinkedIn and calls in higher tiers', 'Email only'],
        ['Personalisation', 'Custom images, variables, dynamic content', 'Whole message written per company'],
        ['Finding companies', 'Lead database in higher tiers', 'Builds the list from your profile'],
        ['Where it runs', 'Their platform', 'Your machine or server'],
        ['If you stop paying', 'Access ends', 'It keeps running'],
      ],
    }},
    PRICE_NOTE,
    { h: 'Where lemlist genuinely wins' },
    { list: [
      '**Multichannel sequences.** If your process genuinely combines email, LinkedIn touches and calls in one orchestrated flow, lemlist does that natively and this does not.',
      '**Teams.** Shared templates, reporting and collaboration are built for groups working the same pipeline.',
      '**Visual personalisation.** Custom images and dynamic content are effective in some markets, and there is no equivalent here.',
      '**A polished interface.** It is a well-designed product used by people who spend all day in it. A command-line tool is not that.',
    ]},
    { h: 'Where buying once wins' },
    { list: [
      '**You are one person.** Per-seat pricing is designed for teams; as a solo operator you are on the least efficient point of that curve.',
      '**Email is your channel.** If your buyers are tradespeople, marine businesses, hospitality or local services, multichannel is a feature you will not use — those markets are not on the platforms.',
      '**Research is your bottleneck.** lemlist personalises within a message you write. The machine writes the message from what the company publishes, which is the more expensive part of the job.',
      '**You want the data local.** Prospect list on your hardware, with the option of running the AI writing locally too.',
    ]},
    { note: 'A fair way to decide: if you would use the LinkedIn and calling steps, lemlist is a better product for you and the subscription is justified. If you would only ever use the email half, you are paying a multichannel price for a single channel.' },
  ],
  faq: [
    { q: 'Does the Cold Outreach Machine do LinkedIn outreach?', a: 'No, deliberately. Automating LinkedIn breaches the platform\'s terms of service, and enforcement typically hits the account you have spent years building. If multichannel sequencing is central to your process, lemlist is the better fit — with the caveat that you are accepting that platform risk either way. See [cold email vs LinkedIn](/cold-email-vs-linkedin-outreach/).' },
    { q: 'How does per-seat pricing compare over time?', a: 'For one person, break-even against lemlist\'s entry tier is roughly eight months. The gap widens sharply with team size, since the machine\'s licence covers one business rather than one user — though it is genuinely built for a single operator, so a large team would be better served by the platform regardless of price.' },
    { q: 'Can I still personalise images or use dynamic content?', a: 'No. The personalisation approach is different: rather than inserting variable elements into a fixed message, the whole message is written for that specific company from what it publishes. Which approach works better depends on your market — visual personalisation lands well in some, and reads as gimmicky in others.' },
    { q: 'Is there a free trial?', a: 'No. It is a one-time purchase of source code, which does not lend itself to trials. What is included instead is a live setup call and thirty days of direct support, so you are not left alone with a folder of files.' },
  ],
  related: [
    ['/instantly-alternative/', 'Instantly alternative'],
    ['/cold-email-vs-linkedin-outreach/', 'Cold email vs LinkedIn'],
    ['/best-cold-email-software/', 'How to choose cold email software'],
  ],
},

{
  slug: 'apollo-alternative',
  title: 'An Apollo Alternative Focused on Outreach, Not the Database',
  description: 'Apollo compared with a one-time-purchase outreach system: what you are really paying for with a contact database, when that data is worth it, and when finding companies yourself works better.',
  keywords: 'Apollo alternative, Apollo.io alternative, sales intelligence alternative, B2B database alternative',
  eyebrow: 'Comparison',
  short: 'Apollo alternative',
  h1: 'An Apollo alternative <span style="color:var(--grey-4);font-weight:300;">when you do not need the database.</span>',
  cta: 'product',
  body: [
    { lead: 'Apollo bundles two products: a large contact database and a sequencing tool. Whether it is worth its subscription depends almost entirely on whether the database is the thing you actually need — and for a lot of local and trade-focused businesses, it is not.' },
    { h: 'What you are really paying for' },
    'Apollo\'s value is the data: millions of contacts, filterable by industry, size, technology and role. For selling software to companies in defined categories, that is genuinely useful and hard to replicate.',
    'It is much less useful when your market is geographic and local. Independent boatbuilders in Northland, electricians in Christchurch, wineries on Waiheke — these businesses are often absent, out of date, or represented by a generic address in large databases. The good data for them is on their own websites and in trade directories.',
    { note: 'We have not verified Apollo\'s current pricing tiers and are not going to quote figures we have not checked. Their pricing page is the authority. What we can compare is the model: a recurring subscription for access to data and sequencing, versus a one-time purchase of a system that finds companies itself.' },
    { h: 'The comparison' },
    { table: {
      minWidth: 620,
      head: ['', 'Apollo', 'Cold Outreach Machine'],
      rows: [
        ['Model', 'Subscription, data plus sequencing', 'One-time purchase, US$499'],
        ['Where leads come from', 'Their contact database', 'Found from your description, from public sources'],
        ['Best for', 'Defined industries, tech, mid-market and up', 'Local, trade and niche markets'],
        ['Data freshness', 'Depends on their refresh cycle', 'Collected at the time you search'],
        ['Writing', 'Sequences and AI assistance', 'Individual message per company'],
        ['Data residency', 'Their platform', 'Your machine'],
        ['Access if you stop paying', 'Ends', 'Continues'],
      ],
    }},
    { h: 'Where Apollo is the better choice' },
    { list: [
      '**You sell into well-covered categories.** Software, mid-market and enterprise companies are exactly what large databases index well.',
      '**You filter on firmographics or technology.** Company size, funding, tech stack — that filtering is the product, and building it yourself is not realistic.',
      '**You need volume of contacts immediately.** A database gives you thousands today; researching companies yourself is slower.',
      '**You need multiple named contacts per company.** Finding the right person inside a large organisation is what the data is for.',
    ]},
    { h: 'Where finding companies yourself wins' },
    { list: [
      '**Local and trade markets.** These are poorly covered in aggregate databases and well covered by their own websites and trade registers.',
      '**Freshness.** A company\'s own site today beats a database record from an unknown date.',
      '**Sourcing transparency.** You know exactly where each address came from, which matters legally — see [finding business emails ethically](/finding-business-emails-ethically/) and the [Australian](/cold-email-law-australia/) rules in particular.',
      '**Cost over time.** Data subscriptions are typically the largest recurring line in an outbound stack.',
    ]},
  ],
  faq: [
    { q: 'Does the Cold Outreach Machine include a contact database?', a: 'No. It finds companies matching the profile you describe, from public sources, at the time you run it — rather than querying a pre-built database. For local and trade markets that produces fresher and more complete results; for filtering large organisations by firmographics, a database is the better instrument.' },
    { q: 'Can I import lists I already have?', a: 'Yes. Existing lists import as CSV, and everything you import is checked against the permanent contact registry so nobody is approached twice across campaigns.' },
    { q: 'Is data from a database legally safer than finding it yourself?', a: 'Not inherently, and often the opposite. Under Australian and European rules in particular, what matters is your lawful basis and your ability to show where data came from. A database record whose origin the vendor will not detail is harder to defend than an address you took from the company\'s own published contact page.' },
    { q: 'What if my market is not in any database?', a: 'That is the case this is built for, and it is more common than the tooling market suggests. Most local trades, marine businesses, hospitality operators and regional service companies are thinly covered in aggregate data but publish everything you need on their own sites.' },
  ],
  related: [
    ['/finding-business-emails-ethically/', 'Finding business emails ethically'],
    ['/best-cold-email-software/', 'How to choose cold email software'],
    ['/building-an-ideal-customer-profile/', 'Building an ideal customer profile'],
  ],
},

{
  slug: 'best-cold-email-software',
  title: 'How to Choose Cold Email Software — A Buyer\'s Guide, Not a Ranking',
  description: 'A framework for choosing outreach software: the four categories that exist, the questions that actually decide the answer, and why ranked "best of" lists mislead.',
  keywords: 'best cold email software, cold email tool comparison, choose outreach software, cold email platform guide',
  eyebrow: 'Buyer\'s guide',
  short: 'Choosing software',
  h1: 'Choosing cold email software. <span style="color:var(--grey-4);font-weight:300;">A framework, not a ranking.</span>',
  cta: 'product',
  body: [
    { lead: 'Most "best cold email software" lists are ranked by affiliate commission, and all of them share a deeper flaw: there is no best tool, because the tools solve different problems. What follows is the framework we would use, including the cases where our own product is the wrong answer.' },
    { h: 'The four categories' },
    { cards: [
      { t: '1. Subscription platforms', d: 'Instantly, Smartlead, lemlist and similar. Roughly $39–97/month. Managed warm-up, team features, support desks. You supply the list and the copy.' },
      { t: '2. Data platforms', d: 'Apollo and similar. A contact database plus sequencing. You are mainly paying for the data. Strong in well-indexed industries, weak in local and trade markets.' },
      { t: '3. Self-hosted senders', d: 'Cleanmails (~$199), Broadcast (~$250), AcelleMail (from ~$80). Bought once, run on your server. Delivery infrastructure — you still build the list and write everything.' },
      { t: '4. Find-and-write systems', d: 'Bought once and also do the research and writing. Our Cold Outreach Machine ($499) is in this category. Higher one-time cost, aimed at the part that takes the hours.' },
    ]},
    { h: 'The questions that decide it' },
    { steps: [
      '**What is your actual bottleneck?** If it is sending, categories 1 and 3 solve it. If it is finding companies and writing to them individually — which for most small businesses it is — only 2 and 4 touch it, and they do so differently.',
      '**How many mailboxes will you run?** More than a handful and managed warm-up becomes near-essential, which points to category 1.',
      '**How many people will use it?** A team needs shared state and permissions. A solo operator is paying for empty seats.',
      '**Is your market well covered by databases?** Software and mid-market: yes. Trades, marine, hospitality, local services: rarely.',
      '**How long will you be doing outbound?** Under six months, rent. Multiple years, the recurring fee stops being a rounding error.',
      '**Does your prospect data need to stay on your hardware?** If your client list is a core commercial asset, that narrows you to categories 3 and 4.',
    ]},
    { h: 'What almost nobody weighs correctly' },
    'The software fee is not the dominant cost of outbound. At twenty emails a day, researching and writing them by hand is roughly 650 to 1,000 hours a year. Priced at anything at all, that dwarfs any subscription on this page.',
    'Which reframes the whole decision: **compare tools on how many of those hours they give back**, not on their monthly price. A cheaper tool that leaves the research with you is not cheaper. [The full arithmetic is here.](/blog/cold-email-subscription-vs-one-time-cost/)',
    { h: 'When our answer is no' },
    'The Cold Outreach Machine is the wrong purchase if you run an agency sending for multiple clients, if you need managed warm-up across many mailboxes, if you need a support desk answering within minutes, or if you are still testing whether outbound works for you at all. In those cases a subscription platform is genuinely better and we would rather say so here than have you find out afterwards.',
    { note: 'One thing that applies whatever you buy: no software fixes a bad list or an unauthenticated domain. Get [SPF, DKIM and DMARC](/spf-dkim-dmarc-explained/) right and [define who you are writing to](/building-an-ideal-customer-profile/) before spending anything at all. Those two steps are free and they decide more than the tool does.' },
  ],
  faq: [
    { q: 'What is the best cold email software?', a: 'There isn\'t one, and any list that names a single winner is either simplifying or being paid. Subscription platforms win on scale and team features; data platforms win where their coverage is strong; self-hosted senders win on cost of ownership; find-and-write systems win when research is the bottleneck. The right question is which category matches your constraint.' },
    { q: 'Is free cold email software any good?', a: 'Open-source options like Mautic and Postal are free of licence cost but not free of cost — you pay in hosting and in the engineering hours deliverability management demands. If your time is worth anything, "free" tooling is often the most expensive category. It makes sense if you have technical capacity in-house and want full control.' },
    { q: 'Should I start with a free trial?', a: 'Yes, for subscription platforms — that is what trials are for, and you learn whether the workflow suits you. One-time purchases generally do not offer trials, which is a real disadvantage; the compensating factor should be a setup call and a support period, so you are not alone with the files.' },
    { q: 'How much should I expect to spend in total?', a: 'Realistically $400 to $1,500 in the first year, whichever model you choose, once you include software, a sending domain, an email service and AI writing costs. The variable that swamps all of it is your own time — which is why the tool that returns the most hours usually wins on total cost even at a higher sticker price.' },
  ],
  related: [
    ['/cold-email-software-one-time-payment/', 'Buy once vs subscribe'],
    ['/instantly-alternative/', 'Instantly alternative'],
    ['/apollo-alternative/', 'Apollo alternative'],
    ['/cold-email-deliverability-checklist/', 'The deliverability checklist'],
  ],
},

];
