/* Agents and automation fundamentals.
 *
 * These complement the existing business-process-automation and
 * ai-agents service pages rather than competing with them:
 * these explain the concepts, those sell the engagement. */

export default [

{
  slug: 'what-is-an-ai-agent',
  alt: { lang: 'fr', url: 'https://kanaky.xyz/qu-est-ce-qu-un-agent-ia/' },
  title: 'What Is an AI Agent? A Plain Explanation With Real Examples',
  description: 'What distinguishes an AI agent from a chatbot or an automation: tools, decisions and loops. Real examples, where agents genuinely help, and where they fail in ways worth knowing about first.',
  keywords: 'what is an AI agent, AI agent explained, AI agents vs chatbots, autonomous AI business',
  eyebrow: 'Fundamentals',
  short: 'What is an AI agent',
  h1: 'What is an AI agent? <span style="color:var(--grey-4);font-weight:300;">And how is it different from a chatbot?</span>',
  cta: 'service',
  body: [
    { lead: 'The word "agent" has been attached to almost everything, which has made it close to meaningless in marketing material. The distinction that actually matters is simple: a chatbot produces text, an automation follows a fixed path, and an agent decides what to do next and then does it.' },
    { h: 'The three things, distinguished' },
    { cards: [
      { t: 'A chatbot', d: 'Takes input, returns text. It cannot act on anything. Useful for answering, useless for doing.' },
      { t: 'An automation', d: 'Follows a path you defined. When X happens, do Y, then Z. Reliable and predictable, and it breaks on anything you did not anticipate.' },
      { t: 'An agent', d: 'Has a goal and a set of tools. It decides which to use, observes the result, and continues until the goal is met or it gives up. The path is not fixed in advance.' },
    ]},
    { h: 'What makes something an agent' },
    { list: [
      '**Tools.** It can do things beyond producing text — read a file, query a database, send an email, call an API, run a search.',
      '**Decisions.** It chooses which tool to use based on the situation, rather than following a predetermined order.',
      '**A loop.** It acts, observes what happened, and decides again. This is the part that distinguishes an agent from a single clever response.',
      '**A stopping condition.** It knows when it is done, or when it cannot proceed — and a badly built agent that lacks this is the most common failure in practice.',
    ]},
    { h: 'A concrete example' },
    'Take handling an inbound enquiry.',
    { table: {
      minWidth: 560,
      head: ['Approach', 'What happens'],
      rows: [
        ['Chatbot', 'Answers the question in the message, and nothing else.'],
        ['Automation', 'Sends a fixed acknowledgement, creates a CRM record, notifies you. Always the same steps.'],
        ['Agent', 'Reads the enquiry, looks the company up, checks whether they are an existing customer, decides whether it is a quote request or a support issue, drafts an appropriate response, schedules a follow-up — and escalates to you when it hits something it cannot judge.'],
      ],
    }},
    { h: 'Where agents genuinely help' },
    { list: [
      '**Work with variable steps.** Research tasks where what you do next depends on what you just found.',
      '**Multi-system tasks** that would otherwise need someone moving between four applications.',
      '**Triage and routing** where the classification requires reading and judgement rather than rules.',
      '**Anything currently requiring a person to check something before deciding.**',
    ]},
    { h: 'Where they fail' },
    'This matters more than the capability list, because agent failures are less obvious than automation failures:',
    { list: [
      '**They can be confidently wrong.** An agent that misreads a situation acts on the misreading, and the action can be harder to undo than a bad sentence.',
      '**Errors compound in loops.** A wrong step produces a wrong observation, which produces a worse next step.',
      '**Costs are unpredictable.** An agent that loops more than expected costs more than expected, occasionally by a lot.',
      '**Debugging is harder.** When an automation breaks, the path is fixed and you can find the step. When an agent goes wrong, you are reconstructing a decision sequence.',
    ]},
    { note: 'The practical rule: **use an automation where the path is known, an agent where it is not.** Most business problems described as needing agents actually have a fixed path, and would be better served by something predictable and cheaper to run.' },
  ],
  faq: [
    { q: 'What is the difference between an AI agent and automation?', a: 'An automation follows a path you defined in advance, which makes it predictable and brittle. An agent decides its own path using tools available to it, which makes it flexible and less predictable. If you can write down the steps, build an automation — it will be cheaper, faster and easier to debug.' },
    { q: 'Are AI agents reliable enough for business use?', a: 'For well-scoped tasks with a human reviewing consequential actions, yes. For unsupervised work with real consequences, be careful — they fail in ways that look like success, and errors compound inside loops. The common pattern that works is an agent that prepares and a person who approves.' },
    { q: 'What does an AI agent cost to run?', a: 'It depends on how many steps it takes, which varies per task and is not fully predictable. That is a genuine budgeting difference from fixed automations. Running the model locally removes per-step cost entirely, which is one reason agent-style work suits local deployment — see [running AI locally](/run-ai-locally-business/).' },
    { q: 'Do I need an agent, or just an automation?', a: 'Most businesses need automation and are being sold agents. If you can write the steps down, you do not need something that decides its own. Agents earn their complexity when the next step genuinely depends on what the previous one found.' },
  ],
  related: [
    ['/ai-automation-small-business/', 'AI automation for small business'],
    ['/workflow-automation-examples/', 'Workflow automation examples'],
    ['/ai-agents-new-caledonia/', 'AI agent development'],
  ],
},

{
  slug: 'ai-automation-small-business',
  title: 'AI Automation for Small Business — What to Do First',
  description: 'A practical sequence for a small business adopting AI: how to find what is worth automating, what to do first, what to avoid, and how to tell whether it worked.',
  keywords: 'AI automation small business, small business AI, business automation first steps, automate small business',
  eyebrow: 'Getting started',
  short: 'AI for small business',
  h1: 'AI automation for a small business. <span style="color:var(--grey-4);font-weight:300;">What to do first.</span>',
  cta: 'service',
  body: [
    { lead: 'Most small businesses adopting AI start with whatever they read about most recently, which is usually a chatbot, which is usually the wrong place to start. A better method: find where hours actually disappear, then automate the least interesting one.' },
    { h: 'Find the hours before choosing a tool' },
    { steps: [
      '**Track a week.** Note what you and your team actually do, in half-hour blocks. Everyone is surprised by this, and the surprise is the point.',
      '**Mark anything repetitive.** Same shape, different details. Copying between systems, re-typing, chasing, formatting, scheduling.',
      '**Add up the hours per task per month.** Small tasks done daily beat large ones done occasionally — this is where intuition is most often wrong.',
      '**Rank by hours, not by how annoying it is.** The most irritating task is rarely the most expensive one.',
      '**Start at the top of that list.** Not with the most interesting technology.',
    ]},
    { h: 'What usually surfaces' },
    'The same categories appear in most small businesses, regardless of industry:',
    { list: [
      '**Quoting and proposals** — high value, done at night, slow to go out.',
      '**Enquiry response** — where speed decides who wins the job.',
      '**Data re-entry between systems** — the purest waste in any business.',
      '**Chasing** — invoices, quotes, missing information. Universally avoided, universally valuable.',
      '**Reporting** — assembled by hand, monthly, by someone who could be doing something else.',
      '**Scheduling** — rosters, appointments, coordination.',
    ]},
    { h: 'What to avoid at the start' },
    { list: [
      '**Customer-facing chatbots.** High visibility, high risk to your reputation, usually low actual saving. If it goes wrong, your customers see it.',
      '**Replacing something that works.** Automating a functioning process to modernise it is how you buy a problem you did not have.',
      '**Broad rollouts.** One workflow, working properly, beats five half-configured.',
      '**Tools looking for problems.** If you cannot name the hours it saves before buying, do not buy it.',
    ]},
    { h: 'Judging whether it worked' },
    'Measure the same thing before and after: hours spent, response time, error rate, or revenue where the link is direct — a quote that goes out same-day rather than next-week has a measurable conversion effect.',
    'If you cannot measure a difference after a month, either it is not saving what you thought or it is not being used. Both are worth knowing, and both are common.',
    { note: 'Realistic expectation for a first project: **one process, five to fifteen hours a month back, working within a few weeks.** Anyone promising a transformed business is selling something. A few hours a month, compounding across several processes, is what actually changes a small business over a year.' },
  ],
  faq: [
    { q: 'What should a small business automate first?', a: 'Whichever repetitive task consumes the most hours per month — which you will only know after tracking a week honestly. For most small businesses it turns out to be quoting, enquiry response, or copying data between systems. Start there rather than with whatever technology is most discussed.' },
    { q: 'How much does it cost to get started?', a: 'Less than most expect for a single workflow, and it varies with what you already use. The larger cost is usually configuring it around how your business actually works rather than the software itself. Start with one process so the commitment matches the uncertainty.' },
    { q: 'Do I need technical staff?', a: 'For off-the-shelf tools, no. For anything connecting your existing systems together, you need either technical capability or someone to build it. The honest signal that you need help is when the answer involves the phrase "and then it needs to talk to".' },
    { q: 'What if it does not work?', a: 'Then you have learned something specific and cheap, provided you started with one process rather than five. The expensive failure is a broad rollout that nobody adopts — which is why a narrow first project with a measurable before-and-after is the right shape regardless of the technology.' },
  ],
  related: [
    ['/workflow-automation-examples/', 'Workflow automation examples'],
    ['/how-to-start-with-ai/', 'How to start with AI'],
    ['/ai-audit/', 'Book a free AI audit'],
  ],
},

{
  slug: 'workflow-automation-examples',
  alt: { lang: 'fr', url: 'https://kanaky.xyz/exemples-automatisation-pme/' },
  title: 'Workflow Automation Examples — Real Processes, Not Demos',
  description: 'Concrete workflow automations small businesses actually run: quote generation, enquiry triage, invoice chasing, reporting and document processing, with what each realistically saves.',
  keywords: 'workflow automation examples, business process automation examples, automate business tasks, automation use cases',
  eyebrow: 'Examples',
  short: 'Automation examples',
  h1: 'Workflow automation examples. <span style="color:var(--grey-4);font-weight:300;">Processes, not demos.</span>',
  cta: 'service',
  body: [
    { lead: 'Automation demos are usually chosen because they look impressive. These are chosen because they are the ones small businesses actually run for years, with a realistic view of what each returns.' },
    { h: 'Quote generation from a spoken description' },
    'The person doing the work describes the job into their phone. The system produces a formatted, priced quote for review and sending.',
    'Saves one to two hours an evening for anyone quoting daily, and the second-order effect is larger: quotes go out same-day, and in trades that frequently decides who gets the job. **Where it goes wrong:** pricing that is not kept current, and any version that sends without review.',
    { h: 'Enquiry triage and response' },
    'Incoming enquiries are read, classified, acknowledged with something relevant, recorded in your system, and either scheduled or escalated.',
    'Saves the interruption cost more than the minutes — you stop breaking off work to discover the call was routine. **Where it goes wrong:** the escalation path. Anything the system cannot judge must reach a person quickly and visibly.',
    { h: 'Invoice chasing' },
    'Overdue invoices trigger a sequence of polite, escalating reminders, stopping when payment arrives.',
    'Recovers money that would otherwise be written off, and removes the reluctance that stops most small business owners chasing at all. **Where it goes wrong:** chasing someone who already paid, which damages a relationship for a bookkeeping error. Reconciliation has to be reliable before this is switched on.',
    { h: 'Document data extraction' },
    'Invoices, receipts, statements and forms are read and their data extracted into your systems.',
    'Removes re-keying entirely, which in document-heavy businesses is the single largest mechanical saving available. **Where it goes wrong:** unverified extraction on anything financial. Review exceptions rather than every line, but review.',
    { h: 'Recurring reporting' },
    'Weekly or monthly reports assembled from your own data and delivered without anyone building them.',
    'Saves the hours, and more usefully makes reporting consistent — reports that were skipped in busy months now arrive. **Where it goes wrong:** reports nobody reads. Automating an unread report just makes it arrive faster.',
    { h: 'Maintenance and renewal reminders' },
    'Service history triggers a reminder when the next service is due.',
    'This one generates revenue rather than saving time, which makes it the highest-return automation for any business with recurring service work — marine, trades, plant, vehicles. **Where it goes wrong:** reminders on a fixed schedule regardless of actual service history, which reads as spam.',
    { h: 'Outbound prospecting' },
    'Companies matching a profile are found, researched, written to individually, and followed up.',
    'Replaces the three hours a day that doing this properly by hand requires — which is why almost nobody does it properly by hand. **Where it goes wrong:** volume without targeting, and any version that sends generic messages at scale. See [the outreach guides](/guides/).',
    { note: 'A pattern across all of these: the automations that survive are the ones removing work nobody wanted to do. Automating something people enjoy, or something that was working fine, tends to get quietly abandoned.' },
  ],
  faq: [
    { q: 'Which automation has the best return?', a: 'For most small businesses, whichever touches revenue rather than only cost. Maintenance reminders generate bookings; faster quoting wins jobs; invoice chasing recovers money. Time-saving automations are valuable, but the ones that produce revenue justify themselves faster and survive scrutiny better.' },
    { q: 'How long does it take to set one up?', a: 'A single well-scoped workflow is usually days to a few weeks, depending on how many existing systems it needs to connect to. The integration work — not the AI part — is what determines the timeline, and it is consistently underestimated.' },
    { q: 'Can I build these myself?', a: 'Simple versions, yes, using no-code tools if you are comfortable with them. Anything involving your existing systems, unusual data, or consequences when it fails is where building it properly matters. The signal that you need help is when a failure would go unnoticed.' },
    { q: 'What happens when an automation breaks?', a: 'The important question, and the one most often skipped. Every automation needs a failure path: someone notified, work queued rather than lost, and a manual fallback. An automation that fails silently is worse than no automation, because you stop watching the thing it was doing.' },
  ],
  related: [
    ['/ai-automation-small-business/', 'AI automation for small business'],
    ['/what-is-an-ai-agent/', 'What is an AI agent'],
    ['/business-process-automation/', 'Business process automation'],
  ],
},

{
  slug: 'ai-vs-hiring',
  alt: { lang: 'fr', url: 'https://kanaky.xyz/automatiser-ou-embaucher/' },
  title: 'AI or Hire Someone? An Honest Comparison for Small Businesses',
  description: 'When automation is the right answer and when a person is: cost, ramp-up, judgement, flexibility and the failure modes of each — plus the sequence that usually works best.',
  keywords: 'AI vs hiring, automate or hire, small business hiring decision, AI instead of employee',
  eyebrow: 'Decisions',
  short: 'AI or hire?',
  h1: 'Automate, or hire someone? <span style="color:var(--grey-4);font-weight:300;">It depends on the work.</span>',
  cta: 'service',
  body: [
    { lead: 'This is usually presented as a cost comparison, which misses what actually decides it. The question is not what each costs — it is whether the work needs judgement, and whether it varies. Those two answers determine the right choice more reliably than any spreadsheet.' },
    { h: 'The comparison' },
    { table: {
      minWidth: 620,
      head: ['', 'Automation', 'A person'],
      rows: [
        ['Cost shape', 'Build once, low ongoing', 'Ongoing salary, rising'],
        ['Ramp-up', 'Days to weeks', 'Weeks to months'],
        ['Handles the unexpected', 'Badly', 'Well'],
        ['Judgement', 'None', 'Yes'],
        ['Consistency', 'Perfect', 'Variable'],
        ['Scales with volume', 'Yes, cheaply', 'Requires hiring again'],
        ['Represents you to customers', 'Poorly', 'Well'],
        ['Fails by', 'Breaking visibly, or silently', 'Leaving, or disengaging'],
      ],
    }},
    { h: 'Automate when' },
    { list: [
      '**The task is the same shape every time.** Different details, identical process.',
      '**Volume is high and rising.** This is where the cost curves diverge sharply.',
      '**Consistency matters more than judgement.** Compliance records, data entry, reminders.',
      '**Nobody wants the job.** Tasks people dislike get done late and badly by humans, and are usually the ones automation handles perfectly.',
      '**It happens outside working hours.** Overnight, weekends, across timezones.',
    ]},
    { h: 'Hire when' },
    { list: [
      '**The work needs judgement.** Deciding, negotiating, weighing incomplete information.',
      '**It varies genuinely.** Not different details — different problems each time.',
      '**A customer relationship is involved.** People buy from people, particularly in trades and professional services.',
      '**Something is going wrong and you do not know why.** A person can investigate. An automation can only run.',
      '**You need capability you do not have.** Hiring buys expertise; automation only scales what you already know how to do.',
    ]},
    { h: 'The sequence that usually works' },
    'Not one or the other, but an order:',
    { steps: [
      '**Automate the mechanical layer first.** Data entry, chasing, reporting, scheduling.',
      '**See what remains.** Often a role that was 60% administration becomes a role that is 90% the valuable part.',
      '**Then hire for that.** You are recruiting for judgement rather than for processing, which is a better job and attracts better candidates.',
      '**Which is also cheaper**, because one person doing only the valuable work replaces what would have been two doing a mix.',
    ]},
    { note: 'A caution about the framing. "Replace a salary with software" is the pitch, and it is usually wrong in small businesses — because the person was doing fifteen things and the automation does two. What actually happens is that their week gets better and they take on work you could not previously afford to do.' },
  ],
  faq: [
    { q: 'Can AI replace an admin assistant?', a: 'Parts of the role, not the role. It handles data entry, scheduling, reminders and document processing well. It does not handle the phone call where someone is upset, the supplier who needs persuading, or the fifteen small judgement calls a day that nobody wrote down. Most businesses find the role changes rather than disappears.' },
    { q: 'Which is cheaper?', a: 'Automation, for high-volume repetitive work, by a wide margin over time. A person, for anything low-volume or judgement-dependent — because building and maintaining an automation for a task done twice a month is never worth it. Volume is the variable that decides.' },
    { q: 'What if I automate and then need to hire anyway?', a: 'That is a good outcome, not a failure. You will be hiring for a better-defined and more valuable role, and the automation continues carrying the mechanical layer underneath. The reverse sequence — hiring first, then automating — usually means hiring for a role that should not have existed.' },
    { q: 'How do I decide for a specific task?', a: 'Two questions. Does it need judgement? Does it vary genuinely, or only in details? If it needs judgement or truly varies, hire. If it is the same shape every time, automate — and be honest about which, because most people overestimate how much judgement their routine work requires.' },
  ],
  related: [
    ['/ai-automation-small-business/', 'AI automation for small business'],
    ['/workflow-automation-examples/', 'Workflow automation examples'],
    ['/ai-audit/', 'Book a free AI audit'],
  ],
},

{
  slug: 'how-to-start-with-ai',
  alt: { lang: 'fr', url: 'https://kanaky.xyz/commencer-avec-ia-entreprise/' },
  title: 'How to Start With AI in Your Business — A Sequence That Works',
  description: 'A realistic order for adopting AI: what to do in the first week, the first month and the first quarter, what to ignore, and how to avoid the pilot that never becomes anything.',
  keywords: 'how to start with AI, AI adoption small business, first AI project, AI implementation steps',
  eyebrow: 'Getting started',
  short: 'How to start with AI',
  h1: 'How to start with AI. <span style="color:var(--grey-4);font-weight:300;">A sequence, not a leap.</span>',
  cta: 'service',
  body: [
    { lead: 'The most common pattern in small-business AI adoption is a pilot that impresses everyone, changes nothing, and is quietly forgotten. Avoiding that has less to do with technology choice than with sequence — and with picking a first project small enough to finish.' },
    { h: 'Week one: look, do not buy' },
    { steps: [
      '**Track where the hours go.** A week of honest notes, in half-hour blocks.',
      '**Mark the repetitive ones.** Same shape, different details.',
      '**Total them by month.** Daily small tasks usually beat occasional large ones, and this is where intuition misleads most.',
      '**Use a general AI assistant on real work** — drafting, summarising, sorting. Free, and it calibrates your sense of what these tools are actually good at.',
      '**Buy nothing.** Anything bought this week is bought before you know what you need.',
    ]},
    { h: 'Month one: one workflow, end to end' },
    'Pick the single task with the most hours attached and automate only that. Not three. One.',
    { list: [
      '**Measure before.** Hours, response time, error rate. Without a baseline you cannot tell whether it worked, and you will end up arguing from impressions.',
      '**Build or buy the narrowest thing** that does the job.',
      '**Use it for a month** in real conditions, not in a test.',
      '**Measure after,** and be willing to conclude it did not help.',
    ]},
    { note: 'The discipline of one workflow is the whole method. A broad rollout gives you five half-working things nobody trusts, and no way to tell which part failed. One workflow that visibly works builds the confidence — and the internal evidence — for the next.' },
    { h: 'Quarter one: expand from evidence' },
    { list: [
      '**Add the next workflow** from your original list, now with a working precedent.',
      '**Connect systems** where the same data is being entered twice.',
      '**Decide your data boundary.** What may go to external services and what stays in-house. Write it down — see [AI and your business data](/ai-data-privacy-business/).',
      '**Train the people using it.** Adoption fails far more often than technology does.',
    ]},
    { h: 'What to ignore' },
    { list: [
      '**Strategy documents about AI transformation.** Automate one process. That is the strategy at this scale.',
      '**Tools without a named problem.** If you cannot say which hours it saves, it saves none.',
      '**Chatbots as a first project.** Visible, risky, usually low saving.',
      '**Rebuilding what works.** Modernising a functioning process is how you buy a problem.',
      '**Comparison articles.** Including this one, past the point where you know your top task. Reading is not a substitute for measuring your own week.',
    ]},
    { h: 'What good looks like at three months' },
    'One or two workflows running reliably, ten to thirty hours a month back, a clear sense of what these tools are and are not good at in your specific business, and a list of what to do next based on evidence rather than enthusiasm.',
    'That is an unglamorous outcome and a genuinely good one. It compounds; a transformation programme usually does not.',
  ],
  faq: [
    { q: 'What is the first thing a business should do with AI?', a: 'Track where the hours actually go for a week, before buying anything. Almost every business is surprised by the result, and the surprise is what makes the first project the right one instead of the most fashionable one.' },
    { q: 'How much should a first project cost?', a: 'Small enough that failing is acceptable. The point of a first project is learning whether this helps in your specific business — a commitment large enough to need justifying is a commitment that will get defended past the point of usefulness.' },
    { q: 'How long before I see a return?', a: 'For a well-chosen single workflow, weeks rather than months. If a first project has not shown a measurable difference after a month of real use, something is wrong with the choice of task or with adoption — and both are worth diagnosing before adding anything else.' },
    { q: 'Should I get help or do it myself?', a: 'Do the looking yourself — nobody else can tell you where your hours go, and an external assessment that skips this step is guessing. Get help for building anything that connects existing systems, or where a silent failure would matter. A free audit is a reasonable way to get a second opinion on the sequence before committing.' },
  ],
  related: [
    ['/ai-automation-small-business/', 'AI automation for small business'],
    ['/ai-vs-hiring/', 'Automate or hire?'],
    ['/ai-audit/', 'Book a free AI audit'],
  ],
},

];
