/* Guides en français — Nouvelle-Calédonie, Polynésie française, La Réunion.
 *
 * Le site comptait 69 pages EN pour 6 pages FR alors que trois marchés
 * sur cinq sont francophones. Ces pages sont des adaptations écrites en
 * français, pas des traductions mécaniques : monnaies locales (XPF, EUR),
 * réalités locales (TPE, connectivité), requêtes locales. Chaque page
 * déclare sa jumelle anglaise en hreflang quand elle existe. */

export default [

{
  slug: 'combien-coute-automatisation-ia',
  lang: 'fr',
  title: 'Combien coûte l’automatisation IA pour une TPE ou PME ? Les vrais chiffres',
  description: 'Les coûts réels de l’automatisation IA pour une petite entreprise : fourchettes honnêtes en XPF et en euros, ce qui fait varier le prix, les coûts cachés, et les cas où ça ne vaut pas la dépense.',
  keywords: 'prix automatisation IA, coût IA entreprise, combien coûte l’IA, tarif agence IA, automatisation PME prix, IA TPE coût',
  eyebrow: 'Prix',
  short: 'Combien coûte l’IA ?',
  h1: 'Combien coûte l’automatisation IA ? <span style="color:var(--grey-4);font-weight:300;">Les vrais chiffres.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'La plupart des agences répondent « ça dépend » puis demandent votre budget. Voici l’inverse : les fourchettes réelles du marché, ce qui fait bouger le prix, et — plus utile encore — les cas où la bonne réponse est de ne rien dépenser du tout.' },
    { h: 'Les fourchettes du marché' },
    { table: {
      minWidth: 560,
      head: ['Prestation', 'Fourchette typique', 'En XPF (indicatif)'],
      rows: [
        ['Audit d’opportunités', 'Gratuit à ~500 €', '0 – 60 000 F'],
        ['Un workflow automatisé (devis, relances, tri d’e-mails)', '1 000 – 4 000 €', '120 000 – 480 000 F'],
        ['Un agent IA connecté à vos outils', '3 000 – 8 000 €', '360 000 – 950 000 F'],
        ['Chatbot client sérieux (pas un gadget)', '2 500 – 8 000 €', '300 000 – 950 000 F'],
        ['Accompagnement mensuel', '100 – 500 €/mois', '12 000 – 60 000 F/mois'],
        ['Logiciel acheté une fois, que vous exploitez vous-même', 'dès ~300 USD', '~36 000 F, une fois'],
      ],
    }},
    'Ces chiffres recoupent ce que pratiquent les agences du Pacifique et de La Réunion en 2026 — certaines annoncent des projets « à partir de 500 € », d’autres des déploiements mid-market à plusieurs dizaines de milliers d’euros. L’écart n’est pas du hasard : il reflète ce que recouvre réellement la prestation.',
    { h: 'Ce qui fait varier le prix' },
    { list: [
      '**Le nombre de systèmes à connecter.** Automatiser un devis qui part de votre boîte mail coûte peu. Le connecter à votre logiciel de facturation, votre agenda et votre CRM, c’est là que les heures partent — l’intégration coûte plus cher que l’IA.',
      '**Le sur-mesure contre l’existant.** Si un logiciel du commerce fait déjà le travail, une version sur mesure est un mauvais achat. Une agence honnête vous le dit avant de vous vendre autre chose.',
      '**Qui porte la maintenance.** Un système livré puis abandonné se dégrade. Le forfait mensuel n’est pas du superflu si le système touche vos clients ou votre facturation.',
      '**La sensibilité des données.** Faire tourner l’IA en local, pour que les données ne quittent pas l’entreprise, demande une mise en place plus soignée — voir [l’IA locale en entreprise](/ia-locale-entreprise/).',
    ]},
    { h: 'Les coûts que personne ne met dans le devis' },
    { list: [
      '**Votre temps de cadrage.** Personne ne peut deviner où partent vos heures à votre place. Comptez quelques heures pour l’observer honnêtement — c’est gratuit et ça décide de tout le reste.',
      '**L’adoption.** Un outil que l’équipe n’utilise pas a un retour de zéro, quel que soit son prix. La formation fait partie du projet, pas du décor.',
      '**Les appels aux modèles IA.** Quelques centimes par exécution chez un fournisseur cloud. Négligeable à petit volume, réel à grand volume — et nul si le modèle tourne sur votre propre machine.',
    ]},
    { h: 'Quand ça ne vaut pas la dépense' },
    'Trois cas reviennent sans cesse, et un prestataire sérieux vous les nomme d’emblée :',
    { steps: [
      '**La tâche est occasionnelle.** Automatiser ce qui se produit deux fois par mois ne s’amortit presque jamais. Automatisez ce qui est quotidien.',
      '**Le vrai problème est ailleurs.** Si les clients ne rappellent pas parce que le devis part en huit jours, le problème n’est pas l’IA, c’est le délai — et parfois une simple réorganisation le règle sans logiciel.',
      '**Le travail demande du jugement.** Négocier, arbitrer, sentir un client : ça s’embauche, ça ne s’automatise pas. Voir [automatiser ou embaucher](/automatiser-ou-embaucher/).',
    ]},
    { note: 'Le calcul qui compte n’est pas le prix, c’est le prix **par heure récupérée**. Un workflow à 250 000 F qui rend dix heures par mois est remboursé en quelques mois, puis rapporte. Un gadget à 50 000 F qui ne rend rien est cher. Exigez de tout prestataire — nous compris — une estimation d’heures récupérées avant de signer.' },
  ],
  faq: [
    { q: 'Quel budget prévoir pour commencer ?', a: 'Pour un premier workflow bien choisi : entre 1 000 et 4 000 € (environ 120 000 à 480 000 F CFP) en sur-mesure, précédé d’un audit gratuit. Commencer par un seul processus limite le risque : si le résultat ne se mesure pas, vous le savez avant d’avoir engagé davantage.' },
    { q: 'Pourquoi de tels écarts entre agences ?', a: 'Parce que la prestation ne recouvre pas la même chose : un chatbot posé sur un site n’a rien à voir avec un agent connecté à la facturation et au planning. À devis égal, comparez le périmètre — nombre de systèmes connectés, qui maintient, qui possède le code — plutôt que le chiffre.' },
    { q: 'L’IA en local coûte-t-elle plus cher ?', a: 'Plus cher à installer, moins cher à l’usage : le matériel remplace l’abonnement, et chaque exécution devient gratuite. Pour des données clients sensibles ou un gros volume répétitif, le calcul penche vite du côté local — et vos données ne quittent jamais l’entreprise.' },
    { q: 'Le prix est-il différent en Nouvelle-Calédonie ou en Polynésie ?', a: 'Le travail se livre à distance, donc les fourchettes restent proches de la métropole. Ce qui change localement : la fiscalité (TGC, TVA polynésienne), la connectivité — un système qui continue de fonctionner quand la liaison tombe a une valeur particulière dans le Pacifique — et la rareté des prestataires qui connaissent vraiment le terrain.' },
  ],
  related: [
    ['/machine-prospection-commerciale/', 'La machine de prospection — 36 000 F, une fois'],
    ['/exemples-automatisation-pme/', '10 exemples d’automatisation pour TPE et PME'],
    ['/commencer-avec-ia-entreprise/', 'Par où commencer avec l’IA'],
    ['/automatisation-ia-nouvelle-caledonie/', 'Notre agence en Nouvelle-Calédonie'],
  ],
},

{
  slug: 'exemples-automatisation-pme',
  lang: 'fr',
  alt: { lang: 'en', url: 'https://kanaky.xyz/workflow-automation-examples/' },
  title: '10 exemples d’automatisation IA pour TPE et PME — du concret, pas des démos',
  description: 'Dix automatisations que des petites entreprises font réellement tourner : devis, relances d’impayés, tri des demandes, rapports, rappels d’entretien — avec ce que chacune rapporte et où elle déraille.',
  keywords: 'exemples automatisation entreprise, automatisation PME, cas d’usage IA TPE, automatiser devis, relance facture automatique',
  eyebrow: 'Exemples',
  short: 'Exemples d’automatisation',
  h1: 'Dix automatisations réelles. <span style="color:var(--grey-4);font-weight:300;">Pas des démos.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Les démonstrations d’IA sont choisies pour impressionner. Cette liste est choisie autrement : ce sont les automatisations que des petites entreprises font tourner pendant des années, avec ce que chacune rapporte réellement — et l’endroit précis où elle déraille quand elle est mal faite.' },
    { h: '1. Le devis dicté' },
    'L’artisan décrit le chantier à voix haute dans son téléphone ; un devis chiffré et mis en forme revient pour relecture et envoi. Une à deux heures rendues chaque soir — et surtout le devis part le jour même, ce qui décide souvent de qui décroche le chantier. **Déraille quand** : les prix ne sont pas tenus à jour, ou quand le devis part sans relecture.',
    { h: '2. La relance des impayés' },
    'Des rappels polis, progressifs, qui s’arrêtent dès l’encaissement. Récupère de l’argent qui aurait été passé en pertes, et supprime la gêne qui fait qu’on ne relance jamais soi-même. **Déraille quand** : le rapprochement bancaire n’est pas fiable et qu’on relance un client qui a déjà payé.',
    { h: '3. Le tri des demandes entrantes' },
    'Chaque demande est lue, classée — devis, urgence, question, démarchage — accusée réception avec un délai réaliste, et transmise au bon endroit. La valeur est dans les interruptions supprimées plus que dans les minutes. **Déraille quand** : ce que le système ne sait pas classer n’atteint pas un humain rapidement.',
    { h: '4. L’extraction de documents' },
    'Factures, relevés, bons de livraison lus automatiquement, leurs données versées dans vos outils. Fini la double saisie — le plus gros gisement mécanique des entreprises administratives. **Déraille quand** : personne ne vérifie les exceptions sur les montants.',
    { h: '5. Les rapports récurrents' },
    'L’activité du mois assemblée depuis vos propres données, sans que personne n’y passe son vendredi. **Déraille quand** : le rapport n’était lu par personne — l’automatiser ne le rend pas utile.',
    { h: '6. Les rappels d’entretien' },
    'L’historique de service déclenche le rappel au client : révision, contrôle, renouvellement. Celle-ci **rapporte** au lieu d’économiser : le client rappelé revient chez vous, pas chez le concurrent. La plus rentable pour tout métier à entretien récurrent — mécanique, clim, piscines, bateaux. **Déraille quand** : les rappels partent à date fixe sans tenir compte du vrai historique.',
    { h: '7. Le suivi des avenants de chantier' },
    'La modification convenue à l’oral sur le chantier devient une trace écrite datée, envoyée au client pour accord. Protège directement la marge — les litiges de fin de chantier naissent presque toujours d’un avenant sans trace. **Déraille quand** : on ne s’en sert que pour les gros montants ; ce sont les petits cumulés qui rongent la marge.',
    { h: '8. La réponse aux demandes de groupe et d’événements' },
    'Pour restaurants, caves et lieux : la demande de groupe reçoit une réponse immédiate avec les vraies disponibilités, les détails sont collectés avant qu’un humain n’intervienne. Les réservations les plus rentables sont les plus souvent perdues par lenteur. **Déraille quand** : le client sent qu’aucun humain ne prendra jamais le relais.',
    { h: '9. La veille de ses propres dossiers' },
    '« Qu’a-t-on facturé pour un chantier semblable l’an dernier ? » — répondu en secondes depuis vos propres documents, au lieu d’une heure de fouille. Particulièrement précieux quand l’IA tourne en local et peut donc lire **tous** les dossiers sans qu’ils sortent de l’entreprise.',
    { h: '10. La prospection sortante' },
    'Trouver les entreprises qui correspondent à votre client idéal, écrire à chacune un message qui la concerne vraiment, envoyer à un rythme prudent. Fait à la main, c’est trois heures par jour — c’est pourquoi personne ne le tient. **Déraille quand** : on envoie du générique en volume ; voir [nos guides sur la prospection](/guides/).',
    { note: 'Le fil commun : les automatisations qui survivent sont celles qui suppriment un travail que personne ne voulait faire. Automatiser ce qui fonctionne déjà, ou ce que quelqu’un aime faire, finit abandonné dans les six mois.' },
  ],
  faq: [
    { q: 'Laquelle rapporte le plus vite ?', a: 'Celles qui touchent au chiffre d’affaires plutôt qu’au temps : rappels d’entretien (des réservations directes), devis le jour même (des chantiers gagnés), relances d’impayés (de l’argent récupéré). Les gains de temps sont réels mais se démontrent moins vite.' },
    { q: 'Faut-il tout automatiser d’un coup ?', a: 'Non — un seul processus, mesuré avant et après, pendant un mois. Cinq chantiers à moitié configurés que personne n’utilise coûtent plus cher qu’un seul qui tourne. Le premier qui marche crée la confiance et finance le suivant.' },
    { q: 'Ces exemples marchent-ils pour une entreprise de deux personnes ?', a: 'Souvent mieux : dans une TPE, personne n’absorbe l’administratif à votre place, donc chaque heure rendue est une heure à vous. Le devis dicté et la relance d’impayés sont typiquement les premiers pas des très petites structures.' },
    { q: 'Que se passe-t-il quand l’automatisation tombe en panne ?', a: 'C’est la question à poser avant d’acheter. Toute automatisation sérieuse prévoit un chemin d’échec : quelqu’un est prévenu, le travail est mis en file plutôt que perdu, et un mode manuel reste possible. Une automatisation qui échoue en silence est pire que pas d’automatisation.' },
  ],
  related: [
    ['/combien-coute-automatisation-ia/', 'Combien ça coûte, vraiment'],
    ['/commencer-avec-ia-entreprise/', 'Par où commencer avec l’IA'],
    ['/qu-est-ce-qu-un-agent-ia/', 'Qu’est-ce qu’un agent IA ?'],
  ],
},

{
  slug: 'commencer-avec-ia-entreprise',
  lang: 'fr',
  alt: { lang: 'en', url: 'https://kanaky.xyz/how-to-start-with-ai/' },
  title: 'Par où commencer avec l’IA dans votre entreprise — une méthode qui marche',
  description: 'Une séquence réaliste pour adopter l’IA dans une TPE ou PME : la première semaine, le premier mois, le premier trimestre — et ce qu’il faut ignorer pour ne pas finir avec un pilote abandonné.',
  keywords: 'commencer avec l’IA, adopter IA entreprise, premier projet IA, IA PME par où commencer',
  eyebrow: 'Premiers pas',
  short: 'Par où commencer',
  h1: 'Commencer avec l’IA. <span style="color:var(--grey-4);font-weight:300;">Une séquence, pas un saut.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Le scénario le plus fréquent dans les petites entreprises : un pilote IA qui impressionne tout le monde, ne change rien, et s’oublie. L’éviter tient moins au choix de l’outil qu’à l’ordre des opérations — et à un premier projet assez petit pour être terminé.' },
    { h: 'Semaine 1 : regarder, ne rien acheter' },
    { steps: [
      '**Notez où partent les heures.** Une semaine de notes honnêtes, par demi-heures. Tout le monde est surpris du résultat — et la surprise est précisément l’information.',
      '**Marquez ce qui se répète.** Même forme, détails différents : ressaisies, relances, mises en forme, plannings.',
      '**Totalisez par mois.** Les petites tâches quotidiennes battent presque toujours les grosses tâches occasionnelles — c’est là que l’intuition trompe le plus.',
      '**Essayez un assistant IA généraliste sur du vrai travail** — rédiger, résumer, trier. C’est gratuit et ça calibre ce que ces outils savent réellement faire.',
      '**N’achetez rien.** Tout ce qui s’achète cette semaine s’achète avant de savoir ce qu’il vous faut.',
    ]},
    { h: 'Mois 1 : un seul processus, de bout en bout' },
    'Prenez la tâche qui totalise le plus d’heures et n’automatisez que celle-là. Pas trois. Une.',
    { list: [
      '**Mesurez avant** : heures, délai de réponse, taux d’erreur. Sans point de départ, impossible de savoir si ça a marché — on finit par en débattre à l’impression.',
      '**Construisez ou achetez le plus petit outil** qui fait le travail.',
      '**Servez-vous-en un mois** en conditions réelles, pas en test.',
      '**Mesurez après** — et acceptez, le cas échéant, de conclure que ça n’a pas aidé. C’est une information qui vaut de l’argent.',
    ]},
    { note: 'La discipline du processus unique est toute la méthode. Un déploiement large donne cinq choses à moitié configurées auxquelles personne ne fait confiance. Un seul workflow qui marche visiblement crée la légitimité — et la preuve interne — pour le suivant.' },
    { h: 'Trimestre 1 : étendre depuis la preuve' },
    { list: [
      '**Ajoutez le processus suivant** de votre liste initiale, fort d’un précédent qui tourne.',
      '**Connectez les systèmes** partout où la même donnée est saisie deux fois.',
      '**Décidez votre frontière de données** : ce qui peut passer par des services externes, ce qui reste dans l’entreprise. Écrivez-la — voir [l’IA locale en entreprise](/ia-locale-entreprise/).',
      '**Formez les gens qui s’en servent.** L’adoption échoue bien plus souvent que la technique.',
    ]},
    { h: 'À ignorer' },
    { list: [
      '**Les stratégies de transformation IA.** À l’échelle d’une TPE, automatiser un processus, c’est la stratégie.',
      '**Les outils sans problème nommé.** Si vous ne savez pas dire quelles heures il rend, il n’en rend aucune.',
      '**Le chatbot comme premier projet.** Visible, risqué pour l’image, gain réel généralement faible.',
      '**Refaire ce qui marche.** Moderniser un processus qui fonctionne, c’est acheter un problème qu’on n’avait pas.',
    ]},
    { h: 'À quoi ressemble la réussite à trois mois' },
    'Un ou deux workflows qui tournent, dix à trente heures rendues par mois, une idée nette de ce que ces outils savent faire *dans votre entreprise à vous*, et une liste de suites fondée sur des mesures plutôt que sur l’enthousiasme. C’est un résultat sans paillettes — et c’est celui qui se cumule.',
  ],
  faq: [
    { q: 'Quelle est la toute première chose à faire ?', a: 'Suivre une semaine de travail à la trace avant d’acheter quoi que ce soit. Presque toutes les entreprises découvrent que leurs heures ne partent pas où elles croyaient — et cette découverte transforme le premier projet en bon projet plutôt qu’en projet à la mode.' },
    { q: 'Combien de temps avant un retour visible ?', a: 'Pour un premier workflow bien choisi : des semaines, pas des mois. Si rien ne se mesure après un mois d’usage réel, le problème est dans le choix de la tâche ou dans l’adoption — et il vaut mieux le diagnostiquer avant d’étendre.' },
    { q: 'Faut-il se faire accompagner ou faire seul ?', a: 'L’observation, faites-la vous-même — personne d’autre ne peut savoir où partent vos heures, et un prestataire qui saute cette étape devine. Pour construire ce qui se connecte à vos systèmes existants, ou ce dont l’échec silencieux coûterait cher, l’accompagnement se justifie.' },
    { q: 'Et si mon équipe est réticente ?', a: 'Commencez par la tâche que tout le monde déteste — la ressaisie, les relances. Personne ne défend la corvée supprimée. La réticence vient presque toujours d’outils imposés sur du travail que les gens aimaient, ou de la peur de mal faire : les deux se règlent par le choix de la première cible et par la formation.' },
  ],
  related: [
    ['/exemples-automatisation-pme/', '10 exemples concrets'],
    ['/combien-coute-automatisation-ia/', 'Combien ça coûte, vraiment'],
    ['/automatiser-ou-embaucher/', 'Automatiser ou embaucher ?'],
  ],
},

{
  slug: 'ia-locale-entreprise',
  lang: 'fr',
  alt: { lang: 'en', url: 'https://kanaky.xyz/run-ai-locally-business/' },
  title: 'L’IA en local : vos données ne quittent pas l’entreprise — guide pratique',
  description: 'Faire tourner l’IA sur vos propres machines : ce que ça permet, ce qu’il faut comme matériel, ce que ça coûte, les limites honnêtes — et pourquoi la question se pose autrement dans le Pacifique.',
  keywords: 'IA locale entreprise, IA souveraineté données, faire tourner IA localement, Ollama entreprise français, IA sans cloud, données sensibles IA',
  eyebrow: 'IA locale',
  short: 'L’IA en local',
  h1: 'L’IA en local. <span style="color:var(--grey-4);font-weight:300;">Vos données restent chez vous.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Depuis peu, des modèles d’IA sérieux tournent sur un ordinateur d’entreprise ordinaire. Pas les plus puissants du monde — mais assez bons pour résumer, trier, rédiger et interroger vos propres documents. Et pendant qu’ils travaillent, rien ne sort de chez vous : ni le contrat, ni le fichier clients, ni la comptabilité.' },
    { h: 'Pourquoi c’est un vrai sujet, pas une lubie' },
    'L’utilité d’une IA grandit avec ce qu’on lui laisse voir. Une IA qui a accès à vos dossiers, vos devis passés et vos échanges rend des services qu’aucun assistant généraliste ne peut rendre. Mais on ne donne cet accès qu’à ce qu’on contrôle entièrement — pas à un service tiers dont les conditions changent et dont les serveurs sont à douze mille kilomètres.',
    'La confidentialité n’est donc pas un supplément moral : **c’est la condition de l’utilité.** Une IA à qui on ne peut pas tout montrer ne rend qu’une fraction de ses services.',
    { h: 'Ce qui marche bien en local' },
    { list: [
      '**Résumer et extraire** : contrats, factures, courriers, comptes rendus — souvent les documents les plus sensibles de l’entreprise.',
      '**Rédiger des premières versions** : courriers types, réponses, traductions.',
      '**Trier et classer** : demandes entrantes, documents, tickets.',
      '**Interroger vos propres dossiers** : « qu’avait-on facturé pour un chantier semblable ? » répondu en secondes — l’usage le plus précieux, et celui qu’on n’oserait jamais confier à un service externe.',
      '**Tout ce qui est répétitif à grand volume** : en local, chaque exécution est gratuite.',
    ]},
    { h: 'Ce qui reste meilleur dans le cloud' },
    'Le dire franchement vaut mieux que le vendre : les raisonnements les plus difficiles, les très longs documents et les toutes dernières capacités restent l’avantage des grands modèles hébergés. L’arrangement raisonnable, que pratiquent les entreprises qui s’y prennent bien, est un partage : **le sensible et le répétitif en local, l’exceptionnel et le difficile dans le cloud** — et la frontière écrite noir sur blanc.',
    { h: 'Le matériel, concrètement' },
    { table: {
      minWidth: 520,
      head: ['Machine', 'Ce qu’elle permet'],
      rows: [
        ['Un portable 16 Go que vous avez déjà', 'Petits modèles — assez pour essayer une semaine et se faire une idée'],
        ['Un Mac 32–64 Go de mémoire unifiée', 'Le bon choix pour la plupart des TPE/PME : silencieux, sobre, capable'],
        ['Une station avec carte graphique dédiée', 'Modèles plus grands, plusieurs utilisateurs, vitesse'],
      ],
    }},
    'L’installation de base tient en une commande avec [Ollama](https://ollama.com), gratuit. La vraie question n’est jamais l’installation : c’est de brancher le modèle sur vos documents proprement, avec des droits d’accès — qui, dans l’entreprise, peut interroger quoi.',
    { h: 'La dimension Pacifique' },
    'Écrit depuis Nouméa et Auckland, ce point n’est pas théorique. Quand la connectivité d’un territoire tient à un câble, un outil de travail qui exige une liaison permanente avec un serveur à l’autre bout du monde a un mode de panne que tout le monde ici a déjà vécu. **Un système qui continue de fonctionner quand la liaison tombe n’est pas un luxe, c’est un cahier des charges.**',
    'Et il y a plus profond que la panne : la question de savoir où vivent les données d’un territoire — celles des entreprises, des institutions, des langues — est une question de souveraineté avant d’être une question d’infrastructure. C’est la conviction qui structure notre travail, du [dictionnaire des langues kanak](https://dictionnaire.kanaky.xyz) à nos systèmes privés. Nous l’avons développée dans [notre texte de position](/blog/future-of-ai-is-local-and-personal/) (en anglais).',
    { note: 'Par où commencer sans rien risquer : installez Ollama sur une machine existante, utilisez un petit modèle une semaine sur du vrai travail, et notez ce qui est « assez bon » et ce qui ne l’est pas. Vous saurez alors quoi construire — et si ça vaut un investissement matériel.' },
  ],
  faq: [
    { q: 'L’IA locale est-elle aussi bonne que ChatGPT ?', a: 'Pas sur les tâches les plus difficiles — les grands modèles hébergés gardent l’avantage en raisonnement complexe. Pour résumer, trier, rédiger et interroger vos propres documents, les bons modèles ouverts sont assez proches pour que la différence ne change généralement pas le résultat. Testez sur votre travail réel, pas sur des benchmarks.' },
    { q: 'Est-ce légal d’utiliser l’IA sur des données clients ?', a: 'C’est précisément là que le local change la donne : quand le modèle tourne chez vous, aucune donnée n’est transmise à un tiers — la question du transfert ne se pose plus. Restent vos obligations propres (RGPD à La Réunion, loi Informatique et libertés applicable en Nouvelle-Calédonie et en Polynésie) : accès, conservation, sécurité. Elles s’appliquent à vos systèmes, IA ou pas.' },
    { q: 'Quel budget matériel prévoir ?', a: 'Pour essayer : zéro, votre machine actuelle suffit probablement. Pour un usage quotidien confortable : un Mac à mémoire généreuse ou une station avec carte graphique — un investissement à quatre chiffres en euros, amorti d’autant plus vite que le volume est grand, puisque chaque exécution devient gratuite.' },
    { q: 'Et si la machine tombe en panne ?', a: 'Comme pour tout outil critique : une sauvegarde des données et de la configuration, et un plan B écrit. La différence avec un service cloud, c’est que la panne est la vôtre — réparable — et non celle d’un fournisseur, sa politique tarifaire ou ses conditions d’utilisation, sur lesquelles vous ne pouvez rien.' },
  ],
  related: [
    ['/exemples-automatisation-pme/', '10 exemples d’automatisation'],
    ['/combien-coute-automatisation-ia/', 'Combien ça coûte, vraiment'],
    ['/automatisation-ia-nouvelle-caledonie/', 'Notre agence en Nouvelle-Calédonie'],
  ],
},

{
  slug: 'automatiser-ou-embaucher',
  lang: 'fr',
  alt: { lang: 'en', url: 'https://kanaky.xyz/ai-vs-hiring/' },
  title: 'Automatiser ou embaucher ? Le comparatif honnête pour une petite entreprise',
  description: 'Quand l’automatisation est la bonne réponse et quand c’est une personne qu’il faut : coûts, montée en charge, jugement, imprévu — et la séquence qui marche le mieux dans les TPE et PME.',
  keywords: 'automatiser ou embaucher, IA ou salarié, coût automatisation vs embauche, remplacer par IA',
  eyebrow: 'Décisions',
  short: 'Automatiser ou embaucher ?',
  h1: 'Automatiser, ou embaucher ? <span style="color:var(--grey-4);font-weight:300;">Ça dépend du travail.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'On présente souvent ce choix comme une comparaison de coûts. C’est passer à côté de ce qui le décide vraiment : le travail demande-t-il du jugement, et varie-t-il réellement ? Ces deux réponses tranchent plus sûrement que n’importe quel tableur.' },
    { h: 'Le comparatif' },
    { table: {
      minWidth: 560,
      head: ['', 'Automatisation', 'Une personne'],
      rows: [
        ['Forme du coût', 'Construction une fois, entretien faible', 'Salaire et charges, récurrents'],
        ['Montée en charge', 'Jours à semaines', 'Semaines à mois'],
        ['Face à l’imprévu', 'Mauvaise', 'Bonne'],
        ['Jugement', 'Aucun', 'Oui'],
        ['Régularité', 'Parfaite', 'Variable'],
        ['Croissance du volume', 'Absorbée à coût quasi nul', 'Nouvelle embauche'],
        ['Relation client', 'Faible', 'Forte'],
        ['Mode d’échec', 'Panne visible — ou silencieuse', 'Départ, désengagement'],
      ],
    }},
    { h: 'Automatisez quand' },
    { list: [
      '**La tâche a la même forme à chaque fois.** Détails différents, processus identique.',
      '**Le volume est grand et monte.** C’est là que les deux courbes de coût divergent.',
      '**La régularité compte plus que le jugement** : saisies, rappels, registres, conformité.',
      '**Personne ne veut de cette tâche.** Ce que les humains font tard et mal, l’automatisation le fait parfaitement — et personne ne regrette la corvée.',
      '**Ça se passe hors horaires** : la nuit, le week-end, entre fuseaux.',
    ]},
    { h: 'Embauchez quand' },
    { list: [
      '**Le travail demande du jugement** : décider, négocier, arbitrer sur information incomplète.',
      '**Ça varie vraiment** — pas des détails différents : des problèmes différents.',
      '**La relation client est en jeu.** On achète à des gens, surtout dans l’artisanat et les services.',
      '**Quelque chose va mal sans qu’on sache pourquoi.** Une personne enquête ; une automatisation ne sait qu’exécuter.',
      '**Il vous manque une compétence.** L’embauche achète un savoir-faire ; l’automatisation ne fait que démultiplier ce que vous savez déjà faire.',
    ]},
    { h: 'La séquence qui marche' },
    { steps: [
      '**Automatisez d’abord la couche mécanique** : saisies, relances, rapports, plannings.',
      '**Regardez ce qui reste.** Un poste qui était à 60 % d’administratif devient un poste à 90 % de valeur.',
      '**Embauchez pour ce poste-là.** Vous recrutez du jugement, pas de la saisie — un meilleur poste, de meilleurs candidats.',
      '**Et c’est moins cher** : une personne sur le travail à valeur remplace ce qui en aurait demandé deux sur un mélange.',
    ]},
    { note: 'Méfiez-vous de l’argument « remplacez un salaire par un logiciel ». Dans une petite entreprise, la personne faisait quinze choses ; l’automatisation en fait deux. Ce qui se passe en réalité : sa semaine s’améliore, et elle prend le travail que vous ne pouviez pas vous offrir avant.' },
  ],
  faq: [
    { q: 'L’IA peut-elle remplacer un assistant administratif ?', a: 'Des morceaux du poste, pas le poste : saisie, planning, rappels, traitement de documents — oui. L’appel du client mécontent, le fournisseur à convaincre et les quinze micro-décisions quotidiennes que personne n’a écrites — non. Dans la pratique, le poste change de contenu plus qu’il ne disparaît.' },
    { q: 'Qu’est-ce qui coûte le moins cher ?', a: 'L’automatisation pour le répétitif à volume, largement, sur la durée. Une personne pour tout ce qui est rare ou demande du jugement — construire et entretenir une automatisation pour une tâche bimensuelle ne s’amortit jamais. C’est le volume qui tranche.' },
    { q: 'Et si j’automatise puis dois embaucher quand même ?', a: 'C’est un bon scénario, pas un échec : vous embauchez alors pour un poste mieux défini et plus intéressant, pendant que l’automatisation continue de porter la couche mécanique en dessous. La séquence inverse — embaucher d’abord, automatiser ensuite — crée souvent un poste qui n’aurait pas dû exister.' },
    { q: 'Comment trancher pour une tâche précise ?', a: 'Deux questions : demande-t-elle du jugement ? Varie-t-elle vraiment, ou seulement dans les détails ? Jugement ou vraie variation : embauchez. Même forme à chaque fois : automatisez — et soyez honnête sur la réponse, on surestime presque toujours le jugement que réclame son propre travail routinier.' },
  ],
  related: [
    ['/commencer-avec-ia-entreprise/', 'Par où commencer avec l’IA'],
    ['/exemples-automatisation-pme/', '10 exemples concrets'],
    ['/combien-coute-automatisation-ia/', 'Combien ça coûte, vraiment'],
  ],
},

{
  slug: 'qu-est-ce-qu-un-agent-ia',
  lang: 'fr',
  alt: { lang: 'en', url: 'https://kanaky.xyz/what-is-an-ai-agent/' },
  title: 'Qu’est-ce qu’un agent IA ? Explication simple, exemples réels',
  description: 'La différence réelle entre un chatbot, une automatisation et un agent IA : outils, décisions, boucle d’action — avec un exemple concret et les cas où un agent est le mauvais choix.',
  keywords: 'agent IA définition, qu’est-ce qu’un agent IA, agent IA vs chatbot, agent intelligent entreprise',
  eyebrow: 'Notions',
  short: 'Qu’est-ce qu’un agent IA ?',
  h1: 'Qu’est-ce qu’un agent IA ? <span style="color:var(--grey-4);font-weight:300;">Et en quoi ce n’est pas un chatbot.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Le mot « agent » est aujourd’hui collé sur à peu près tout, ce qui l’a vidé de son sens commercial. La distinction utile tient en une phrase : un chatbot produit du texte, une automatisation suit un chemin fixé d’avance, un agent décide de la prochaine étape puis l’exécute.' },
    { h: 'Les trois, distingués' },
    { cards: [
      { t: 'Le chatbot', d: 'Reçoit une question, rend du texte. Il ne peut agir sur rien. Utile pour répondre, inutile pour faire.' },
      { t: 'L’automatisation', d: 'Suit le chemin que vous avez défini : quand X arrive, faire Y puis Z. Fiable, prévisible — et cassante dès que survient ce que vous n’aviez pas prévu.' },
      { t: 'L’agent', d: 'A un objectif et des outils. Il choisit lequel utiliser, observe le résultat, recommence — jusqu’à l’objectif atteint ou l’échec constaté. Le chemin n’est pas écrit d’avance.' },
    ]},
    { h: 'Un exemple concret' },
    'Une demande arrive dans la boîte de l’entreprise.',
    { table: {
      minWidth: 520,
      head: ['Approche', 'Ce qui se passe'],
      rows: [
        ['Chatbot', 'Répond à la question posée. Rien d’autre.'],
        ['Automatisation', 'Accusé de réception type, fiche créée, notification. Toujours les mêmes étapes.'],
        ['Agent', 'Lit la demande, cherche qui est l’entreprise, vérifie si c’est un client existant, qualifie — devis, urgence, question —, prépare une réponse adaptée, programme une relance. Et vous passe la main dès qu’il tombe sur ce qu’il ne sait pas juger.'],
      ],
    }},
    { h: 'Ce qui fait qu’un système est un agent' },
    { list: [
      '**Des outils** : lire un fichier, interroger une base, envoyer un message, appeler un service.',
      '**Des décisions** : il choisit l’outil selon la situation, au lieu de dérouler un ordre prédéfini.',
      '**Une boucle** : agir, observer, décider à nouveau. C’est elle qui distingue l’agent d’une réponse isolée, aussi brillante soit-elle.',
      '**Une condition d’arrêt** : savoir quand c’est fini — ou quand il n’y arrivera pas. Son absence est le défaut de fabrication le plus courant.',
    ]},
    { h: 'Où les agents échouent' },
    'Cette partie compte plus que la liste des prouesses, parce que les échecs d’agents se voient moins que les pannes d’automatisations :',
    { list: [
      '**Ils peuvent se tromper avec assurance.** Un agent qui a mal lu la situation agit sur sa mauvaise lecture — et une action se rattrape moins bien qu’une phrase.',
      '**Les erreurs se cumulent en boucle.** Un pas faux produit une observation fausse, qui produit un pas pire.',
      '**Le coût est peu prévisible** : un agent qui boucle plus que prévu coûte plus que prévu.',
      '**Le débogage est plus dur.** Une automatisation cassée se lit étape par étape ; un agent qui a dérivé se reconstitue décision par décision.',
    ]},
    { note: 'La règle pratique : **là où le chemin est connu, une automatisation ; là où il ne l’est pas, un agent.** La plupart des besoins décrits comme « il nous faut un agent » ont en réalité un chemin parfaitement connu — et seraient mieux servis par quelque chose de prévisible et moins cher à faire tourner.' },
  ],
  faq: [
    { q: 'Quelle différence entre un agent IA et une automatisation ?', a: 'L’automatisation suit un chemin défini d’avance — prévisible et rigide. L’agent choisit son chemin avec les outils qu’on lui donne — souple et moins prévisible. Si vous pouvez écrire les étapes sur une feuille, il vous faut une automatisation : moins chère, plus rapide, plus simple à déboguer.' },
    { q: 'Les agents sont-ils assez fiables pour une entreprise ?', a: 'Pour des tâches bien bornées, avec un humain qui valide les actions à conséquence : oui. En autonomie totale sur des actions réelles : prudence — ils échouent d’une manière qui ressemble à une réussite. Le motif qui marche : l’agent prépare, l’humain approuve.' },
    { q: 'Combien coûte un agent à l’usage ?', a: 'Cela dépend du nombre d’étapes qu’il prend, qui varie par tâche — une vraie différence budgétaire avec l’automatisation à coût fixe. Faire tourner le modèle en local supprime le coût par étape, ce qui rend les agents nettement plus sereins à exploiter — voir l’IA en local.' },
    { q: 'Ai-je besoin d’un agent, ou d’une simple automatisation ?', a: 'Dans la plupart des petites entreprises : d’une automatisation, alors qu’on leur vend un agent. L’agent gagne sa complexité quand l’étape suivante dépend réellement de ce que la précédente a découvert — recherche, tri qui demande de la lecture, tâches traversant plusieurs systèmes.' },
  ],
  related: [
    ['/exemples-automatisation-pme/', '10 exemples concrets'],
    ['/ia-locale-entreprise/', 'L’IA en local'],
    ['/automatiser-ou-embaucher/', 'Automatiser ou embaucher ?'],
  ],
},

];
