/* AI by trade and sector.
 *
 * The trap with a cluster like this is writing the same page ten
 * times with the job title swapped — which is exactly what Google
 * calls a doorway page, and rightly. Each page here starts from
 * that trade's actual working day and the specific admin that eats
 * it. If a paragraph would read identically for a different trade,
 * it does not belong. */

export default [

{
  slug: 'ai-for-electricians',
  title: 'AI for Electricians — Where It Saves Real Hours',
  description: 'Practical AI for electrical contractors: quoting from voice notes after a day on the tools, compliance paperwork, job scheduling and chasing work — with an honest view of what is not worth it.',
  keywords: 'AI for electricians, electrical contractor software, electrician quoting automation, trade business AI',
  eyebrow: 'Trades',
  short: 'AI for electricians',
  h1: 'AI for electricians. <span style="color:var(--grey-4);font-weight:300;">Mostly, it is the quoting.</span>',
  cta: 'service',
  body: [
    { lead: 'The pattern in electrical contracting is consistent enough to name: the work finishes at five, and the paperwork starts at eight. Quotes get written at the kitchen table, compliance forms pile up, and the enquiry that came in at eleven gets a reply on Thursday — by which time someone else has already quoted it.' },
    { h: 'Quoting is where the hours are' },
    'A quote for a switchboard upgrade or a rewire is not intellectually hard; it is a known set of materials, a labour estimate and a callout. What makes it expensive is that it happens after a full day of physical work, when nobody wants to open a laptop.',
    'Dictating the job into a phone in the van and getting back a formatted, priced quote changes the economics of that entirely — not because the quote is better, but because it goes out the same evening instead of the following week. **In trades, speed of response is frequently what decides the job**, and the tradie who quotes on the day wins work from the one who quotes properly on Friday.',
    { h: 'The compliance layer' },
    'Certificates of compliance, electrical safety certificates, records of testing — jurisdiction-dependent, repetitive, and legally required. AI does not sign these and should not, but it can populate the routine fields from job details you already recorded, leaving you to check and sign rather than transcribe.',
    { h: 'Where else it pays' },
    { list: [
      '**Enquiry response.** An immediate acknowledgement with a realistic timeframe, so the customer stops phoning the next electrician on the list.',
      '**Job history search.** "What did we charge for the same board at the Kelburn place" answered in seconds from your own records.',
      '**Materials lists** generated from a job description, for pricing or ordering.',
      '**Chasing the quotes you sent.** Most electricians never follow up a quote. A follow-up four days later is close to free and converts a meaningful share of silence.',
      '**Finding commercial work.** Property managers, builders and facilities companies are reachable, and almost nobody in the trade approaches them systematically.',
    ]},
    { h: 'What is not worth it' },
    'Anything customer-facing that pretends to be you. A chatbot that answers technical questions about their wiring is a liability, not an efficiency — customers want an electrician\'s judgement, and a confident wrong answer about electrical safety is worse than no answer. Keep AI in the paperwork, the admin and the chasing.',
    { note: 'The realistic prize is one to two hours an evening returned. Not a transformed business — an evening back, and quotes going out while the job is still fresh in the customer\'s mind.' },
  ],
  faq: [
    { q: 'Can AI write my quotes?', a: 'It can produce a formatted, priced draft from a spoken description of the job — line items, labour, callout, tax — that you check and send. It does not know your margins or your suppliers unless you tell it, and it should never send a quote without you seeing it. The saving is in not typing at nine at night, which is most of the cost.' },
    { q: 'Will it handle my compliance certificates?', a: 'It can fill routine fields from job data you already have, which removes re-keying. It cannot certify work and must not be trusted to decide what is compliant — that is your registration and your liability. Treat it as a form-filler that you verify and sign.' },
    { q: 'Is this worth it for a one-person operation?', a: 'Often more so than for a larger firm, because a sole operator has no office person absorbing the admin. The evening hours you get back are your own. Start with quoting alone rather than trying to automate everything at once.' },
    { q: 'How do I find commercial clients?', a: 'Property managers, building companies, facilities managers and real estate firms all need reliable electrical contractors and are reachable by email. Very few electricians approach them systematically, which is precisely why it works — see [B2B lead generation for small businesses](/b2b-lead-generation-small-business/).' },
  ],
  related: [
    ['/ai-for-plumbers/', 'AI for plumbers'],
    ['/ai-for-builders/', 'AI for builders'],
    ['/b2b-lead-generation-small-business/', 'Finding commercial clients'],
  ],
},

{
  slug: 'ai-for-plumbers',
  title: 'AI for Plumbers — Practical Uses in a Callout-Driven Business',
  description: 'How plumbing businesses use AI where it actually helps: triaging emergency calls, quoting from the van, chasing unpaid invoices and keeping maintenance customers — without pretending it does the plumbing.',
  keywords: 'AI for plumbers, plumbing business automation, plumber quoting software, trade admin automation',
  eyebrow: 'Trades',
  short: 'AI for plumbers',
  h1: 'AI for plumbers. <span style="color:var(--grey-4);font-weight:300;">Built around callouts, not projects.</span>',
  cta: 'service',
  body: [
    { lead: 'Plumbing runs on a different rhythm from most trades. Work arrives unplanned and often urgent, the phone rings while you are under a sink, and the difference between a good week and a bad one is frequently how well the interruptions were handled rather than how well the work was done.' },
    { h: 'Triage is the highest-value thing here' },
    'Not every call is an emergency, and not every emergency is yours. A burst pipe at 2am and a slow-draining shower need completely different responses, but both arrive on the same phone.',
    'Automated triage — capturing the enquiry, asking the two or three questions that establish urgency, and either scheduling it or flagging it for immediate attention — is worth more in plumbing than in trades where work is planned weeks ahead. **What it protects is not time so much as attention**: you stop breaking off a job to discover the call was a quote request.',
    { h: 'Quoting from the van' },
    'Same pattern as other trades, with a plumbing-specific wrinkle: much of the work is diagnosed on site, and the quote depends on what was found. Dictating "replace hot water cylinder, supply 180 litre, two isolation valves, half day two people, plus callout" and getting back a formatted quote before you have left the driveway means the customer decides while you are still standing there.',
    { h: 'The invoice problem' },
    'Plumbing has a debtor problem that project trades do not, because the work is done before anyone discusses money and emergency customers are less price-sensitive at 2am than they are on Friday. Automated, polite, escalating payment reminders recover money that would otherwise be written off — and they do it without the awkward phone call most people avoid making.',
    { h: 'Maintenance contracts are the underused asset' },
    { list: [
      '**Reminders for annual servicing** — cylinders, backflow prevention, commercial grease traps.',
      '**Compliance schedules** for commercial clients, who are legally obliged and frequently disorganised.',
      '**Reactivating past customers.** A message to everyone you served two years ago costs nothing and reliably produces work.',
      '**Approaching property managers.** Rental portfolios generate constant plumbing work and value reliability over price — the best commercial relationship available to a plumber, and rarely pursued systematically.',
    ]},
    { note: 'Nothing here diagnoses a leak or decides what compliant work looks like. The value sits entirely in the layer around the job: the enquiry, the quote, the invoice and the follow-up.' },
  ],
  faq: [
    { q: 'Can AI answer my phone?', a: 'It can capture enquiries, ask qualifying questions and schedule non-urgent work, then route genuine emergencies to you immediately. Whether you want it on your main line is a judgement call — some customers accept it, others want a human, and in emergency plumbing the second group is larger. Many businesses use it for overflow and after-hours rather than as the front line.' },
    { q: 'Does it help with unpaid invoices?', a: 'Yes, and this is often the fastest payback in plumbing specifically. Automated escalating reminders recover money that otherwise gets written off, and they remove the reluctance that stops most sole operators from chasing at all.' },
    { q: 'What about emergency callouts at night?', a: 'Automated triage that captures details, establishes urgency and wakes you only for genuine emergencies is a real quality-of-life improvement. The rule that matters: err toward waking you. A missed real emergency costs far more than an unnecessary alert.' },
    { q: 'Is it worth it if I only do residential work?', a: 'The quoting and invoice-chasing pieces are, immediately. The commercial and maintenance-contract pieces are where residential plumbers often find a more profitable second stream — property managers in particular, who need someone reliable on call and are reachable directly.' },
  ],
  related: [
    ['/ai-for-electricians/', 'AI for electricians'],
    ['/ai-for-builders/', 'AI for builders'],
    ['/business-process-automation/', 'Business process automation'],
  ],
},

{
  slug: 'ai-for-builders',
  title: 'AI for Builders and Construction — Where It Helps on Long Projects',
  description: 'AI for building companies: estimating support, variation tracking, subcontractor coordination, client updates and compliance documentation across projects that run for months.',
  keywords: 'AI for builders, construction automation, building company software, construction admin AI',
  eyebrow: 'Trades',
  short: 'AI for builders',
  h1: 'AI for builders. <span style="color:var(--grey-4);font-weight:300;">The problem is the paperwork trail.</span>',
  cta: 'service',
  body: [
    { lead: 'Building differs from callout trades in one decisive way: projects run for months, involve many parties, and generate a documentation trail that becomes the evidence when something is disputed. The admin burden is not a series of small tasks — it is one long one, and it is where margin quietly disappears.' },
    { h: 'Variations are where money is lost' },
    'Most builders can point to a job where the variations were agreed verbally, done, and then argued about at invoicing. The work was real; the record was not.',
    'Capturing variations as they happen — a voice note on site, converted into a dated written record with scope and cost, sent to the client for confirmation — is unglamorous and directly protects margin. **This is the single highest-value automation available to a building company**, and it is worth more than anything on the estimating side.',
    { h: 'Estimating support' },
    'Not automated estimating — quantities and pricing need someone who knows the job. But extracting a materials schedule from plans and specifications, and checking a new estimate against what similar past jobs actually cost, removes hours of reading and gives you a sanity check that catches the estimate that drifted.',
    { h: 'Coordination and client updates' },
    { list: [
      '**Subcontractor scheduling.** Confirmations, reminders, and rescheduling messages when a trade runs late — which cascades into every trade behind them.',
      '**Weekly client updates.** Generated from site notes and photos. Clients who receive a regular update ring far less often, and the calls they do make are better ones.',
      '**Compliance documentation.** Building consent conditions, inspection records, producer statements — assembled from what you already recorded rather than re-typed.',
      '**Health and safety records.** Site inductions, toolbox talks, hazard registers. Legally required, universally resented, entirely mechanical.',
      '**Defect lists** captured on site and turned into scheduled work with responsibilities attached.',
    ]},
    { h: 'Finding the next project' },
    'Building companies typically rely on referrals and repeat clients, which works until it does not — usually at exactly the wrong point in the cycle. Architects, developers, property managers and commercial clients are all reachable directly, and a builder with a genuine specialisation who approaches them systematically is unusual enough to be noticed.',
    { note: 'None of this touches the build. It touches the record of the build, which is where disputes are won or lost and where a surprising share of a builder\'s week actually goes.' },
  ],
  faq: [
    { q: 'Can AI do my estimating?', a: 'It can extract materials schedules from plans and compare a draft estimate against what your past jobs actually cost, which catches the ones that have drifted. It cannot judge site conditions, buildability or risk — those are why estimators exist. Treat it as a fast first pass and a cross-check, not an estimator.' },
    { q: 'What is the fastest payback for a building company?', a: 'Variation capture. Recording verbally agreed changes as dated written records, confirmed by the client, protects margin directly and prevents the disputes that cost far more than any admin time. Most builders lose more money to undocumented variations than to any inefficiency automation would fix.' },
    { q: 'Will it help with health and safety compliance?', a: 'It can generate and maintain the documentation — inductions, toolbox talk records, hazard registers — from what happens on site. It does not make your site safe, and it does not replace your obligations. It removes the excuse that the paperwork is too tedious to keep current, which is when it actually becomes evidence.' },
    { q: 'How do builders find commercial work?', a: 'Architects, developers, property managers and facilities companies commission continuously and are reachable by email. The builders who succeed at this have a specific angle — a build type, a compliance capability, a regional advantage — rather than a general offer. See [building an ideal customer profile](/building-an-ideal-customer-profile/).' },
  ],
  related: [
    ['/ai-for-electricians/', 'AI for electricians'],
    ['/ai-for-real-estate/', 'AI for real estate'],
    ['/business-process-automation/', 'Business process automation'],
  ],
},

{
  slug: 'ai-for-real-estate',
  title: 'AI for Real Estate Agencies — Beyond Writing Listing Descriptions',
  description: 'Practical AI for real estate: vendor reporting, buyer matching, appraisal preparation, database reactivation and the compliance trail — with a clear line on where automation damages trust.',
  keywords: 'AI for real estate, real estate automation, property agency AI, listing automation, real estate CRM AI',
  eyebrow: 'Property',
  short: 'AI for real estate',
  h1: 'AI for real estate. <span style="color:var(--grey-4);font-weight:300;">The listing text is the least of it.</span>',
  cta: 'service',
  body: [
    { lead: 'Every real estate AI pitch starts with generating listing descriptions, which is the least valuable thing on the list and the easiest to spot. The work that actually consumes an agent\'s week is vendor communication, buyer follow-up and a database that decays quietly in the background.' },
    { h: 'Vendor reporting' },
    'Vendors want to know what is happening, and agents are worst at communicating during the periods when there is least to report — which is exactly when the anxiety peaks and the relationship is most at risk.',
    'Generating a weekly report from real data — viewings, enquiry numbers, feedback themes, comparable activity — takes minutes instead of an hour per listing. The vendor who receives a regular report chases less and renews the agency agreement more often. **Consistency here is worth more than eloquence anywhere else.**',
    { h: 'The database is the asset nobody works' },
    'Most agencies hold thousands of past contacts: buyers who missed out, vendors from years ago, appraisals that never listed. It sits untouched because working it manually is unthinkable.',
    { list: [
      '**Matching new listings to past buyers** on their stated criteria, before the listing goes public.',
      '**Reactivating old appraisals.** Someone who had an appraisal three years ago and did not sell is a live prospect now.',
      '**Anniversary contact** with past vendors — the single highest-conversion outreach in the industry and the one most consistently neglected.',
      '**Detecting intent signals.** A buyer who returns to your site repeatedly is telling you something.',
    ]},
    { h: 'Appraisal preparation' },
    'Assembling comparable sales, market data and property history into a presentation is hours of assembly per appraisal. Automating the assembly leaves the agent to do the part that wins the listing — the judgement about price and the conversation in the room.',
    { h: 'Where automation damages trust' },
    'Real estate is a relationship business operating under conduct rules, and some automation actively harms you:',
    { list: [
      '**Automated responses to buyer enquiries** that read as automated. Buyers making the largest purchase of their lives notice, and it costs you the relationship immediately.',
      '**Generated market commentary presented as personal insight.** If a vendor discovers your market view was assembled rather than considered, everything else you told them is retrospectively suspect.',
      '**Anything touching disclosure obligations.** Material facts about a property are a legal duty. A generated description that misstates one is your problem, not the software\'s.',
    ]},
    { note: 'The line worth holding: automate the assembly and the remembering, never the judgement or the relationship. An agent whose reports arrive reliably and whose database actually works is more valuable than one with better adjectives.' },
  ],
  faq: [
    { q: 'Can AI write property listings?', a: 'It can draft them, and the drafts read like drafts unless you supply real detail and edit properly. More importantly, listing text is subject to fair-trading and disclosure rules — a generated description that misstates a material fact is a legal exposure. Draft with it if you like, but read every word before it publishes.' },
    { q: 'What is the highest-value use for an agency?', a: 'Working the existing database. Most agencies hold thousands of past contacts they never contact — old appraisals, buyers who missed out, vendors from years ago. Matching them to new listings and reaching out systematically produces business from people who already know you, which converts far better than any cold approach.' },
    { q: 'Will automated vendor reports feel impersonal?', a: 'Not if they contain real data and you add a genuine comment. A weekly report with actual viewing numbers, enquiry counts and feedback themes plus two sentences of your own reads as attentive. The version that feels impersonal is the one with no data and generic reassurance — which is what vendors currently receive when they receive anything.' },
    { q: 'Does this work for a single agent?', a: 'Particularly well, because a solo agent has no support staff absorbing the reporting and follow-up. The database work in particular scales in a way one person\'s memory cannot.' },
  ],
  related: [
    ['/ai-for-builders/', 'AI for builders'],
    ['/business-process-automation/', 'Business process automation'],
    ['/b2b-lead-generation-small-business/', 'B2B lead generation'],
  ],
},

{
  slug: 'ai-for-recruitment-agencies',
  title: 'AI for Recruitment Agencies — Where It Helps and Where It Is Risky',
  description: 'AI in recruitment: candidate matching, screening support, business development and database reactivation — plus a direct look at bias, transparency obligations and why candidate data belongs in-house.',
  keywords: 'AI for recruitment, recruitment agency automation, candidate matching AI, recruiting AI bias',
  eyebrow: 'Recruitment',
  short: 'AI for recruitment',
  h1: 'AI in recruitment. <span style="color:var(--grey-4);font-weight:300;">Useful, and genuinely risky.</span>',
  cta: 'private',
  body: [
    { lead: 'Recruitment is unusually well suited to AI — it is matching, searching and communicating at volume. It is also one of the few applications where getting it wrong has legal and human consequences beyond a bad quarter, because the decisions affect whether people get work.' },
    { h: 'Where it helps clearly' },
    { list: [
      '**Searching your own database.** Most agencies have thousands of candidates they cannot effectively search. Semantic search over CVs — finding people by capability rather than keyword — surfaces candidates who were always there.',
      '**Reactivating the database.** Candidates placed two years ago are moving again. Nobody has time to work through a list that size manually.',
      '**Job description drafting** from a client conversation, for the client to approve.',
      '**Candidate communication at volume.** The industry\'s worst reputational problem is silence after application. Automated, honest status updates fix a real grievance cheaply.',
      '**Business development.** New client acquisition is the constraint in most agencies, and it is exactly the kind of research-and-write work that automation suits.',
      '**Formatting and summarising CVs** into a consistent client-facing format.',
    ]},
    { h: 'Where it is risky' },
    'Screening and ranking candidates is where recruitment AI attracts regulatory attention, and the concerns are well founded. Models trained on historical hiring data can reproduce historical patterns, including discriminatory ones, and they do so in a way that looks objective — which makes it harder to challenge, not easier.',
    { list: [
      '**Automated rejection** without human review is the highest-risk use available. Several jurisdictions have introduced or are introducing rules requiring transparency or auditing where AI materially affects hiring decisions.',
      '**Proxy discrimination.** A model can learn to use a signal that correlates with a protected characteristic — a postcode, a school, a career gap — without ever being given the characteristic itself.',
      '**Opacity.** If you cannot explain why a candidate was ranked low, you cannot defend it to them, to your client, or to a regulator.',
    ]},
    { note: 'A defensible position: use AI to **surface and summarise**, never to **reject**. Widening the pool a human then assesses is a use that improves outcomes for candidates. Narrowing it automatically is the use that generates the harm and the liability.' },
    { h: 'Why candidate data belongs in-house' },
    'A recruitment database is CVs, salary histories, references and personal circumstances — a concentration of personal data with strong protections in every jurisdiction. It is also your entire commercial asset.',
    'Running matching and search on your own infrastructure means candidate data never reaches a third party. For an agency whose database *is* the business, that is both a privacy position and a competitive one. [How private AI deployment works.](/run-ai-locally-business/)',
  ],
  faq: [
    { q: 'Can AI screen candidates for me?', a: 'It can summarise applications and surface people matching stated criteria, which saves substantial time. Using it to automatically reject is where legal risk concentrates — several jurisdictions now impose transparency or audit requirements where AI materially affects hiring decisions, and the discrimination exposure is real. Surface and summarise; let a person decide.' },
    { q: 'Is AI in recruitment discriminatory?', a: 'It can be, and often in ways that are hard to detect. A model can learn proxies for protected characteristics — postcodes, schools, career gaps — without being given the characteristic. That is why human review of anything affecting an outcome, and the ability to explain a decision, matter more in recruitment than in almost any other application.' },
    { q: 'What is the safest high-value use?', a: 'Searching and reactivating your own database. It has no adverse-decision risk, it works an asset you already paid for, and it surfaces candidates for opportunities rather than filtering them out — the direction of effect is toward more people being considered, not fewer.' },
    { q: 'Should candidate data stay on our own systems?', a: 'There is a strong case for it. A recruitment database is a dense concentration of personal data and simultaneously your core commercial asset. Running matching locally means it never reaches a third party, which addresses both the privacy obligation and the commercial exposure at once.' },
  ],
  related: [
    ['/run-ai-locally-business/', 'Running AI locally'],
    ['/ai-data-privacy-business/', 'AI and your business data'],
    ['/b2b-lead-generation-small-business/', 'B2B lead generation'],
  ],
},

{
  slug: 'ai-for-marine-businesses',
  title: 'AI for Marine Businesses — Boatyards, Brokers and Marine Trades',
  description: 'AI for the marine industry: seasonal booking pressure, quoting survey and refit work, maintenance schedules that generate repeat revenue, and reaching commercial marine clients.',
  keywords: 'AI for marine business, boatyard software, marine trades automation, boat broker AI, marine services',
  eyebrow: 'Marine',
  short: 'AI for marine',
  h1: 'AI for marine businesses. <span style="color:var(--grey-4);font-weight:300;">Built around the season.</span>',
  cta: 'service',
  body: [
    { lead: 'Marine businesses run on a seasonal cycle that concentrates demand into a few months and leaves the rest quiet. That shape — not the technology — should determine what is worth automating, because the constraint in peak season and the constraint in the off-season are opposite problems.' },
    { h: 'Peak season: the constraint is capacity' },
    'In season, the yard is full and the phone does not stop. The problem is not finding work, it is handling enquiries without losing the ones worth having.',
    { list: [
      '**Enquiry triage.** Distinguishing a hardstand booking from a full refit enquiry from a warranty question, and routing each appropriately.',
      '**Booking coordination** for haul-outs, hardstand and berth allocation, where the constraint is physical space and the scheduling is genuinely complex.',
      '**Quote turnaround** for antifoul, survey work and repairs — dictated at the boat, formatted and sent before you have walked back to the office.',
      '**Waitlist management,** so a cancellation gets filled instead of becoming a gap.',
    ]},
    { h: 'Off-season: the constraint is work' },
    'The same business four months later has capacity and no queue. This is when the systems built in season earn their keep.',
    { list: [
      '**Maintenance reminders** driven by service history. Antifoul intervals, engine servicing, rigging inspection, survey renewals. Boat owners forget; the yard that reminds them books the work.',
      '**Reactivating past customers.** Everyone who hauled out two seasons ago and has not returned.',
      '**Approaching commercial operators.** Charter fleets, fishing operations, tourism vessels and marine transport have year-round maintenance obligations and are far less seasonal than private owners. This is the most valuable client category available to a marine business and the least systematically pursued.',
      '**Quoting refit work** — the large winter jobs that make the off-season profitable.',
    ]},
    { h: 'Survey and compliance documentation' },
    'Marine work generates substantial documentation: survey reports, compliance certification, insurance documentation, maintenance records that follow a vessel and affect its value. Assembling reports from inspection notes and photographs, and keeping per-vessel service histories current, is mechanical work that currently happens in evenings.',
    { note: 'The single most valuable thing for most marine businesses is a per-vessel service history that automatically generates the next reminder. It converts a one-off haul-out into a recurring customer, and it is the difference between a yard that waits for the phone and one that fills its own calendar.' },
  ],
  faq: [
    { q: 'What is the highest-value automation for a boatyard?', a: 'Maintenance reminders driven by service history. Antifoul intervals, engine servicing and survey renewals are predictable, owners forget them, and the yard that sends the reminder gets the booking. It converts occasional customers into recurring ones and directly fills the off-season.' },
    { q: 'How do marine businesses find commercial clients?', a: 'Charter operators, fishing fleets, tourism vessels and marine transport companies all have year-round maintenance requirements and statutory obligations. They are reachable directly and are far less seasonal than private owners. Very few marine businesses approach them systematically, which is exactly why it works.' },
    { q: 'Can AI help with survey reports?', a: 'It can assemble a structured report from inspection notes and photographs, which removes hours of writing up. The findings and the judgement remain the surveyor\'s — and where survey work carries certification obligations, the qualified person signs and is responsible for what is in it.' },
    { q: 'Is this worth it for a small operation?', a: 'The reminder system alone usually is, because it directly generates bookings rather than merely saving time. Start there — it pays for itself in filled slots — and add quoting once you see the pattern.' },
  ],
  related: [
    ['/ai-for-hospitality/', 'AI for hospitality'],
    ['/b2b-lead-generation-small-business/', 'B2B lead generation'],
    ['/business-process-automation/', 'Business process automation'],
  ],
},

{
  slug: 'ai-for-hospitality',
  title: 'AI for Hospitality — Restaurants, Cellar Doors and Small Venues',
  description: 'AI for hospitality operators: booking friction, group and event enquiries, rosters, supplier admin and reviews — and why the automation guests notice is usually the wrong automation.',
  keywords: 'AI for hospitality, restaurant automation, cellar door bookings, venue management AI, hospitality admin',
  eyebrow: 'Hospitality',
  short: 'AI for hospitality',
  h1: 'AI for hospitality. <span style="color:var(--grey-4);font-weight:300;">Fix the booking before anything else.</span>',
  cta: 'service',
  body: [
    { lead: 'Hospitality has thin margins and an owner who is usually also working the floor. That combination means automation has to earn its place immediately, and it means the highest-value fix is often not automation at all — it is the booking path that quietly loses people before they ever arrive.' },
    { h: 'Start with the booking, because it is usually broken' },
    'Before any AI, check what actually happens when someone tries to book. Broken widgets, forms that fail on a phone, enquiry emails nobody monitors on a Tuesday — these are extremely common in small venues and cellar doors, and each one loses a booking silently. Nobody complains about a booking form that does not work; they just go elsewhere.',
    '**A venue losing bookings to a broken form does not have an AI problem.** Fix that first, and measure the difference before adding anything.',
    { h: 'Group and event enquiries' },
    'Once booking works, the highest-value automation in hospitality is handling group and function enquiries. These are the most valuable bookings and the ones most often lost to slow replies — a wedding party or corporate function enquiry that waits two days has usually already been answered by someone else.',
    { list: [
      '**Immediate acknowledgement** with real availability, not a promise to get back to them.',
      '**Capturing the details that matter** — numbers, date, dietary requirements, budget — before a person gets involved.',
      '**Following up on quotes sent.** Most venues never chase a function quote.',
    ]},
    { h: 'The back of house' },
    { list: [
      '**Rostering** against forecast demand, bookings and staff availability — hours of weekly work in most venues.',
      '**Supplier ordering** from stock levels and upcoming bookings.',
      '**Reconciling supplier invoices** against deliveries, where errors are common and rarely caught.',
      '**Compliance records** — food safety logs, temperature records, training documentation.',
      '**Review responses** drafted for the owner to edit. Speed and specificity matter here, and a generic reply is visibly generic to everyone reading.',
    ]},
    { h: 'What guests should never notice' },
    'Hospitality sells an experience, and automation that guests can feel undermines the thing they are paying for. A chatbot on the front page of a fine-dining restaurant is a category error. An automated response to a complaint is worse than a slow human one.',
    'Keep it behind the scenes: rosters, ordering, invoices, compliance, internal coordination. The guest-facing exception is booking, where speed genuinely helps them — and even there, a function enquiry should reach a person quickly.',
    { note: 'For cellar doors and destination venues specifically, the booking path is frequently the entire problem. Visitors decide in the morning where to go that afternoon; a venue that cannot be booked in two taps on a phone has lost them regardless of how good the wine is.' },
  ],
  faq: [
    { q: 'Should a restaurant use an AI chatbot?', a: 'Rarely on the front line. Hospitality sells an experience, and a bot answering guests undercuts it. Where automation helps is speed on bookings and function enquiries, and everything behind the scenes — rosters, ordering, invoices, compliance. If a guest can tell, reconsider.' },
    { q: 'What is the fastest win for a small venue?', a: 'Checking that your booking path actually works on a phone, then automating group and function enquiry responses. Function bookings are the most valuable and the most frequently lost to slow replies. Neither requires much technology; both directly affect revenue.' },
    { q: 'Can AI handle rostering?', a: 'It can generate a draft roster from forecast demand, bookings and availability, which removes hours of weekly work. A manager still adjusts it, because the model does not know that one person is training another or that someone needs an early finish. A good draft to edit beats a blank grid.' },
    { q: 'What about responding to online reviews?', a: 'Draft with it, always edit, and never automate sending. A generic reply is obvious to every future customer reading it, and a mishandled response to a genuine complaint does more damage than the complaint. Speed helps; automation without review does not.' },
  ],
  related: [
    ['/ai-for-marine-businesses/', 'AI for marine businesses'],
    ['/business-process-automation/', 'Business process automation'],
    ['/ai-automation-small-business/', 'AI automation for small business'],
  ],
},

{
  slug: 'ai-for-accountants',
  title: 'AI for Accounting Practices — Where the Billable Hours Go',
  description: 'AI in accounting practices: document processing, transaction coding, client queries and advisory capacity — plus what must stay under professional review and why peak season changes the maths.',
  keywords: 'AI for accountants, accounting practice automation, bookkeeping AI, tax practice efficiency',
  eyebrow: 'Professional services',
  short: 'AI for accountants',
  h1: 'AI in an accounting practice. <span style="color:var(--grey-4);font-weight:300;">Where the hours actually go.</span>',
  cta: 'service',
  body: [
    { lead: 'Accounting practices are dense with work that is repetitive, document-heavy and rule-based — the exact profile AI handles well. The opportunity is not doing accounting faster; it is clearing the mechanical layer so qualified people spend their time on the work clients actually value.' },
    { h: 'Document processing is the obvious start' },
    'Invoices, receipts, bank statements, contracts. Every practice processes enormous volumes, most of it still involving a person reading a document and typing what it says into a system. Extraction handles this at a quality that needs checking rather than redoing — and the checking is a fraction of the time.',
    { h: 'Transaction coding' },
    'Classifying transactions into accounts is pattern recognition against how you have coded similar items before. A model learns your conventions per client and drafts the coding; a person reviews exceptions rather than every line. The efficiency is not marginal.',
    { h: 'Client communication' },
    { list: [
      '**Chasing missing records.** The perennial time sink, entirely mechanical, and the thing nobody enjoys doing.',
      '**Answering routine queries** drafted from the client\'s own file, for review before sending.',
      '**Deadline reminders** driven by each client\'s actual obligations.',
      '**Onboarding new clients** — collecting information, confirming what is needed.',
    ]},
    { h: 'The advisory question' },
    'Most practices say they want to move from compliance work to advisory work, and most do not, because compliance consumes the capacity. The compliance work is precisely what automates well.',
    'That is the actual business case: not reducing headcount, but converting hours currently spent on processing into hours available for advice — which is both better paid and less vulnerable to being automated by someone else.',
    { h: 'What stays under review' },
    'Everything affecting a return or a set of accounts. These models produce confident output that is sometimes wrong, and in accounting a plausible wrong figure is worse than an obvious one because it survives a glance. Use them for the first pass, and keep professional judgement where it belongs.',
    { note: 'On where the data lives: a practice holds concentrated financial information about many businesses, which is a more consequential exposure than most single businesses face. That argues for keeping processing in-house — [private AI for accountants](/private-ai-for-accountants/) covers the setup.' },
  ],
  faq: [
    { q: 'Will AI replace accountants?', a: 'It replaces mechanical processing — reading documents, coding transactions, chasing records. It does not replace judgement, advice, or professional responsibility for what is filed. The practices that adopt it are generally not shrinking; they are moving capacity from compliance toward advisory work, which is better paid.' },
    { q: 'Is it accurate enough for financial documents?', a: 'For extracting figures and classifying transactions, yes — as a first pass a person reviews. It should not be trusted unverified on anything affecting a return. The gain comes from reviewing extracted data rather than keying it, which is still a very large saving.' },
    { q: 'What about client confidentiality?', a: 'Your professional body\'s requirements govern this and are usually stricter than any provider\'s terms. Many practices are comfortable with business-tier tools under appropriate agreements; others conclude that concentrated client financial data should not leave the practice at all. Running processing in-house settles the question rather than managing it.' },
    { q: 'When should a practice start?', a: 'Outside peak season, so you can test properly rather than under pressure. Start with document extraction on one client group, verify the output carefully, and expand from what you learn. Introducing new processing during your busiest month is how a good idea becomes a bad memory.' },
  ],
  related: [
    ['/private-ai-for-accountants/', 'Private AI for accountants'],
    ['/business-process-automation/', 'Business process automation'],
    ['/ai-data-privacy-business/', 'AI and your business data'],
  ],
},

{
  slug: 'ai-for-ecommerce',
  title: 'AI for E-commerce — Product Content, Support and the Long Tail',
  description: 'AI for online retailers: product content at catalogue scale, support deflection done honestly, merchandising and the operational work behind the storefront.',
  keywords: 'AI for ecommerce, product description AI, ecommerce automation, online store AI, catalogue automation',
  eyebrow: 'Retail',
  short: 'AI for e-commerce',
  h1: 'AI for e-commerce. <span style="color:var(--grey-4);font-weight:300;">The catalogue is the opportunity.</span>',
  cta: 'service',
  body: [
    { lead: 'E-commerce has a structural problem that suits automation unusually well: the catalogue is always larger than the team. Products go live with thin descriptions, missing attributes and no images beyond the supplier\'s, because writing properly for two thousand items was never realistic.' },
    { h: 'Product content at scale' },
    'This is where the return is clearest. Generating descriptions, attributes and specifications from supplier data and images turns a catalogue that is 80% thin into one that is complete — which matters for search visibility, for conversion, and for the long tail of products nobody had time to write.',
    { list: [
      '**Descriptions from supplier data,** in your own voice rather than the manufacturer\'s copy every competitor is also using.',
      '**Structured attributes** extracted consistently, which is what makes filtering and search work properly.',
      '**Category and tag assignment** across thousands of items.',
      '**Localised versions** where you sell across markets.',
      '**Image tagging** for search and merchandising.',
    ]},
    { note: 'A caution that matters commercially: identical manufacturer copy across many retailers is a known weakness in search, and thin generated content is not obviously better. Content should add something real — fit, use, comparison, what it suits — or it is volume without value. Generate to a brief, not to a word count.' },
    { h: 'Customer support' },
    'Support deflection is the other obvious application, and the one most often done badly. Order status, delivery timeframes, returns policy and stock questions are genuinely repetitive and can be handled well.',
    'What ruins it is a bot that cannot escalate. A customer with a real problem trapped in a loop is worse than a slow email reply, and it is the single most common complaint about e-commerce automation. **Build the escape hatch first**, make it obvious, and measure how often people use it — high escape rates are telling you something about the bot, not about the customers.',
    { h: 'Behind the storefront' },
    { list: [
      '**Demand forecasting** for purchasing, particularly on seasonal lines.',
      '**Supplier communication** — purchase orders, chasing, discrepancy resolution.',
      '**Review analysis** at volume, surfacing product problems before they show up in returns data.',
      '**Returns processing** and pattern detection — repeated returns on one product usually indicate a description or sizing problem you can fix.',
      '**Abandoned cart recovery** with messages referencing the actual product rather than a template.',
    ]},
  ],
  faq: [
    { q: 'Can AI write product descriptions that rank in search?', a: 'It can produce descriptions at catalogue scale, which is valuable mainly because the alternative is thin or duplicated manufacturer copy. Whether they rank depends on whether they add something real — fit, use, comparison, suitability. Generating volume for its own sake is the version search engines have become good at discounting.' },
    { q: 'Should I use an AI chatbot for customer support?', a: 'For order status, delivery, returns and stock questions, yes — those are repetitive and well handled. The requirement is an obvious, easy escalation to a person. A customer with a real problem stuck in a loop costs you more than the support hours you saved, and it is the most common failure in e-commerce automation.' },
    { q: 'What is the fastest win for a small online store?', a: 'Completing the catalogue. Most small stores have hundreds of products with thin descriptions and missing attributes, which suppresses both search visibility and conversion across the long tail. Fixing it manually was never going to happen; fixing it in a week is now realistic.' },
    { q: 'Can AI help with product photography?', a: 'Image generation and editing can produce lifestyle context and format variants from existing product shots at a fraction of traditional cost. The constraint is honesty: the product shown must be the product sold. Generated imagery that misrepresents an item is a fair-trading problem, not a creative decision.' },
  ],
  related: [
    ['/business-process-automation/', 'Business process automation'],
    ['/ai-automation-small-business/', 'AI automation for small business'],
  ],
},

{
  slug: 'ai-for-nonprofits',
  title: 'AI for Non-Profits and Community Organisations — Doing More With the Same People',
  description: 'AI for non-profits: grant applications and reporting, volunteer coordination, donor communication and the administrative load that consumes small teams — with a clear view of what to be careful with.',
  keywords: 'AI for nonprofits, charity automation, grant writing AI, community organisation admin, NGO efficiency',
  eyebrow: 'Community',
  short: 'AI for non-profits',
  h1: 'AI for non-profits. <span style="color:var(--grey-4);font-weight:300;">The reporting burden is the target.</span>',
  cta: 'service',
  body: [
    { lead: 'Non-profits run on small teams doing several jobs each, and a disproportionate share of their capacity goes to funding administration rather than to the work itself. That is the load worth attacking — not because the reporting is unimportant, but because it is the least mission-critical use of the few hours available.' },
    { h: 'Grant applications and reporting' },
    'Most organisations apply to multiple funders, each with different forms asking overlapping questions in incompatible formats. And each successful grant brings its own reporting obligations on its own schedule.',
    { list: [
      '**Reusing your own material.** Your programme descriptions, outcomes and organisational history already exist in past applications. Assembling them into a new funder\'s format is mechanical.',
      '**Drafting reports** from activity records and outcome data you already collect.',
      '**Tracking deadlines and obligations** across multiple funders.',
      '**Plain-language versions** of the same information for newsletters, boards and community updates.',
    ]},
    'The honest framing: this does not make a weak application strong. It removes the assembly work so the person who understands the programme spends their time on the parts that persuade.',
    { h: 'Volunteer and community coordination' },
    { list: [
      '**Rostering** against availability and skills.',
      '**Onboarding** — induction material, role descriptions, training records.',
      '**Keeping volunteers informed**, which is the main determinant of whether they stay.',
      '**Records for compliance** where you work with vulnerable people.',
    ]},
    { h: 'Donor and supporter communication' },
    'Small organisations often have supporter lists they cannot work — people who gave once, attended once, volunteered once. Personalised acknowledgement and updates at a scale a two-person team cannot reach manually is a genuine capacity increase, not a marketing trick.',
    { h: 'Where to be careful' },
    { list: [
      '**Community voice.** If your organisation represents a community, generated communication that does not sound like that community damages the trust you exist on. Draft with it, and have the right person edit.',
      '**Cultural material.** Where language, heritage or cultural knowledge is involved, general-purpose models are unreliable and confidently so. Accuracy here is a matter of respect, not just quality, and it needs people with the standing to verify it.',
      '**Beneficiary data.** Information about vulnerable people carries the strongest obligations. This is a case for keeping processing in-house — see [AI and your business data](/ai-data-privacy-business/).',
      '**Funder honesty.** Reports must reflect what actually happened. A well-drafted report describing outcomes you did not achieve is a serious problem.',
    ]},
    { note: 'For organisations working in te reo Māori, Pacific languages or other community languages, general models handle them considerably worse than English and will produce fluent errors without signalling uncertainty. Verification by fluent speakers is not optional.' },
  ],
  faq: [
    { q: 'Can AI write grant applications?', a: 'It can assemble a strong draft from your own existing material — past applications, programme descriptions, outcome data — into a new funder\'s format. It cannot supply the insight into your programme that makes an application compelling, and a funder reading generic text notices. Use it for assembly; keep the argument yours.' },
    { q: 'Is it appropriate for a charity to use AI?', a: 'It is a capacity question. If administrative load is consuming hours that could go to the mission, reducing it serves the mission. The care needed is around voice, cultural material and beneficiary data — not around the principle.' },
    { q: 'What about data on the people we serve?', a: 'Information about beneficiaries, particularly vulnerable people, carries the strongest protections and the strongest ethical obligations. Keep that processing in-house rather than sending it to third-party services, and treat it with the same care as health information.' },
    { q: 'We have almost no budget. Is this realistic?', a: 'Open-source models running on hardware you already own cost nothing per use, which suits organisations with more time pressure than money. Start with the single heaviest administrative burden — usually funder reporting — rather than attempting a broad rollout.' },
  ],
  related: [
    ['/ai-data-privacy-business/', 'AI and your business data'],
    ['/run-ai-locally-business/', 'Running AI locally'],
    ['/business-process-automation/', 'Business process automation'],
  ],
},

];
