/* Cold email law by jurisdiction.
 *
 * These pages describe legislation accurately and carry an explicit
 * disclaimer. They are not legal advice and must never read as if
 * they were — the licence already places compliance on the buyer,
 * and overclaiming here would undercut that. */

const DISCLAIMER = { note: '**This is not legal advice.** It is a plain-language summary of publicly available legislation, written to help you ask better questions. Rules change, enforcement practice varies, and your circumstances may differ. If cold outreach is material to your business, have a lawyer in the relevant jurisdiction review what you are doing.' };

export default [

{
  slug: 'cold-email-law-new-zealand',
  title: 'Is Cold Email Legal in New Zealand? The Unsolicited Electronic Messages Act Explained',
  description: 'What New Zealand law requires of cold email under the Unsolicited Electronic Messages Act 2007: consent types, identification, unsubscribe obligations, penalties and how B2B outreach fits.',
  keywords: 'cold email legal New Zealand, Unsolicited Electronic Messages Act 2007, NZ spam law, B2B email law NZ',
  eyebrow: 'New Zealand',
  short: 'Cold email law · NZ',
  h1: 'Is cold email legal <span style="color:var(--grey-4);font-weight:300;">in New Zealand?</span>',
  cta: 'product',
  body: [
    { lead: 'Yes, business-to-business cold email is lawful in New Zealand, provided you meet the conditions in the Unsolicited Electronic Messages Act 2007. The Act is more permissive than European rules and stricter than many people assume — the obligations are specific, and the Department of Internal Affairs does enforce them.' },
    DISCLAIMER,
    { h: 'What the Act requires' },
    { steps: [
      '**A form of consent.** The Act recognises express consent, and also *inferred* consent — which is where most legitimate B2B outreach sits. Consent can be inferred where a business has conspicuously published a work-related address without a statement that it does not want unsolicited messages, and your message is relevant to that person\'s work.',
      '**Accurate sender identification.** The message must clearly identify who sent it and include accurate contact details. Anonymous or disguised outreach is prohibited outright.',
      '**A functional unsubscribe facility.** Every commercial electronic message must include a working way to opt out, and requests must be honoured — the Act requires this to be actioned promptly.',
      '**No address-harvesting software.** The Act specifically prohibits using automated harvesting tools and harvested-address lists. This matters directly: it makes *how you sourced the list* a legal question, not just a quality one.',
    ]},
    { h: 'The part that catches people out' },
    'Inferred consent is not a blank cheque. It depends on the address being **conspicuously published** and on your message being **relevant to the role** of the person it reaches.',
    'Writing to `admin@` at a plumbing company about plumbing software is a reasonable reading of relevance. Writing to a published address about something unrelated to that person\'s work is not, and neither is writing to an address you obtained from a harvested list rather than from the business\'s own publication.',
    { h: 'Penalties' },
    'The Act provides for civil pecuniary penalties, with the maximum figure for an organisation substantially higher than for an individual. The Department of Internal Affairs investigates complaints and has publicly reported enforcement action and settlements. Complaints from recipients are the usual trigger — which is another reason a single spam complaint deserves attention rather than a shrug.',
    { h: 'Practical compliance' },
    { list: [
      '**Source addresses from the business\'s own published material** — their website, a directory they listed themselves in, a trade register. Not from purchased or harvested lists.',
      '**Write to the role.** Relevance to that person\'s work is part of the legal basis, not just good manners.',
      '**Identify yourself properly** — real name, real business, real reply address, and a way to verify you exist.',
      '**Include a plain opt-out** in every message. A clear sentence is sufficient; it does not need to be a styled button.',
      '**Honour opt-outs permanently and globally**, across every campaign, forever.',
      '**Keep records** of where each address came from and when. If a complaint arrives, that record is your position.',
    ]},
    { note: 'New Zealand\'s Privacy Act 2020 also applies where you hold personal information, including named business email addresses. It governs how you collect, store and use that information, and gives individuals rights to access and correct it. The two regimes work together: the Unsolicited Electronic Messages Act governs the sending, the Privacy Act governs the data.' },
  ],
  faq: [
    { q: 'Do I need explicit permission to send a cold email in New Zealand?', a: 'Not necessarily. The Act recognises inferred consent, which can arise where a business has conspicuously published a work-related address without indicating it does not want unsolicited messages, and your message is relevant to that person\'s work. That is the basis most legitimate B2B outreach relies on — but it depends on both conditions holding.' },
    { q: 'Can I email addresses I found on a company website?', a: 'Generally yes, where the address is conspicuously published, there is no statement declining unsolicited messages, and your message is relevant to that person\'s role. This is precisely the situation inferred consent is designed for. Sourcing from the company\'s own publication also keeps you clear of the Act\'s prohibition on harvested lists.' },
    { q: 'What must every cold email include?', a: 'Clear and accurate identification of who is sending it, accurate contact information, and a functional unsubscribe facility that you honour promptly. Those are requirements of the Act rather than best practice, and a message missing any of them is non-compliant regardless of how relevant it is.' },
    { q: 'Does the Act apply if I am sending from outside New Zealand?', a: 'The Act covers messages with a New Zealand link, which includes messages sent to an address in New Zealand. Sending from overseas does not remove the obligation when your recipients are here.' },
  ],
  related: [
    ['/cold-email-law-australia/', 'Cold email law in Australia'],
    ['/finding-business-emails-ethically/', 'Finding business emails ethically'],
    ['/cold-email-deliverability-checklist/', 'The deliverability checklist'],
  ],
},

{
  slug: 'cold-email-law-australia',
  title: 'Is Cold Email Legal in Australia? The Spam Act 2003 and Privacy Act Explained',
  description: 'What Australian law requires of cold outreach: the Spam Act 2003 consent, identification and unsubscribe rules, how the Privacy Act limits list building, and why enforcement here is unusually active.',
  keywords: 'cold email legal Australia, Spam Act 2003, Australian privacy act email, B2B cold email Australia ACMA',
  eyebrow: 'Australia',
  short: 'Cold email law · AU',
  h1: 'Is cold email legal <span style="color:var(--grey-4);font-weight:300;">in Australia?</span>',
  cta: 'product',
  body: [
    { lead: 'Business-to-business cold email is lawful in Australia under the Spam Act 2003, subject to consent, identification and unsubscribe requirements. Australia deserves particular care for one reason: the regulator enforces actively and has issued substantial penalties to well-known companies, including for unsubscribe failures rather than for sending as such.' },
    DISCLAIMER,
    { h: 'The three requirements of the Spam Act' },
    { cards: [
      { t: 'Consent', d: 'Express or inferred. Inferred consent can arise from an existing business relationship, or where a work-related address is conspicuously published without a statement declining unsolicited messages — and your message relates to that role.' },
      { t: 'Identify', d: 'The message must clearly identify the sender and include accurate contact details that remain valid.' },
      { t: 'Unsubscribe', d: 'A functional opt-out in every commercial message, honoured within the period the Act specifies. This is where enforcement most often bites.' },
    ]},
    { h: 'Address-harvesting is separately prohibited' },
    'The Spam Act prohibits supplying, acquiring or using address-harvesting software and harvested-address lists. This makes list provenance a legal question in Australia, not merely a deliverability one. A purchased list whose origin the seller cannot document is a compliance risk regardless of how well the campaign is run.',
    { h: 'The Privacy Act adds a second layer' },
    'Beyond the Spam Act, the Privacy Act 1988 and its Australian Privacy Principles govern personal information, which includes named business email addresses that identify an individual.',
    'The principle that most often surprises people is **purpose limitation**: personal information collected for one purpose generally cannot be used for an unrelated one. An address published so customers can request a quote was not published so that vendors could build a prospecting database — and repurposing it that way is exactly the tension the APPs are concerned with.',
    { list: [
      '**APP 3** governs collection — you should only collect personal information reasonably necessary for your functions.',
      '**APP 5** requires notification — telling people you hold their information and why.',
      '**APP 6** limits use and disclosure to the purpose of collection, or a related purpose the person would reasonably expect.',
      '**APP 7** applies specifically to direct marketing and includes opt-out obligations.',
    ]},
    { note: 'Small businesses under a turnover threshold are exempt from parts of the Privacy Act, but the exemption is narrower than commonly assumed and does not extend to the Spam Act at all. Do not assume you fall outside it without checking.' },
    { h: 'Practical compliance' },
    { steps: [
      '**Document where every address came from.** In Australia more than anywhere, provenance is the thing you may be asked to prove.',
      '**Never use purchased or harvested lists.** Both the Spam Act prohibition and the Privacy Act purpose limitation point the same direction.',
      '**Make the unsubscribe genuinely functional** and process it promptly. Enforcement history shows this is the failure regulators act on.',
      '**Keep identification accurate and current.** Contact details in the message must still work.',
      '**Write only to roles your message genuinely relates to.** Relevance supports inferred consent; irrelevance undermines it.',
    ]},
  ],
  faq: [
    { q: 'Does the Spam Act apply to B2B email?', a: 'Yes. The Act covers commercial electronic messages generally, and does not exempt business-to-business communication. The consent, identification and unsubscribe requirements apply whether you are writing to a consumer or to a company.' },
    { q: 'What counts as inferred consent in Australia?', a: 'Broadly, an existing business relationship, or a work-related address conspicuously published without any statement declining unsolicited messages, where your message relates to that person\'s role. It is narrower than it sounds: relevance to the role is doing real work in that test, and a published address does not imply consent to receive anything at all.' },
    { q: 'How quickly must I honour an unsubscribe request?', a: 'The Act sets a specific short period, and this is the requirement regulators have most visibly enforced. The safe practice is to process opt-outs immediately and automatically, and to maintain a single suppression list across every campaign rather than per-campaign settings.' },
    { q: 'Am I exempt as a small business?', a: 'The small business exemption applies to parts of the Privacy Act, not the Spam Act — so the consent, identification and unsubscribe rules apply to you regardless of size. The Privacy Act exemption itself has conditions and exceptions that catch more businesses than people expect, so it is worth checking rather than assuming.' },
  ],
  related: [
    ['/cold-email-law-new-zealand/', 'Cold email law in New Zealand'],
    ['/finding-business-emails-ethically/', 'Finding business emails ethically'],
  ],
},

{
  slug: 'cold-email-law-united-states',
  title: 'Is Cold Email Legal in the US? CAN-SPAM and State Privacy Laws Explained',
  description: 'What CAN-SPAM actually requires of cold outreach in the United States, why it is more permissive than most regimes, and how state privacy laws such as the CCPA change the picture.',
  keywords: 'cold email legal United States, CAN-SPAM Act, US email law B2B, CCPA cold email',
  eyebrow: 'United States',
  short: 'Cold email law · US',
  h1: 'Is cold email legal <span style="color:var(--grey-4);font-weight:300;">in the United States?</span>',
  cta: 'product',
  body: [
    { lead: 'Yes, and the United States is the most permissive major jurisdiction for cold outreach. CAN-SPAM does not require consent before sending — it regulates how you send and what you must do when someone asks you to stop. That permissiveness is real, and it is also the reason American outreach advice travels badly to other countries.' },
    DISCLAIMER,
    { h: 'What CAN-SPAM requires' },
    { list: [
      '**No false or misleading header information.** The "From", "To" and routing details must accurately identify who sent the message.',
      '**No deceptive subject lines.** The subject must reflect what is actually in the message.',
      '**Identify the message as an advertisement**, where applicable, in a clear way.',
      '**Include a valid physical postal address.** This one surprises people and is genuinely required.',
      '**Provide a clear opt-out mechanism**, and honour requests promptly — the Act sets a specific period.',
      '**Monitor what others do on your behalf.** Hiring an agency does not transfer your legal responsibility.',
    ]},
    { h: 'What CAN-SPAM does not require' },
    'Consent. There is no opt-in requirement before a first commercial message — which is the single largest difference from European rules and the reason a great deal of outreach advice written for the American market is unsafe to apply in the EU or UK.',
    { note: 'This asymmetry matters commercially. If you sell internationally, the compliant approach is to apply the strictest applicable regime to each recipient rather than your own local rules. A campaign that is lawful from Texas can be unlawful the moment it reaches Berlin.' },
    { h: 'State laws are a second layer' },
    'CAN-SPAM is federal and largely preempts state anti-spam statutes, but state *privacy* laws are a separate matter and have expanded considerably.',
    { list: [
      '**California (CCPA/CPRA)** gives residents rights over personal information including access, deletion and opting out of sale or sharing. Business contact information receives some accommodation, but the exemptions have narrowed over time.',
      '**Virginia, Colorado, Connecticut, Utah and a growing list of others** have enacted comprehensive privacy statutes with varying thresholds and obligations.',
      'These laws generally regulate **how you handle the data** rather than whether you may send — but if you hold a prospect database of any size, they apply to you as a data holder.',
    ]},
    { h: 'Penalties' },
    'CAN-SPAM provides for civil penalties assessed per violating email, and because each message counts separately, totals in enforcement actions have reached very large figures. The Federal Trade Commission enforces it, and internet service providers can also bring actions.',
    { h: 'Practical compliance' },
    { steps: [
      '**Put a real postal address in every message.** A registered business address or a mailbox service is acceptable; omitting it is a straightforward violation.',
      '**Keep headers and subject lines truthful.** No "Re:" on a first contact, no disguised sender.',
      '**Make opting out easy and honour it fast.** Automate suppression so it cannot be missed.',
      '**Maintain one global suppression list**, not per-campaign settings.',
      '**Apply the stricter rule when in doubt** — particularly if any recipient may be in Europe.',
    ]},
  ],
  faq: [
    { q: 'Do I need consent to send cold email in the US?', a: 'No. CAN-SPAM regulates the conduct of commercial email rather than requiring prior permission, which makes the United States considerably more permissive than the EU, the UK, Australia or New Zealand. That permissiveness applies only to recipients in the US.' },
    { q: 'Do I really need a physical address in the email?', a: 'Yes. A valid physical postal address is an explicit CAN-SPAM requirement, and omitting it is one of the easiest violations to prove. A registered business address or a commercial mailbox service satisfies it.' },
    { q: 'How fast must I process an opt-out?', a: 'CAN-SPAM sets a specific short period, and continuing to send after a request is one of the clearest violations available. The practical answer is to suppress immediately and automatically rather than relying on a manual process that might slip.' },
    { q: 'Does CAN-SPAM apply if I am outside the United States?', a: 'It applies to commercial messages sent to recipients in the United States regardless of where the sender is. Location does not remove the obligation, and enforcement has reached overseas senders.' },
  ],
  related: [
    ['/cold-email-law-europe-gdpr/', 'Cold email and GDPR'],
    ['/cold-email-law-new-zealand/', 'Cold email law in New Zealand'],
  ],
},

{
  slug: 'cold-email-law-europe-gdpr',
  title: 'Cold Email and GDPR — What Is Actually Allowed in the EU',
  description: 'How GDPR and the ePrivacy Directive govern B2B cold email in Europe: legitimate interest as a lawful basis, the transparency obligations people forget, national variation, and what compliant outreach requires.',
  keywords: 'cold email GDPR, GDPR B2B email, legitimate interest cold email, ePrivacy directive email, EU cold email legal',
  eyebrow: 'European Union',
  short: 'Cold email and GDPR',
  h1: 'Cold email and GDPR. <span style="color:var(--grey-4);font-weight:300;">Harder, not impossible.</span>',
  cta: 'product',
  body: [
    { lead: 'B2B cold email can be lawful in the European Union, but the requirements are substantially heavier than in the United States, New Zealand or Australia — and they vary by member state. Anyone telling you GDPR simply bans cold email is wrong; anyone telling you it is straightforward is also wrong.' },
    DISCLAIMER,
    { h: 'Two regimes apply at once' },
    { cards: [
      { t: 'GDPR', d: 'Governs the personal data. A named business address like firstname.lastname@company.com identifies a person and is therefore personal data. You need a lawful basis to process it, and obligations of transparency and rights follow.' },
      { t: 'ePrivacy', d: 'Governs the sending of electronic marketing. Implemented separately by each member state, which is why the rules differ across the bloc even though GDPR is uniform.' },
    ]},
    { h: 'Legitimate interest — the usual basis, with conditions' },
    'Most compliant B2B outreach in Europe relies on legitimate interest rather than consent. GDPR itself acknowledges that direct marketing may be a legitimate interest. But relying on it is not a formality — it requires you to actually carry out and document a balancing assessment: your interest in marketing against the individual\'s rights and their reasonable expectations.',
    'It is much easier to defend when the message is relevant to that person\'s professional role, sent to a business address, at a company plausibly in your market. It is very hard to defend for untargeted bulk sending, and effectively impossible for personal addresses.',
    { h: 'The obligation people forget' },
    '**Transparency.** Under GDPR, when you obtain personal data from a source other than the individual, you must inform them — typically at the point of first contact — of who you are, what data you hold, where you got it, your lawful basis, and their rights.',
    'In practice this means a compliant first cold email in Europe includes a short privacy notice or a clear link to one. This is the single most commonly omitted requirement, and its absence is what turns an otherwise reasonable message into a complaint.',
    { list: [
      '**Right of access** — they can ask what you hold about them.',
      '**Right to erasure** — they can ask you to delete it.',
      '**Right to object** — for legitimate-interest processing, an objection to direct marketing is absolute. You stop, permanently.',
      '**Records** — you must be able to show where the data came from and why you believe your basis holds.',
    ]},
    { h: 'National variation is real' },
    'ePrivacy is a directive rather than a regulation, so implementation differs. Some member states apply consent requirements to business recipients that others do not; some distinguish sole traders and partnerships from incorporated companies, treating the former closer to individuals. Germany is generally regarded as among the strictest.',
    'The practical consequence: **"compliant in Europe" is not a single status.** If you target multiple member states, check the rules for each, or take the strictest reading across all of them.',
    { note: 'A pragmatic position many small businesses take: keep European outreach narrow, highly relevant, sent only to business addresses at companies with an evident connection to the offer, always with a privacy notice, and with instant permanent suppression on any objection. That is defensible. Bulk untargeted sending into the EU is not.' },
  ],
  faq: [
    { q: 'Is cold email banned under GDPR?', a: 'No. GDPR does not ban cold email; it requires a lawful basis for processing personal data, and legitimate interest can serve for relevant B2B outreach. What GDPR adds are real obligations — a documented balancing assessment, a privacy notice at first contact, and honouring objections absolutely — that make careless bulk sending unlawful while leaving targeted, transparent outreach available.' },
    { q: 'Is a company email address personal data?', a: 'A named address such as firstname.lastname@company.com identifies an individual and is personal data. A generic role address such as info@company.com generally is not, though the picture is less clean where a sole trader\'s business address is effectively personal. The safe assumption is that named addresses are personal data.' },
    { q: 'What do I have to tell people in the first email?', a: 'Where you obtained their details, who you are, why you are contacting them, your lawful basis, and how they can object or request erasure. This can be a brief paragraph or a clear link to a privacy notice — but omitting it entirely is the most common compliance failure in European outreach.' },
    { q: 'Does GDPR apply if my business is outside the EU?', a: 'It can. GDPR has extraterritorial reach and applies where you offer goods or services to people in the EU or monitor their behaviour. Sending marketing email to prospects in the EU from New Zealand, Australia or the United States does not place you outside its scope.' },
  ],
  related: [
    ['/cold-email-law-united-kingdom/', 'Cold email law in the UK'],
    ['/cold-email-law-united-states/', 'Cold email law in the US'],
    ['/finding-business-emails-ethically/', 'Finding business emails ethically'],
  ],
},

{
  slug: 'cold-email-law-united-kingdom',
  title: 'Cold Email Law in the UK — PECR, UK GDPR and the Corporate Subscriber Rule',
  description: 'What UK law allows in cold outreach: how PECR treats corporate subscribers differently from individuals, why sole traders and partnerships are treated differently, and what compliant B2B email requires.',
  keywords: 'cold email UK law, PECR B2B email, UK GDPR cold email, ICO cold email rules, corporate subscriber',
  eyebrow: 'United Kingdom',
  short: 'Cold email law · UK',
  h1: 'Cold email in the UK. <span style="color:var(--grey-4);font-weight:300;">The corporate subscriber rule.</span>',
  cta: 'product',
  body: [
    { lead: 'The United Kingdom occupies a middle position: more permissive than much of the European Union for business-to-business email, considerably stricter than the United States. The distinction that decides most cases is who counts as a "corporate subscriber" — and it is narrower than most people assume.' },
    DISCLAIMER,
    { h: 'Two regimes, as in the EU' },
    'UK GDPR governs the personal data. The Privacy and Electronic Communications Regulations — PECR — govern electronic marketing. Both apply to cold email, and the Information Commissioner\'s Office enforces them.',
    { h: 'The corporate subscriber distinction' },
    'PECR\'s consent requirement for marketing email applies to individual subscribers. **Corporate subscribers are treated differently**, which is what makes B2B cold email workable in the UK.',
    { table: {
      minWidth: 520,
      head: ['Recipient type', 'Treatment under PECR'],
      rows: [
        ['Limited companies, LLPs, public bodies', 'Corporate subscriber — consent not required for marketing email'],
        ['Sole traders', 'Treated as individual subscribers'],
        ['Non-LLP partnerships', 'Treated as individual subscribers'],
        ['Personal addresses of any kind', 'Individual subscriber'],
      ],
    }},
    'The consequence is direct and easy to get wrong: emailing a limited company sits on much firmer ground than emailing a sole trader, and a great many small businesses — including most tradespeople, consultants and independent operators — are sole traders. **You need to know the legal form of the business you are contacting**, not just that it is a business.',
    { h: 'UK GDPR still applies' },
    'Even where PECR permits the send, UK GDPR governs the underlying personal data. That means:',
    { list: [
      '**A lawful basis** — normally legitimate interest, with a documented balancing assessment.',
      '**Transparency** — telling the recipient where you got their details and what rights they have, at first contact.',
      '**The right to object** — absolute for direct marketing. On objection you stop permanently.',
      '**Accurate records** of source and basis, which the ICO can ask you to produce.',
    ]},
    { h: 'What every message must do' },
    { steps: [
      '**Identify the sender accurately.** Concealing or disguising identity is prohibited.',
      '**Provide a valid address for opt-out requests** and honour them without delay.',
      '**Tell them where you got their details** — this is the UK GDPR transparency obligation, and it is the step most often missed.',
      '**Check the legal form of the business** before treating a recipient as a corporate subscriber.',
      '**Keep the message relevant to the role.** Relevance supports the legitimate-interest assessment you are relying on.',
    ]},
    { note: 'The ICO publishes direct marketing guidance in plain English, and it is genuinely readable — unusually so for regulatory material. If you send into the UK regularly, an hour with it is a better investment than any summary, including this one.' },
  ],
  faq: [
    { q: 'Can I cold email UK businesses without consent?', a: 'For corporate subscribers — limited companies, LLPs and public bodies — PECR does not require consent for marketing email. For sole traders and non-LLP partnerships, who are treated as individual subscribers, the position is much closer to requiring consent. Since many small businesses are sole traders, the legal form of the recipient matters before you send.' },
    { q: 'How do I know if a business is a corporate subscriber?', a: 'Check the company register. UK companies and LLPs are searchable on Companies House, and most businesses display their company number and registered form on their website footer as they are required to. If you cannot establish the legal form, the cautious approach is to treat the recipient as an individual subscriber.' },
    { q: 'Do I have to say where I got their email address?', a: 'Yes. UK GDPR requires you to inform people when you obtain their personal data from a source other than themselves, including the source. In practice this means a brief privacy notice or a clear link in your first message — and it is the most commonly omitted requirement in UK outreach.' },
    { q: 'What are the penalties?', a: 'The ICO can issue monetary penalties under PECR, and separately under UK GDPR where data protection obligations are breached. It publishes enforcement actions, and unsolicited marketing is a recurring category. Complaints from recipients are the usual starting point for an investigation.' },
  ],
  related: [
    ['/cold-email-law-europe-gdpr/', 'Cold email and GDPR'],
    ['/cold-email-law-united-states/', 'Cold email law in the US'],
    ['/finding-business-emails-ethically/', 'Finding business emails ethically'],
  ],
},

];
