/* Local and private AI.
 *
 * This cluster carries the position argued in the manifesto:
 * that useful AI is moving toward running close to the person it
 * serves. Every page here has to stay honest about the trade-offs,
 * or the position reads as marketing rather than conviction. */

export default [

{
  slug: 'run-ai-locally-business',
  title: 'How to Run AI Locally in Your Business — A Practical Guide',
  description: 'What it takes to run AI on your own hardware: which tasks work well locally, what you need, where local models genuinely fall short, and how to decide what stays in-house.',
  keywords: 'run AI locally, local AI business, on-premise AI, self-hosted LLM, private AI setup',
  eyebrow: 'Local AI',
  short: 'Running AI locally',
  h1: 'Running AI on your own machines. <span style="color:var(--grey-4);font-weight:300;">What it actually takes.</span>',
  cta: 'private',
  body: [
    { lead: 'Running capable language models on ordinary business hardware became realistic surprisingly recently. Not for everything — the largest cloud models remain meaningfully better at the hardest reasoning — but for a wide band of practical work, a model running on a machine in your office is now good enough, and the data never leaves the building.' },
    { h: 'What works well locally' },
    { list: [
      '**Summarising and extracting.** Pulling structured information out of documents, emails, transcripts and reports. Local models are strong here and the documents are often the most sensitive thing you have.',
      '**Drafting and rewriting.** First drafts, tone adjustment, translation, standard correspondence.',
      '**Classification and routing.** Sorting incoming enquiries, tagging tickets, triaging documents.',
      '**Search over your own material.** Answering questions from your own files, contracts and history — the single most valuable local use case for most businesses, and the one that would be most uncomfortable to send elsewhere.',
      '**Anything high-volume and repetitive.** Where per-call cloud costs accumulate, local inference is free after hardware.',
    ]},
    { h: 'What still favours the cloud' },
    'Being straight about this matters more than being enthusiastic:',
    { list: [
      '**Hard multi-step reasoning.** Complex analysis, difficult code, long chains of inference. The frontier models are better and the gap is real.',
      '**Very long documents.** Large context windows are memory-hungry; local models handle shorter contexts comfortably.',
      '**Anything needing the newest capabilities.** Cloud providers ship improvements continuously; local models move in releases.',
      '**Occasional use.** If you run a handful of requests a week, hardware is a poor investment against a few dollars of API cost.',
    ]},
    { h: 'What you need' },
    { table: {
      minWidth: 560,
      head: ['Setup', 'Realistic use', 'Rough cost'],
      rows: [
        ['A modern laptop with 16GB', 'Small models, light daily work', 'Hardware you likely own'],
        ['32GB desktop or Mac', 'Mid-size models, comfortable daily use', 'Mid four figures'],
        ['Dedicated GPU workstation', 'Larger models, multiple users, speed', 'Upper four to five figures'],
        ['Rented private server', 'Team access without buying hardware', 'Monthly, but your instance'],
      ],
    }},
    'Detail on sizing: [local LLM hardware requirements](/local-llm-hardware-requirements/).',
    { h: 'How to start without committing' },
    { steps: [
      '**Install [Ollama](https://ollama.com) on a machine you already have.** Free, and it runs on Mac, Windows and Linux.',
      '**Pull a small model and use it for a week** on real work — summarising, drafting, sorting. You will learn quickly where it is good enough.',
      '**Pick one workflow that is genuinely sensitive** and try moving just that one locally. Client documents, HR material, financial records.',
      '**Measure honestly.** Compare output against what you get from a cloud model on the same task. Sometimes the gap does not matter; sometimes it does. Both answers are useful.',
      '**Only then decide about hardware.** Buying a workstation before knowing which workflows benefit is how expensive machines end up idle.',
    ]},
    { note: 'The most common mistake is treating this as all-or-nothing. Most businesses that do this well end up with a split: sensitive and repetitive work runs locally, hard reasoning goes to a cloud model, and the boundary is a deliberate decision rather than a default.' },
  ],
  faq: [
    { q: 'Is local AI as good as ChatGPT or Claude?', a: 'Not for the hardest tasks — the frontier cloud models remain better at complex reasoning, long documents and code. For summarising, drafting, classifying and answering questions over your own material, good open-weight models are close enough that the difference rarely changes the outcome. Test on your actual work rather than on benchmarks.' },
    { q: 'What does it cost to run AI locally?', a: 'After hardware, essentially nothing per use — which is what makes it attractive for high-volume repetitive work. The cost is upfront: a machine with enough memory, and the time to set it up. Against a few dollars a month of API usage, hardware makes no sense; against continuous processing of thousands of documents, it pays back quickly.' },
    { q: 'Do I need a technical person to set this up?', a: 'For a single machine running Ollama, no — installation is a download and a command. For serving a team, integrating with existing systems, or handling regulated data properly, yes. The gap between "it runs on my laptop" and "the business depends on it" is where most of the real work sits.' },
    { q: 'Can local AI access my company files safely?', a: 'That is precisely its advantage: a local model reading your contracts, invoices and correspondence sends nothing anywhere. The security question shifts from "what does the provider do with this" to "who in my business can query this system", which is a question you control and can audit.' },
  ],
  related: [
    ['/ollama-for-business/', 'Ollama for business'],
    ['/local-llm-hardware-requirements/', 'Hardware requirements'],
    ['/local-ai-vs-cloud-ai/', 'Local vs cloud, compared'],
    ['/ai-data-privacy-business/', 'AI and business data privacy'],
  ],
},

{
  slug: 'ollama-for-business',
  title: 'Ollama for Business — What It Is and How to Use It Properly',
  description: 'A practical introduction to Ollama for business use: what it does, choosing a model, connecting it to your own tools, serving a team, and the limits worth knowing before you commit.',
  keywords: 'Ollama business, Ollama guide, run llama locally, local LLM server, Ollama API',
  eyebrow: 'Local AI',
  short: 'Ollama for business',
  h1: 'Ollama for business. <span style="color:var(--grey-4);font-weight:300;">The shortest path to local AI.</span>',
  cta: 'private',
  body: [
    { lead: 'Ollama is the reason running a language model on your own hardware stopped being a systems engineering project. It downloads models, runs them, and exposes a local API that behaves much like the cloud ones — which means most software that talks to an AI provider can be pointed at it with a configuration change.' },
    { h: 'What it actually does' },
    { list: [
      '**Downloads and manages models** with a single command, handling the formats and quantisation for you.',
      '**Runs them efficiently** on Mac, Windows and Linux, using GPU acceleration where available.',
      '**Exposes a local HTTP API** on your machine, so your own tools can call it like any other AI service.',
      '**Keeps everything local.** No account, no telemetry of your prompts, no data leaving the machine.',
    ]},
    { h: 'Getting started' },
    { code: '# install from ollama.com, then:\nollama pull llama3.1\nollama run llama3.1\n\n# it now also serves an API at localhost:11434' },
    'That is genuinely the whole setup for a single machine. The interesting work starts afterwards, in what you point at it.',
    { h: 'Choosing a model' },
    { table: {
      minWidth: 560,
      head: ['Size', 'Memory needed', 'Suited to'],
      rows: [
        ['3B – 8B', '8 – 16GB', 'Summarising, classifying, drafting, fast responses'],
        ['13B – 14B', '16 – 32GB', 'General work with noticeably better quality'],
        ['30B – 70B', '32 – 64GB+', 'Closest to cloud quality; slower without a strong GPU'],
      ],
    }},
    'Start smaller than you think you need. A fast small model you actually use beats a large one that takes thirty seconds per response and quietly stops being used. [Hardware detail here.](/local-llm-hardware-requirements/)',
    { h: 'Using it in real work' },
    { steps: [
      '**Point existing tools at it.** Anything that lets you set a custom API endpoint — including our own [Cold Outreach Machine](/marketplace/cold-outreach-machine/) — can use a local model instead of a cloud provider.',
      '**Build a document assistant.** Combine Ollama with a local search index over your own files so the model can answer from your material without any of it leaving.',
      '**Automate a repetitive task.** Classification, extraction, first-draft writing. High volume is where local economics win decisively.',
      '**Serve a small team.** Run it on one machine on your network and let colleagues use it. Add authentication before you do — the default configuration assumes a single trusted user.',
    ]},
    { note: '**A security point people miss:** Ollama\'s API has no authentication by default. On a personal machine that is fine. Exposed to a network — and certainly to the internet — it is an open endpoint anyone can query. Put it behind a reverse proxy with authentication, or keep it bound to localhost.' },
    { h: 'Honest limits' },
    { list: [
      '**Quality below the frontier.** Real, and it matters most on complex reasoning.',
      '**Speed depends entirely on hardware.** A large model without GPU acceleration is slow enough to change how you use it.',
      '**No built-in multi-user management.** It is a runtime, not a platform. Team access is something you build around it.',
      '**You own the maintenance.** Updates, model changes and uptime are yours.',
    ]},
  ],
  faq: [
    { q: 'Is Ollama free for commercial use?', a: 'Ollama itself is open source and free. The models it runs have their own licences, and those vary — most open-weight models permit commercial use, some restrict it above certain scale thresholds. Check the licence of the specific model you intend to rely on rather than assuming.' },
    { q: 'Can I use Ollama with my existing software?', a: 'Usually yes. Its API is close enough to common cloud APIs that most tools accepting a custom endpoint will work with a configuration change. That compatibility is the main reason it became the default way to run models locally.' },
    { q: 'How many people can share one Ollama instance?', a: 'Technically several, practically it depends on hardware — requests queue, so a handful of concurrent users on a well-specified machine is comfortable and a whole department is not. For team-scale use you want a dedicated GPU machine and a queueing layer in front.' },
    { q: 'Which model should a business start with?', a: 'An 8B-class model on whatever machine you already own. It runs comfortably in 16GB, responds fast enough to be usable, and is good enough to tell you within a week which of your workflows local AI can handle. Scale up only once you know what you actually need.' },
  ],
  related: [
    ['/run-ai-locally-business/', 'Running AI locally'],
    ['/local-llm-hardware-requirements/', 'Hardware requirements'],
    ['/self-hosted-cold-email/', 'Self-hosted cold email'],
  ],
},

{
  slug: 'local-llm-hardware-requirements',
  title: 'Local LLM Hardware Requirements — What You Actually Need',
  description: 'Hardware for running language models locally: how memory determines model size, why unified memory changed the maths, GPU versus CPU, and realistic configurations at each budget.',
  keywords: 'local LLM hardware, run LLM requirements, GPU for AI, RAM for local AI, Mac for local LLM',
  eyebrow: 'Local AI',
  short: 'Hardware requirements',
  h1: 'Hardware for local models. <span style="color:var(--grey-4);font-weight:300;">Memory is the whole story.</span>',
  cta: 'private',
  body: [
    { lead: 'One rule explains most of this: the model must fit in memory. Everything else — speed, model choice, whether you need a GPU — follows from that constraint. Get memory right and the rest is optimisation.' },
    { h: 'Sizing, roughly' },
    'A quantised model needs approximately its parameter count in gigabytes, plus overhead for context. An 8-billion-parameter model at common quantisation wants around 8–10GB. A 70B model wants 40GB or more.',
    { table: {
      minWidth: 600,
      head: ['Memory available', 'Comfortable model size', 'What that gets you'],
      rows: [
        ['8GB', '3B, small 7B quantised', 'Basic summarising and classifying. Usable, limited.'],
        ['16GB', '7B – 8B comfortably', 'The practical entry point. Good for most business tasks.'],
        ['32GB', '13B – 14B, 30B quantised', 'Noticeably better quality. A good default target.'],
        ['64GB+', '70B quantised', 'Closest to cloud quality available locally.'],
      ],
    }},
    { h: 'Unified memory changed the picture' },
    'Apple Silicon Macs share memory between processor and graphics, so a machine with 64GB of unified memory can load a model that would otherwise require an expensive dedicated GPU. For a small business wanting one capable machine without building a workstation, a Mac with generous memory is often the simplest good answer — and it is quiet enough to sit in an office.',
    'On the PC side, video memory on the graphics card is the binding constraint rather than system memory. A card with 24GB of VRAM handles considerably more than one with 8GB, regardless of how much system RAM the machine has.',
    { h: 'Does it need a GPU?' },
    'For usable speed, effectively yes — or unified memory doing the same job. Models run on CPU alone, but generation slows to the point where people stop using the system, which is the real failure mode. A tool that takes forty seconds to answer gets abandoned no matter how private it is.',
    { h: 'Configurations that make sense' },
    { cards: [
      { t: 'Trying it out', d: 'The laptop you already own, if it has 16GB. Costs nothing, and tells you within a week which workflows local AI can actually handle.' },
      { t: 'One person, daily use', d: 'A Mac with 32–64GB unified memory, or a PC with a 16–24GB graphics card. This is the sweet spot for most small businesses.' },
      { t: 'Small team', d: 'A dedicated machine with a strong GPU on the network, serving several people, with authentication in front of it.' },
      { t: 'No hardware purchase', d: 'A rented GPU instance. Monthly cost, but a private instance rather than a shared service — a reasonable middle ground for regulated data.' },
    ]},
    { note: 'Buy for the model you will actually run daily, not the largest one you might experiment with. A fast 8B model used constantly delivers more value than a 70B model that is technically impressive and too slow to fit into anyone\'s working rhythm.' },
  ],
  faq: [
    { q: 'Can I run a local LLM on a normal laptop?', a: 'With 16GB of memory, yes — an 8B-class model runs comfortably and handles summarising, drafting and classification well. With 8GB you are limited to small models and will feel it. Below that, local inference is not a realistic proposition.' },
    { q: 'Do I need an expensive graphics card?', a: 'You need either a capable GPU or Apple Silicon unified memory. CPU-only inference works but is slow enough that people abandon the tool, which defeats the purpose. The cheapest viable path is usually a Mac with generous unified memory rather than building a PC around a high-VRAM card.' },
    { q: 'Is it cheaper than paying for cloud AI?', a: 'It depends entirely on volume. For occasional use, no — hardware costs far more than a few dollars of API calls. For continuous high-volume work, hardware pays back within months and then costs nothing per use. Estimate your monthly API spend honestly before buying anything.' },
    { q: 'What about running models on a rented server?', a: 'A good middle path: a private GPU instance gives you a dedicated environment without capital expenditure, and for regulated data a single-tenant instance is often acceptable where a shared consumer service is not. You pay monthly, but the instance is yours rather than a shared service.' },
  ],
  related: [
    ['/ollama-for-business/', 'Ollama for business'],
    ['/local-ai-vs-cloud-ai/', 'Local vs cloud, compared'],
    ['/run-ai-locally-business/', 'Running AI locally'],
  ],
},

{
  slug: 'local-ai-vs-cloud-ai',
  title: 'Local AI vs Cloud AI — An Honest Comparison for Businesses',
  description: 'Where local AI wins and where cloud AI wins: quality, cost at volume, privacy, latency, maintenance and control — and why the sensible answer for most businesses is both.',
  keywords: 'local AI vs cloud AI, on-premise vs cloud LLM, private AI comparison, self-hosted AI benefits',
  eyebrow: 'Local AI',
  short: 'Local vs cloud',
  h1: 'Local or cloud? <span style="color:var(--grey-4);font-weight:300;">The answer is usually both.</span>',
  cta: 'private',
  body: [
    { lead: 'This is framed as a choice more often than it needs to be. The businesses handling it well do not pick a side — they decide, workflow by workflow, which side each one belongs on. What follows is the comparison that decision rests on.' },
    { h: 'The comparison' },
    { table: {
      minWidth: 640,
      head: ['', 'Local', 'Cloud'],
      rows: [
        ['Quality on hard tasks', 'Good, below frontier', 'Best available'],
        ['Cost per request', 'Zero after hardware', 'Per token, accumulates'],
        ['Upfront cost', 'Hardware', 'None'],
        ['Data exposure', 'None — never leaves', 'Sent to the provider'],
        ['Works offline', 'Yes', 'No'],
        ['Latency', 'Fast, no network round trip', 'Network dependent'],
        ['Maintenance', 'Yours', 'Theirs'],
        ['Improves over time', 'When you update it', 'Continuously, automatically'],
        ['Availability risk', 'Your hardware', 'Provider outages, policy or pricing changes'],
      ],
    }},
    { h: 'The case for cloud' },
    { list: [
      '**The best models are there.** For genuinely hard reasoning, the frontier models are better and pretending otherwise helps nobody.',
      '**Nothing to maintain.** No hardware, no updates, no capacity planning.',
      '**It improves without you.** Capabilities arrive continuously.',
      '**Elastic.** A thousand requests in an hour costs a thousand requests; locally it costs a queue.',
    ]},
    { h: 'The case for local' },
    { list: [
      '**Data never leaves.** For client files, health records, legal documents and financial data, this is not a preference — it is often the requirement.',
      '**Cost stops scaling.** After hardware, volume is free. High-throughput repetitive work is where this becomes decisive.',
      '**No dependency.** No outages, no deprecated models, no pricing changes, no terms-of-service updates that alter what you are permitted to do.',
      '**It works offline** — which matters more in places with unreliable connectivity than most vendors, writing from cities with fibre, appreciate.',
    ]},
    { h: 'How to split it' },
    { steps: [
      '**Sensitive data stays local.** Client documents, personal records, anything you would need to disclose a breach of.',
      '**High-volume repetitive work goes local.** Classification, extraction, routing — the tasks where per-call costs quietly accumulate.',
      '**Hard reasoning goes to the cloud.** Complex analysis, difficult code, work where the quality gap changes the result.',
      '**Anything customer-facing and latency-sensitive** goes wherever it responds faster, which is often local.',
      '**Write the boundary down.** A rule your team understands beats a habit nobody can articulate — and it is the thing an auditor or a client will ask about.',
    ]},
    { note: 'The direction of travel is worth noting when you plan. Open-weight models have been closing the gap with frontier models steadily, and consumer hardware capable of running them keeps getting cheaper. A workflow that needs the cloud today may not in a year — which argues for building so you can move it, rather than hard-wiring one provider into everything.' },
  ],
  faq: [
    { q: 'Is local AI private by definition?', a: 'Local means the data does not leave your infrastructure, which removes the third-party exposure entirely. It does not automatically make you compliant or secure: access control, storage, backups and who inside your business can query the system are all still your responsibility. Local removes one risk and hands you the others.' },
    { q: 'Will local models catch up with cloud models?', a: 'The gap has narrowed considerably and open-weight releases have repeatedly reached capability levels that were frontier a year or two earlier. Whether that continues is not knowable, so the sensible position is to build systems where the model can be swapped rather than betting on either side.' },
    { q: 'What is the biggest hidden cost of running AI locally?', a: 'Maintenance and the expertise to do it. Cloud providers absorb updates, uptime and scaling. Locally that is yours — and for a business with no technical staff, that ongoing burden is a larger factor than hardware price. It is the reason some businesses that could run locally sensibly choose not to.' },
    { q: 'Can I switch later?', a: 'Yes, if you design for it. Keep the model behind an interface your software calls rather than embedding one provider throughout. Tools that support both — like our own outreach system, which runs on either a cloud provider or a local model — make the decision reversible, which is worth more than getting it right first time.' },
  ],
  related: [
    ['/run-ai-locally-business/', 'Running AI locally'],
    ['/ai-data-privacy-business/', 'AI and business data privacy'],
    ['/local-llm-hardware-requirements/', 'Hardware requirements'],
  ],
},

{
  slug: 'ai-data-privacy-business',
  title: 'AI and Your Business Data — What Actually Happens to What You Send',
  description: 'What AI providers do with business data, how to read the terms that matter, which questions to ask before adopting a tool, and the practical options for keeping sensitive material out of third-party systems.',
  keywords: 'AI data privacy business, does ChatGPT train on my data, AI confidentiality, business data AI providers',
  eyebrow: 'Privacy',
  short: 'AI and your data',
  h1: 'What happens to the data <span style="color:var(--grey-4);font-weight:300;">you send an AI provider.</span>',
  cta: 'private',
  body: [
    { lead: 'Most businesses adopt AI tools faster than they read the terms attached to them. The answers are usually reassuring for paid business tiers and considerably less so for free consumer products — and the difference is where most accidental exposure happens.' },
    { h: 'The distinction that matters most' },
    { cards: [
      { t: 'Consumer products', d: 'Free and personal tiers of AI assistants. Historically the default has been that conversations may be used to improve the service. Settings exist to change this, and most staff have never opened them.' },
      { t: 'Business and API tiers', d: 'Paid business plans and developer APIs generally commit not to train on customer data by default, with defined retention periods. This is the tier your business data belongs on.' },
    ]},
    'The practical consequence: **an employee pasting a client contract into a free consumer assistant is a different risk from your system calling a business API.** The first is where real exposure occurs, and it is usually invisible to management until someone asks.',
    { h: 'Questions worth asking any provider' },
    { steps: [
      '**Is my data used for training?** For business tiers the answer should be no by default, not no if you find the right toggle.',
      '**How long is it retained, and where?** Retention periods and geography both matter — some regulated data cannot leave a jurisdiction.',
      '**Who can access it?** Provider staff access for abuse monitoring is common and usually reasonable; you should still know it exists.',
      '**What happens when I leave?** Deletion terms, and whether they extend to backups.',
      '**Sub-processors?** Providers often use other infrastructure companies. Your data may touch more organisations than the one you contracted with.',
      '**What certifications do they hold?** Independent audits are not a guarantee, but their absence is informative.',
    ]},
    { h: 'The categories that need more than terms' },
    'For some material, a good contract is not sufficient, either legally or reputationally:',
    { list: [
      '**Health information** — the strongest protections in most jurisdictions.',
      '**Legal files under privilege** — where sending to a third party raises questions beyond privacy.',
      '**Financial and tax records** held for clients.',
      '**Personal data of others** — where your obligations flow from data protection law rather than your own preference.',
      '**Trade secrets and unreleased work** — where the risk is commercial rather than regulatory.',
    ]},
    'For these, running the model on your own infrastructure removes the question entirely rather than managing it. [How that works in practice.](/run-ai-locally-business/)',
    { note: 'A policy most businesses should have and few do: a short written rule about what may and may not be pasted into external AI tools, and one approved tool for anything sensitive. The exposure almost never comes from a considered architectural decision. It comes from someone in a hurry with a document and a deadline.' },
  ],
  faq: [
    { q: 'Do AI companies train on my business data?', a: 'On paid business tiers and APIs, generally no by default, with contractual commitments to that effect. On free consumer tiers the position has historically been different, and settings that change it are off the beaten path. Read the terms for the specific tier you are using — the difference between tiers of the same product is larger than the difference between providers.' },
    { q: 'Is it safe to use AI with client information?', a: 'It depends on your obligations to that client and on which tier you use. Many professional service firms can use business-tier AI tools for client work under appropriate terms; some cannot, either because of regulation or because of what they promised in their own engagement letters. Check your professional obligations before your provider\'s terms — yours are usually stricter.' },
    { q: 'What is the safest option for sensitive material?', a: 'Running the model on infrastructure you control, so the data never leaves. That removes the third-party question entirely, at the cost of maintaining the system yourself. For most businesses the sensible pattern is a split: sensitive work local, everything else on a business-tier cloud service.' },
    { q: 'How do I stop staff pasting confidential material into AI tools?', a: 'A written policy plus a sanctioned alternative. Prohibition alone fails, because the tools are genuinely useful and people under deadline will use them anyway. Giving staff an approved tool that handles sensitive material properly is far more effective than a rule they will quietly route around.' },
  ],
  related: [
    ['/run-ai-locally-business/', 'Running AI locally'],
    ['/local-ai-vs-cloud-ai/', 'Local vs cloud, compared'],
    ['/private-ai-for-law-firms/', 'Private AI for law firms'],
  ],
},

{
  slug: 'private-ai-for-law-firms',
  title: 'Private AI for Law Firms — Using AI Without Sending Client Files Away',
  description: 'How law firms can use AI while keeping privileged material in-house: which tasks suit local models, the confidentiality questions to resolve first, and a realistic path to adoption.',
  keywords: 'AI for law firms, legal AI privacy, private AI legal, confidential AI law practice',
  eyebrow: 'Regulated sectors',
  short: 'Private AI · law firms',
  h1: 'AI in a law firm <span style="color:var(--grey-4);font-weight:300;">without sending files anywhere.</span>',
  cta: 'private',
  body: [
    { lead: 'The value of AI in legal work is obvious — summarising, searching, drafting, reviewing. The obstacle is equally obvious: the material is privileged, and sending it to a third party raises questions that a good privacy policy does not fully answer. Running the model in the firm removes the question rather than managing it.' },
    { note: '**This page is about technology, not professional obligations.** Confidentiality duties, privilege and the rules of your law society or bar govern what you may do, and they differ by jurisdiction. Resolve those first; the technical options below only matter afterwards.' },
    { h: 'Where AI genuinely helps in practice' },
    { list: [
      '**Summarising long documents.** Contracts, filings, discovery bundles, transcripts.',
      '**Searching your own precedents.** A model with access to the firm\'s history answers "have we done this before" in seconds instead of an afternoon.',
      '**First-draft correspondence** from a matter file, for a lawyer to review and correct.',
      '**Extracting structured data** — dates, parties, obligations, deadlines — from documents into a usable form.',
      '**Comparing versions** and surfacing what actually changed between drafts.',
    ]},
    { h: 'Why local matters more here than elsewhere' },
    'Privilege is not a privacy preference; it is a legal status that can be affected by disclosure to third parties. Whether and how transmitting material to a service provider affects privilege is a question for your jurisdiction and your regulator — but a system where nothing is transmitted does not raise it at all.',
    'There is also a client-relations dimension. "Our AI runs on our own servers and your file never leaves this firm" is a sentence clients understand immediately, and increasingly one that sophisticated clients ask for before it is offered.',
    { h: 'What a firm setup looks like' },
    { steps: [
      '**A machine in the firm** with enough memory to run a capable model — see [hardware requirements](/local-llm-hardware-requirements/).',
      '**A private index over your own documents**, so the model answers from your material rather than from general knowledge.',
      '**Access control tied to matter permissions.** The system must not let anyone query files they could not otherwise open — this is the requirement most commonly overlooked, and the one most likely to cause an incident.',
      '**An audit log.** Who asked what, and when. Both for supervision and for the conversation with your regulator.',
      '**A written policy** on what may be used with external AI tools, so the sanctioned system is the easy path rather than the obstacle.',
    ]},
    { h: 'The honest limitation' },
    'Local models are good at summarising, searching and drafting. They are not as strong as frontier cloud models at the hardest analytical reasoning, and none of them — local or cloud — should be trusted to state the law without verification. They produce fluent, confident text whether or not it is correct.',
    'The realistic value is in the hours returned on reading, searching and first drafts, with a lawyer reviewing everything. Any vendor promising more than that is selling something you should not buy.',
  ],
  faq: [
    { q: 'Can law firms use AI on privileged material?', a: 'That depends on your jurisdiction, your regulator and your engagement terms, and it is a question for professional advice rather than a technology vendor. What is clear is that a system where material never leaves the firm avoids the disclosure question entirely, which is why local deployment is the common answer where the analysis is uncertain.' },
    { q: 'Is a local model good enough for legal work?', a: 'For summarising, searching precedents, extracting structured information and producing first drafts — yes, with review. For complex analytical reasoning, frontier cloud models are stronger. No model of either kind should be relied on for legal conclusions without a lawyer verifying them; fluency is not accuracy.' },
    { q: 'What does it cost to set up?', a: 'Hardware capable of running a good model sits in the mid four figures, plus the work of indexing your documents and configuring access control properly. The access control and audit layer is usually the larger part of the project, and the part it is unwise to economise on.' },
    { q: 'How do we stop staff using consumer AI tools instead?', a: 'By making the sanctioned system genuinely easier to use than the alternative. Prohibition alone fails — the tools are useful and deadlines are real. A local system that is fast and integrated into how people already work removes the temptation far more reliably than a policy document.' },
  ],
  related: [
    ['/ai-data-privacy-business/', 'AI and your business data'],
    ['/run-ai-locally-business/', 'Running AI locally'],
    ['/private-ai-for-accountants/', 'Private AI for accountants'],
  ],
},

{
  slug: 'private-ai-for-accountants',
  title: 'Private AI for Accountants — Automating Without Exposing Client Financials',
  description: 'How accounting practices can use AI on client financial data while keeping it in-house: the tasks that pay back fastest, the confidentiality constraints, and a practical setup.',
  keywords: 'AI for accountants, accounting AI privacy, private AI accounting firm, financial data AI',
  eyebrow: 'Regulated sectors',
  short: 'Private AI · accountants',
  h1: 'AI in an accounting practice <span style="color:var(--grey-4);font-weight:300;">without exposing client financials.</span>',
  cta: 'private',
  body: [
    { lead: 'Accounting practices hold concentrated financial information about a great many businesses. That makes AI unusually valuable — the work is repetitive, document-heavy and rule-based — and unusually sensitive. Running the model in-house resolves the tension directly.' },
    { note: '**Professional obligations come first.** Confidentiality requirements from your professional body, and the terms of your engagement letters, govern what you may do with client data. This page describes what is technically possible, not what your standards permit.' },
    { h: 'Where the payback is fastest' },
    { list: [
      '**Document extraction.** Pulling figures, dates and parties out of invoices, receipts, statements and contracts into structured form. Repetitive, high volume, and exactly what these models do well.',
      '**Transaction classification.** Sorting entries into accounts, learning from how you have categorised similar items before.',
      '**Reconciliation support.** Surfacing likely matches and flagging what does not fit, for a human to resolve.',
      '**Drafting client correspondence** from a file — explanatory letters, queries, follow-ups.',
      '**Searching your own history.** "How did we treat this for a similar client" answered from your own files rather than memory.',
      '**Deadline and obligation tracking** extracted from documents rather than re-keyed.',
    ]},
    { h: 'Why in-house makes sense here' },
    'The concentration is the point. A single practice may hold detailed financial records for hundreds of businesses — turnover, margins, debts, disputes, salaries. That is a more attractive target and a more consequential exposure than any single business faces on its own.',
    'Sending that material to an external service may be permissible under the right terms; keeping it inside means the question of a provider breach, a terms change, or a sub-processor you did not evaluate simply does not arise.',
    { h: 'A realistic setup' },
    { steps: [
      '**One capable machine** in the practice — [sizing guidance here](/local-llm-hardware-requirements/).',
      '**Integration with your practice software**, so extracted data lands where it is used rather than in a separate silo.',
      '**Client-level access control.** Staff should only be able to query clients they work on, exactly as with your document system.',
      '**Human review on anything that affects a return or a set of accounts.** These models are fluent and occasionally confidently wrong — the review step is not optional.',
      '**An audit trail** of what was generated and by whom.',
    ]},
    { h: 'What it does not do' },
    'It does not exercise professional judgement, and it should not be trusted to apply tax law unverified. Its value is in the mechanical layer — reading, extracting, sorting, drafting — which happens to be where a large share of billable hours currently disappears. That is a substantial prize without needing to overstate it.',
  ],
  faq: [
    { q: 'Can accountants use AI with client data?', a: 'Subject to your professional body\'s confidentiality requirements and your engagement terms, generally yes — but the tier and terms matter. Many practices are comfortable with business-tier tools under appropriate contracts; others conclude that concentrated client financial data should not leave the practice. Running the model in-house makes that a settled question rather than a judgement call.' },
    { q: 'Which tasks pay back fastest?', a: 'Document extraction and transaction classification, by a wide margin. They are high-volume, repetitive, and currently consume junior hours that could go to work clients value more. Start there rather than with anything requiring judgement.' },
    { q: 'Is a local model accurate enough for financial documents?', a: 'For extracting figures and classifying transactions, yes — with verification. Treat it as a fast first pass that a person checks, not as an authority. The efficiency comes from reviewing extracted data rather than keying it, which is still a large saving.' },
    { q: 'What about during peak season?', a: 'Peak is when the volume argument is strongest — and when hardware capacity, rather than a per-request bill, becomes the constraint. Size the machine for your busiest month rather than your average one; the cost difference is smaller than the cost of a system that queues when you need it most.' },
  ],
  related: [
    ['/ai-data-privacy-business/', 'AI and your business data'],
    ['/private-ai-for-law-firms/', 'Private AI for law firms'],
    ['/ai-for-accountants/', 'AI for accounting practices'],
  ],
},

{
  slug: 'private-ai-for-healthcare',
  title: 'Private AI in Healthcare — Keeping Patient Information In-House',
  description: 'How healthcare providers can use AI without sending patient information to third parties: suitable administrative tasks, why local deployment fits regulated health data, and what to resolve first.',
  keywords: 'private AI healthcare, patient data AI privacy, local AI medical practice, health information AI',
  eyebrow: 'Regulated sectors',
  short: 'Private AI · healthcare',
  h1: 'AI in healthcare <span style="color:var(--grey-4);font-weight:300;">without patient data leaving.</span>',
  cta: 'private',
  body: [
    { lead: 'Health information carries the strongest legal protections of any data category in most jurisdictions, and the consequences of getting it wrong are proportionate. That makes healthcare both a natural fit for local AI and a domain where caution should outweigh enthusiasm.' },
    { note: '**Read this as a technology overview, not compliance guidance.** Health information is governed by specific legislation — the Health Information Privacy Code in New Zealand, HIPAA in the United States, and equivalents elsewhere — and by your professional obligations. Any AI deployment touching patient data needs review by people qualified in your jurisdiction. Nothing here substitutes for that.' },
    { h: 'Administrative tasks, not clinical ones' },
    'The defensible use cases are administrative. Clinical decision support is a regulated category in its own right, frequently subject to medical-device rules, and is not what a general-purpose language model on a practice server should be doing.',
    { list: [
      '**Clinical documentation.** Turning consultation notes into structured records for the clinician to review and sign off.',
      '**Correspondence.** Referral letters, summaries and routine communication drafted from the record.',
      '**Coding support.** Suggesting codes from documentation, verified by a person.',
      '**Administrative triage.** Sorting and routing incoming correspondence and requests.',
      '**Searching practice records** for a clinician who needs history quickly.',
      '**Transcription** of dictated notes, locally, without audio leaving the practice.',
    ]},
    { h: 'Why local deployment fits this domain' },
    'Health privacy regimes generally impose strict limits on disclosure to third parties, require specific agreements with any processor, and impose breach notification duties. Every external service in the chain is another agreement to negotiate, another party to assess, and another potential source of a notifiable breach.',
    'A model running on a server inside the practice, with no external connection, removes that chain. The obligations that remain — access control, storage security, audit, retention — are ones you already have systems and habits for.',
    { h: 'What must be in place' },
    { steps: [
      '**A privacy impact assessment** before deployment, not after. In several jurisdictions this is expected rather than optional for new processing of health information.',
      '**Access control matching clinical need-to-know.** The AI system must never become a route around the permissions in your patient record system.',
      '**Complete audit logging** of queries and outputs.',
      '**Clinician review of everything generated.** Documentation drafted by a model is a draft until a clinician verifies and signs it.',
      '**Retention and deletion rules** applying to prompts and outputs as much as to records.',
      '**Staff training** on what may be entered — including the explicit rule that consumer AI tools are not to be used with patient information.',
    ]},
    { h: 'The limitation that matters most' },
    'These models produce fluent text that is sometimes wrong, and in a clinical context fluency is actively dangerous because it is persuasive. Every output is a draft for a qualified person to verify. The value is in the time returned on documentation and administration — which is substantial, and is where clinician burnout largely originates — not in judgement.',
  ],
  faq: [
    { q: 'Is it legal to use AI with patient data?', a: 'It depends on your jurisdiction, the specific processing, and the safeguards in place — this needs assessment by someone qualified in your regulatory environment before any deployment. What local deployment changes is that no third-party disclosure occurs, which removes a substantial part of the analysis but not all of it.' },
    { q: 'Can AI write clinical notes?', a: 'It can produce a structured draft from a consultation, which a clinician then reviews, corrects and signs. That is a documentation aid. It is not a clinical record until a qualified person has verified it, and it should never be treated as one.' },
    { q: 'What about clinical decision support?', a: 'That is a separate regulatory category, often falling under medical device rules, and it is not an appropriate use of a general-purpose model deployed on a practice server. Keep AI use administrative unless you are working with a properly certified clinical system.' },
    { q: 'What hardware does a practice need?', a: 'A machine with enough memory to run a capable model — see [hardware requirements](/local-llm-hardware-requirements/) — plus secure storage and network configuration consistent with your existing health information systems. The infrastructure work is usually smaller than the governance work, and the governance work is the part that should not be rushed.' },
  ],
  related: [
    ['/ai-data-privacy-business/', 'AI and your business data'],
    ['/run-ai-locally-business/', 'Running AI locally'],
    ['/private-ai-for-law-firms/', 'Private AI for law firms'],
  ],
},

{
  slug: 'personal-ai-assistant',
  title: 'Building a Personal AI Assistant That Knows Your Work',
  description: 'What a genuinely personal AI assistant is, why one that knows your own files and history beats a general chatbot, how to build one that runs on your machine, and the honest limits.',
  keywords: 'personal AI assistant, private AI assistant, build own AI, AI that knows my files, personal LLM',
  eyebrow: 'Personal AI',
  short: 'Personal AI assistant',
  h1: 'A personal AI <span style="color:var(--grey-4);font-weight:300;">that actually knows your work.</span>',
  cta: 'private',
  body: [
    { lead: 'The AI assistants most people use are impressive and completely amnesiac about you. They know a great deal about the world and nothing about your clients, your projects, your correspondence or how you decided things last year. A personal assistant — one with access to your own material, running on your own machine — is a different and more useful thing.' },
    { h: 'What makes it personal' },
    { list: [
      '**It has read your material.** Your documents, notes, emails, past work. Not as training data, but as something it can search and cite when answering.',
      '**It remembers.** Context that persists between conversations, so you are not re-explaining your situation every time.',
      '**It knows your preferences.** How you write, what you care about, the decisions you have already made and do not want revisited.',
      '**It runs where your data is.** Which is what makes all of the above safe to do.',
    ]},
    { h: 'Why the last point is not optional' },
    'An assistant is only useful in proportion to what you let it see, and you can only let it see everything if nothing leaves. The two properties are linked: a genuinely useful personal assistant needs access to material you would not paste into a chat window, which means it has to run somewhere you control.',
    'This is the practical case for local AI, distinct from the ideological one. Not privacy for its own sake — privacy as the precondition for usefulness.',
    { h: 'How one is actually built' },
    { steps: [
      '**A local model** via [Ollama](/ollama-for-business/) on a machine with enough memory — [sizing here](/local-llm-hardware-requirements/).',
      '**An index over your own files.** Documents are split, converted to vectors and stored locally, so relevant passages can be retrieved and given to the model when you ask something. This is what lets it answer from your material rather than inventing.',
      '**A memory layer** — a simple store of facts and preferences that persist across sessions.',
      '**Connections to where you actually work.** Your notes, your calendar, your files, your email if you want it. Each connection increases usefulness and the care required.',
      '**An interface you will genuinely use.** A terminal, a chat window, a keyboard shortcut. Tools that require a detour get abandoned regardless of how good they are.',
    ]},
    { h: 'What it is good at, and what it is not' },
    { table: {
      minWidth: 520,
      head: ['Works well', 'Does not'],
      rows: [
        ['Answering from your own documents', 'Reasoning at the frontier level'],
        ['Drafting in your voice', 'Knowing anything after its training data'],
        ['Recalling decisions and context', 'Being reliably correct without checking'],
        ['Sorting, tagging, summarising', 'Replacing your judgement'],
      ],
    }},
    { note: 'The failure mode to design against is trust without verification. An assistant that knows your files will answer confidently about them, including when it has retrieved the wrong passage. Build it to cite what it used — the source, the file, the passage — so you can check in a second rather than assuming.' },
    { h: 'Where this is heading' },
    'The trajectory is toward assistants that are individual rather than shared: a system that has genuinely accumulated your context, that runs close to you, that does not reset. We think that is where useful AI ends up for most people, and we have written about why at more length in [our position on local and personal AI](/blog/future-of-ai-is-local-and-personal/).',
  ],
  faq: [
    { q: 'Can I build a personal AI assistant myself?', a: 'The components are available and reasonably approachable: Ollama for the model, an open-source vector store for your documents, and a few hundred lines to connect them. A technically comfortable person can have something useful running in a weekend. Making it reliable, secure and integrated into your daily work is the longer part.' },
    { q: 'How is this different from just using ChatGPT?', a: 'A general assistant knows the world; a personal one knows your work. The difference shows up in what you can ask — "what did we agree with this client in March" is answerable by one and not the other. It also means you can ask about material you would not paste into someone else\'s system.' },
    { q: 'Is it safe to give an AI access to all my files?', a: 'If it runs locally, the data does not leave your machine, and the remaining risk is who can query the system. That is a real question — an assistant with access to everything is a single point through which everything can be requested. Access control and honest thinking about what to include matter more here than in almost any other setup.' },
    { q: 'What hardware do I need?', a: 'A machine with 16GB of memory runs a small model adequately; 32GB or more is comfortable. For a personal assistant the responsiveness matters more than raw capability — a fast model you consult constantly is worth more than a slow one you avoid.' },
  ],
  related: [
    ['/run-ai-locally-business/', 'Running AI locally'],
    ['/ollama-for-business/', 'Ollama for business'],
    ['/local-ai-vs-cloud-ai/', 'Local vs cloud, compared'],
  ],
},

];
