/* Cold outreach craft — the pages someone reads before or while
 * running outbound. Every one answers a question people actually
 * type. No invented statistics anywhere: mechanisms, rules and
 * trade-offs only. */

export default [

{
  slug: 'cold-email-deliverability-checklist',
  title: 'Cold Email Deliverability Checklist — Everything to Fix Before You Send',
  description: 'The complete pre-send checklist for cold outreach: domain separation, SPF, DKIM, DMARC, warm-up, volume, content and list hygiene — in the order that actually matters.',
  keywords: 'cold email deliverability, email deliverability checklist, cold email spam folder, improve email deliverability',
  eyebrow: 'Deliverability',
  short: 'Deliverability checklist',
  h1: 'The deliverability checklist. <span style="color:var(--grey-4);font-weight:300;">In the order that matters.</span>',
  cta: 'product',
  body: [
    { lead: 'Most cold email failures are not writing failures. The message never got read because it never reached an inbox — and by the time you notice, the damage to your domain is already done. This is the full checklist, ordered by how much each item actually affects whether you land.' },
    { h: 'Before you send anything' },
    { steps: [
      '**Use a separate sending domain.** Not your main company domain. Something like `yourcompany-outreach.com`, about $12 a year. If deliverability ever degrades, your invoices, your client threads and your password resets are untouched. This single decision protects everything else you do by email.',
      '**Set up SPF, DKIM and DMARC on that domain.** Three DNS records your sending provider gives you. They prove the mail genuinely comes from you. Without them, a large share of what you send is filtered before a human sees it — and no amount of good writing compensates. See [SPF, DKIM and DMARC explained](/spf-dkim-dmarc-explained/).',
      '**Warm the domain up.** A brand-new domain sending fifty messages on day one looks exactly like a spammer, because that is what spammers do. Start at a handful a day and climb over two to four weeks. See [email warm-up explained](/email-warm-up-explained/).',
      '**Verify your list.** Sending to dead addresses produces bounces, and a high bounce rate is one of the fastest ways to get a domain flagged. Remove anything that does not resolve before the first send.',
    ]},
    { h: 'While you are sending' },
    { list: [
      '**Keep the volume low and the pace slow.** Twenty or so a day, spaced twenty to thirty minutes apart, inside working hours. Bursts are the signature of automation.',
      '**Send on weekdays only.** Weekend sending hurts reply rates and reads as machine-driven.',
      '**One message per company.** Emailing three people at the same business in the same week is how you get reported rather than answered.',
      '**Honour opt-outs immediately and permanently.** Not just for this campaign — forever, across every campaign. This is both a legal obligation in most countries and a reputation protection.',
      '**Watch bounces in real time.** A sudden rise means your list has gone stale or something broke. Stop and fix it rather than pushing through.',
    ]},
    { h: 'What is in the message itself' },
    { list: [
      '**A real, working reply address** that a human monitors.',
      '**Your actual identity** — name, business, and a way to verify you exist. Anonymous cold email is both less effective and, in most jurisdictions, unlawful.',
      '**A plain way to opt out.** One clear sentence beats a styled unsubscribe button that looks like bulk mail.',
      '**No link shorteners, no tracking pixels, minimal links.** Every one of those is a spam signal, and open-tracking pixels in particular are increasingly worthless since mail clients started pre-fetching them.',
      '**Plain text, or as close as you can get.** Heavy HTML templates are what marketing blasts look like. A cold email should look like a person wrote it, because one should have.',
    ]},
    { h: 'The order is the point' },
    'If you only do three things, do the first three: separate domain, authenticated records, slow warm-up. They account for most of the difference between landing and disappearing. Clever subject lines matter far less than people think, and matter not at all if the mail is filtered before delivery.',
    { note: 'A useful mental model: deliverability is a reputation score attached to your domain, built slowly and lost quickly. Everything on this list either builds it or protects it. Nothing on this list is about persuasion — that comes after you have earned the right to arrive.' },
  ],
  faq: [
    { q: 'How long before a new sending domain is ready for full volume?', a: 'Plan for two to four weeks of gradual increase. Start with a handful of messages a day and roughly double every few days, watching bounces and replies. Rushing this is the most common self-inflicted deliverability wound, and recovering a flagged domain takes far longer than warming one up properly.' },
    { q: 'Do I really need a separate domain, or is a subdomain enough?', a: 'A subdomain of your main domain shares some reputation with the parent, so problems can bleed across. A genuinely separate domain is the safer choice and costs about $12 a year. If you already send transactional mail from your main domain — invoices, receipts, password resets — treat that domain as something to protect rather than something to experiment with.' },
    { q: 'Why do my emails land in spam even though SPF and DKIM pass?', a: 'Authentication proves who sent the message, not that anyone wants it. If records pass and mail still lands in spam, the usual causes are: a cold domain with no sending history, volume that climbed too fast, a list with dead addresses producing bounces, content that looks like a marketing blast, or recipients marking earlier messages as spam. Work through those in that order.' },
    { q: 'Does open tracking hurt deliverability?', a: 'It can, and it has become close to useless anyway. Tracking pixels are an extra remote image request, some filters treat them as a signal, and privacy features in modern mail clients pre-fetch images automatically — which inflates open rates until they mean nothing. Replies are the only metric worth optimising for in cold outreach.' },
  ],
  related: [
    ['/spf-dkim-dmarc-explained/', 'SPF, DKIM and DMARC explained'],
    ['/email-warm-up-explained/', 'Email warm-up, explained'],
    ['/why-cold-emails-go-to-spam/', 'Why cold emails go to spam'],
    ['/how-many-cold-emails-per-day/', 'How many cold emails per day is safe'],
  ],
},

{
  slug: 'spf-dkim-dmarc-explained',
  title: 'SPF, DKIM and DMARC Explained — In Plain English, With Setup Steps',
  description: 'What SPF, DKIM and DMARC actually do, why cold email fails without them, how to set all three up, and how to check they are working. Written for people who are not system administrators.',
  keywords: 'SPF DKIM DMARC, email authentication, DMARC setup, SPF record, DKIM explained, email DNS records',
  eyebrow: 'Email authentication',
  short: 'SPF, DKIM, DMARC',
  h1: 'SPF, DKIM and DMARC, <span style="color:var(--grey-4);font-weight:300;">explained without the jargon.</span>',
  cta: 'product',
  body: [
    { lead: 'These three DNS records are the difference between your email arriving and your email vanishing. They are also the single most skipped step in cold outreach, usually because the names sound like something only a system administrator should touch. They are not.' },
    { h: 'The problem they solve' },
    'Email was designed in an era when nobody expected anyone to lie. Anyone can write any address in the "From" field, the same way you can write any return address on an envelope. That is why phishing works, and why receiving servers became deeply suspicious of mail they cannot verify.',
    'These three records are how you prove the mail is genuinely yours. They do not make your email good — they make it *verifiable*, which is the precondition for arriving at all.',
    { h: 'What each one does' },
    { cards: [
      { t: 'SPF — who is allowed to send', d: 'A list, published in your DNS, of the servers permitted to send email using your domain. The receiving server checks whether the mail came from one of them. Think of it as a guest list.' },
      { t: 'DKIM — proof it was not altered', d: 'A cryptographic signature added to each message, verifiable against a public key in your DNS. It proves the message genuinely came from your domain and was not tampered with in transit. Think of it as a wax seal.' },
      { t: 'DMARC — what to do on failure', d: 'Your instruction to receiving servers about what should happen when SPF or DKIM fails: allow it, quarantine it, or reject it. It also asks for reports, so you can see who is sending as you. Think of it as the policy.' },
    ]},
    { h: 'Setting them up' },
    { steps: [
      '**Get the records from your sending provider.** Every email service — Google Workspace, Microsoft 365, Zoho, Brevo, Postmark, Amazon SES — has a page that gives you the exact values. You are copying, not composing.',
      '**Add them to your domain\'s DNS.** In the registrar where you bought the domain, find DNS settings, and add each record with the exact type (TXT or CNAME), name and value given. Precision matters — a trailing space breaks it.',
      '**Wait for propagation.** Usually minutes, occasionally a few hours.',
      '**Verify in your provider\'s dashboard.** All three should show as verified. If any one does not, fix it before you send a single cold email — this is the step people skip and then wonder why nothing lands.',
    ]},
    { h3: 'A note on your DMARC policy' },
    'Start with `p=none`. That means "do not change how you handle failures, but send me reports". It lets you see what is happening without accidentally blocking your own legitimate mail. Once the reports are clean for a few weeks, move to `p=quarantine`, and later `p=reject` if you want the strongest protection.',
    { code: 'v=DMARC1; p=none; rua=mailto:dmarc@yourdomain.com' },
    { note: 'Going straight to `p=reject` before checking reports is the classic way to discover, painfully, that some system you forgot about — a CRM, an invoicing tool, a booking form — has been sending mail as you all along.' },
    { h: 'How to check it worked' },
    'Send a message to an address you control at a major provider, open it, and view the original or the message headers. You are looking for three lines showing `spf=pass`, `dkim=pass` and `dmarc=pass`. If all three pass, you are authenticated. Free tools like MXToolbox will also check your records from the outside.',
  ],
  faq: [
    { q: 'Can I send cold email without SPF, DKIM and DMARC?', a: 'Technically yes, practically no. Major providers treat unauthenticated bulk mail with heavy suspicion, and both Google and Yahoo have tightened requirements for anyone sending at volume. Without these records, a large share of your messages will be filtered regardless of how well written they are. The setup takes about twenty minutes.' },
    { q: 'What is the difference between SPF and DKIM?', a: 'SPF checks whether the sending server is on your approved list — it validates the route. DKIM checks a cryptographic signature on the message itself — it validates the content and origin. They fail in different situations, which is why you want both: forwarded mail often breaks SPF while DKIM survives.' },
    { q: 'My provider set these up automatically. Do I still need to check?', a: 'Yes. Many providers configure DKIM for you but leave SPF or DMARC to you, and some only complete setup after you confirm domain ownership. Open your provider dashboard and confirm all three read as verified. Assuming is how people end up sending unauthenticated for months.' },
    { q: 'Do these records help if I send from a shared platform?', a: 'They still apply, but on a shared sending platform you also inherit the reputation of everyone else using the same IP pool. That is one of the arguments for sending from your own domain and infrastructure — your reputation is yours, good or bad, rather than an average of strangers.' },
  ],
  related: [
    ['/cold-email-deliverability-checklist/', 'The full deliverability checklist'],
    ['/sending-domain-setup/', 'Setting up a sending domain'],
    ['/why-cold-emails-go-to-spam/', 'Why cold emails go to spam'],
  ],
},

{
  slug: 'how-many-cold-emails-per-day',
  title: 'How Many Cold Emails Per Day Is Safe? A Straight Answer',
  description: 'How many cold emails you can send per day without damaging your domain, why the safe number is lower than most tools suggest, how to scale up properly, and what actually gets domains flagged.',
  keywords: 'how many cold emails per day, cold email limits, safe cold email volume, cold email sending limits',
  eyebrow: 'Volume and pacing',
  short: 'Emails per day',
  h1: 'How many cold emails a day <span style="color:var(--grey-4);font-weight:300;">is actually safe?</span>',
  cta: 'product',
  body: [
    { lead: 'For an established domain with authentication in place, twenty to fifty a day per mailbox is a defensible range. For a new domain, start with five. Those numbers are lower than most tools imply, and the reason is worth understanding — because the cost of getting this wrong is not a bad campaign, it is a burnt domain.' },
    { h: 'Why the safe number is low' },
    'Receiving servers do not judge a single message. They judge a pattern: how much you send, how fast, how consistently, how many bounce, how many people complain, and how many reply. A domain sending five messages a day for a month and a domain sending a hundred and fifty on a Tuesday send the same volume — but only one of them looks like a business.',
    'The asymmetry matters. Building a good sending reputation takes weeks. Losing it takes an afternoon. And a flagged domain does not just hurt your outreach — if it is anywhere near your main domain, it hurts your invoices too.',
    { h: 'A schedule that works' },
    { table: {
      head: ['Week', 'Per day, per mailbox', 'What you are watching'],
      rows: [
        ['1', '5', 'Bounces. Anything above a couple of percent means list problems.'],
        ['2', '10 – 15', 'Whether replies arrive at all — proof you are landing.'],
        ['3', '20 – 30', 'Spam complaints. Any at all is a signal to slow down.'],
        ['4+', '30 – 50', 'Steady state. Most small businesses never need more.'],
      ],
    }},
    { h: 'Pace matters as much as volume' },
    'Twenty emails sent in four minutes and twenty emails spread across a working day are the same volume and completely different signals. Space them fifteen to thirty minutes apart, keep them inside business hours in the recipient\'s timezone, and send on weekdays only. A human writing twenty individual emails could not physically do it any faster — that is the shape you are imitating, because that is the shape that is not suspicious.',
    { h: 'If you need more volume' },
    'Add mailboxes or domains rather than pushing one harder. Ten mailboxes sending twenty a day is a far safer two hundred than one mailbox sending two hundred. This is exactly what large outbound teams do, and it is the point at which a managed platform with multi-inbox warm-up starts earning its subscription.',
    { note: 'Before adding volume, ask whether volume is the constraint. If a hundred well-researched emails produce nothing, a thousand produce nothing louder. Poor targeting scales badly, and the fix is upstream — in who you are writing to, not how many.' },
  ],
  faq: [
    { q: 'What happens if I send too many too fast?', a: 'The realistic outcomes, roughly in order: messages start landing in spam, then bounces climb as providers throttle you, then your domain accumulates a negative reputation that follows it. Recovery means stopping entirely, fixing the underlying cause, and warming up again slowly over weeks — or buying a new domain and starting over.' },
    { q: 'Do these limits apply per mailbox or per domain?', a: 'Both, and they interact. Individual mailboxes have provider limits, while reputation attaches largely to the domain. Running five mailboxes on one domain at fifty a day each means that domain is sending two hundred and fifty a day, and it will be judged on that total.' },
    { q: 'Is there a hard limit imposed by email providers?', a: 'Providers do publish sending caps, and those are real, but they are ceilings for all mail rather than guidance for cold outreach specifically. Staying under a provider limit tells you nothing about whether your reputation is healthy. The safe cold-email number is well below any published cap.' },
    { q: 'Should I send at the same time every day?', a: 'Roughly, but not exactly. A perfectly regular pattern — the same messages at the same second every day — is itself a machine signature. Some natural variation within business hours is both more human and slightly safer.' },
  ],
  related: [
    ['/email-warm-up-explained/', 'Email warm-up, explained'],
    ['/cold-email-deliverability-checklist/', 'The full deliverability checklist'],
    ['/cold-email-metrics-to-track/', 'The metrics worth tracking'],
  ],
},

{
  slug: 'email-warm-up-explained',
  title: 'Email Warm-Up Explained — What It Is, Whether You Need It, and How to Do It',
  description: 'What email warm-up actually does, why a new sending domain needs it, a realistic four-week schedule, and an honest look at whether automated warm-up services are worth paying for.',
  keywords: 'email warm up, domain warm up, cold email warm up, new sending domain, inbox warm up',
  eyebrow: 'Reputation',
  short: 'Email warm-up',
  h1: 'Email warm-up, <span style="color:var(--grey-4);font-weight:300;">and whether you actually need it.</span>',
  cta: 'product',
  body: [
    { lead: 'Warm-up means building a sending history gradually, so that receiving servers learn your domain belongs to a real business before you ask them to deliver anything at volume. A domain with no history sending fifty messages on day one is indistinguishable from a spammer — because that behaviour is exactly what spam looks like.' },
    { h: 'What is actually happening' },
    'Mail providers keep a reputation score for every sending domain. A new domain does not start neutral so much as unknown, and unknown is treated cautiously. Every message that gets delivered, opened and — best of all — replied to, nudges that score upward. Every bounce, every spam complaint, every message deleted unread nudges it down.',
    'Warm-up is simply the process of generating enough positive signal, slowly enough to be believable, that the score is healthy before real volume arrives.',
    { h: 'A four-week schedule' },
    { steps: [
      '**Week one, about five a day.** Send to people who will actually reply — colleagues, past clients, anyone who knows you. Replies are the strongest positive signal there is.',
      '**Week two, ten to fifteen.** Begin mixing in real prospects. Watch bounces closely; anything above a couple of percent means your list needs cleaning before you go further.',
      '**Week three, twenty to thirty.** Mostly real outreach now. Any spam complaint at all is a signal to hold at this level rather than climb.',
      '**Week four and beyond, thirty to fifty.** Steady state for a single mailbox. Most small businesses never need to exceed this.',
    ]},
    { note: 'Ask people you know to reply, not just to receive. A conversation — message, reply, reply back — is worth far more to your reputation than a message that simply lands and sits there.' },
    { h: 'Are automated warm-up services worth it?' },
    'These services put your mailbox into a network where accounts send and reply to each other automatically, generating artificial positive signal. Bundled into most subscription platforms, they are genuinely useful if you are running many mailboxes — doing that by hand does not scale.',
    'The honest caveat: providers are aware these networks exist and have become better at recognising the pattern of mail that is only ever exchanged inside a closed loop. It is a race, and it is not obviously one the warm-up networks are winning. For a single mailbox at moderate volume, a patient manual warm-up costs nothing and carries no risk of being classified as part of an artificial network.',
    { h: 'What warm-up cannot fix' },
    { list: [
      '**Missing authentication.** No amount of warm-up compensates for absent SPF, DKIM or DMARC.',
      '**A bad list.** Warming up and then sending to dead addresses undoes the work immediately.',
      '**Content people report.** If recipients mark your mail as spam, reputation falls faster than warm-up can raise it.',
      '**A domain that is already burnt.** Once a domain has a bad history, warming it up rarely works. Starting fresh usually does.',
    ]},
  ],
  faq: [
    { q: 'How long does warm-up take?', a: 'Two to four weeks for a new domain to reach normal outreach volume safely. Faster is possible and regularly ends badly. If a tool promises full volume within days, it is optimising for your impatience rather than your domain.' },
    { q: 'Do I need to warm up if I am using an established domain?', a: 'If the domain has been sending normal business email for years, it already has a reputation and needs far less. But if you are moving from ten messages a day to two hundred, that jump is itself the risk — ramp the increase over a couple of weeks even on an established domain.' },
    { q: 'Can I warm up and run a real campaign at the same time?', a: 'Yes, and it is usually the sensible approach: use the warm-up weeks to send your best-researched, most likely-to-reply prospects. Genuine replies are exactly the signal warm-up is trying to manufacture, so real outreach done slowly warms a domain better than artificial traffic does.' },
    { q: 'What if my domain is already flagged?', a: 'Stop sending, identify what caused it — usually volume, bounces or complaints — and fix that first. Then either warm up again over a longer period, or accept that a genuinely burnt domain is cheaper to replace than to rehabilitate. Twelve dollars for a fresh domain versus weeks of uncertain recovery is not a hard decision.' },
  ],
  related: [
    ['/how-many-cold-emails-per-day/', 'How many cold emails per day is safe'],
    ['/sending-domain-setup/', 'Setting up a sending domain'],
    ['/spf-dkim-dmarc-explained/', 'SPF, DKIM and DMARC explained'],
  ],
},

{
  slug: 'sending-domain-setup',
  title: 'How to Set Up a Cold Email Sending Domain (And Why Never Use Your Main One)',
  description: 'Choosing, buying and configuring a separate sending domain for cold outreach: naming that does not look like spam, the DNS records to add, and why this one decision protects your entire business email.',
  keywords: 'cold email sending domain, separate domain for cold email, secondary domain email, sending domain setup',
  eyebrow: 'Setup',
  short: 'Sending domain',
  h1: 'Setting up a sending domain. <span style="color:var(--grey-4);font-weight:300;">The cheapest insurance you will buy.</span>',
  cta: 'product',
  body: [
    { lead: 'Twelve dollars a year buys you a domain whose only job is cold outreach. If deliverability ever degrades — and over a long enough run, something eventually goes wrong — the damage stays there. Your invoices, your client threads, your password resets and your reputation with existing customers are untouched. There is no cheaper insurance in this business.' },
    { h: 'Why not just use your main domain' },
    'Because your main domain carries everything that matters. Quotes, contracts, invoices, booking confirmations, password resets. A deliverability problem there does not just mean prospects miss your pitch — it means a client does not receive an invoice, and you find out three weeks later when the payment is late.',
    'Cold outreach is inherently the riskiest mail you will ever send: to people who did not ask for it, at volume, from templates you are still refining. Keeping that traffic away from the domain your business depends on is basic separation of concerns.',
    { h: 'Choosing the name' },
    { list: [
      '**Stay recognisably related to your brand.** `yourcompany-outreach.com`, `yourcompanyhq.com`, `getyourcompany.com`, or the same name on a different extension. The recipient should be able to tell it is you.',
      '**Avoid anything that reads as disposable.** Random strings, heavy hyphenation, or novelty extensions cost you credibility with both humans and filters.',
      '**Prefer common extensions.** `.com`, `.co`, or your national extension. Some newer extensions carry a worse average reputation purely because of who else uses them.',
      '**Do not buy an expired domain to save time.** You inherit whatever history it has, and you cannot see that history before buying. A fresh domain with no reputation is safer than a cheap one with a bad one.',
    ]},
    { h: 'Configuring it' },
    { steps: [
      '**Buy the domain** at any registrar. This is a commodity — price is the only real difference.',
      '**Connect it to an email provider.** Google Workspace, Microsoft 365, Zoho and others all work. You need real mailboxes, not just a forwarding rule, so that replies arrive somewhere a human reads.',
      '**Add SPF, DKIM and DMARC.** Your provider gives you the exact values. This step is not optional — see [SPF, DKIM and DMARC explained](/spf-dkim-dmarc-explained/).',
      '**Set up forwarding to your real inbox,** so replies reach you without needing to check a second mailbox all day. Reply from the sending address, though, not your main one.',
      '**Warm it up before real volume.** A new domain needs two to four weeks of gradual sending — see [email warm-up explained](/email-warm-up-explained/).',
    ]},
    { h: 'One detail people miss' },
    'Put a real website on the sending domain, even a single page. It can simply redirect to your main site. A domain sending business email with nothing at all behind it is a small negative signal, and it looks odd to any recipient who types the address into a browser to check whether you are real — which is exactly what a careful prospect does.',
  ],
  faq: [
    { q: 'How many sending domains do I need?', a: 'One is enough for most small businesses at moderate volume. You add domains when you need more volume than a single domain can safely carry, or when you are running genuinely separate campaigns to different markets. Adding domains is the safe way to scale; pushing one domain harder is not.' },
    { q: 'Can I use a subdomain instead of a separate domain?', a: 'You can, and it is better than using your main domain directly, but subdomains share some reputation with the parent. For twelve dollars a year, full separation removes the question entirely.' },
    { q: 'Should the sending domain have its own website?', a: 'Yes, even a redirect to your main site. It costs nothing, removes a small negative signal, and satisfies the prospect who checks whether you exist before replying.' },
    { q: 'Do I reply from the sending domain or my main one?', a: 'Reply from the sending domain, so the conversation stays consistent and the thread history stays intact. Set up forwarding so you see replies without living in a second inbox. Once a conversation becomes a real client relationship, moving it to your main domain is natural.' },
  ],
  related: [
    ['/spf-dkim-dmarc-explained/', 'SPF, DKIM and DMARC explained'],
    ['/email-warm-up-explained/', 'Email warm-up, explained'],
    ['/cold-email-deliverability-checklist/', 'The full deliverability checklist'],
  ],
},

{
  slug: 'why-cold-emails-go-to-spam',
  title: 'Why Cold Emails Go to Spam — The Real Causes, in Order',
  description: 'The actual reasons cold email lands in spam, ranked by how often each one is the culprit: authentication, domain history, volume, list quality, content patterns and recipient behaviour.',
  keywords: 'why cold emails go to spam, cold email spam folder, emails landing in spam, avoid spam filter',
  eyebrow: 'Diagnosis',
  short: 'Why mail goes to spam',
  h1: 'Why your cold emails go to spam. <span style="color:var(--grey-4);font-weight:300;">Ranked by likelihood.</span>',
  cta: 'product',
  body: [
    { lead: 'When mail stops landing, most people start rewriting subject lines. That is almost always the wrong end of the problem. Here are the real causes, in the order you should check them — the first three account for the overwhelming majority of cases.' },
    { h: '1. Authentication is missing or broken' },
    'No SPF, no DKIM, no DMARC, or one of them silently failing after a DNS change. This is the most common cause by a wide margin, and it is entirely binary: either the records verify or they do not. Check your provider dashboard first, before touching anything else. [Full explanation here.](/spf-dkim-dmarc-explained/)',
    { h: '2. The domain has no history, or a bad one' },
    'A new domain sending at volume looks like a spammer. A domain that previously sent badly carries that history. Neither is fixed by better writing. New domains need [warming up](/email-warm-up-explained/); genuinely burnt domains are usually cheaper to replace than to rehabilitate.',
    { h: '3. Volume or pace' },
    'Too much, too fast, or in bursts. A hundred messages in ten minutes is a machine signature no content can disguise. [Safe volumes here.](/how-many-cold-emails-per-day/)',
    { h: '4. List quality' },
    'Dead addresses produce bounces, and bounce rate is a direct reputation input. Scraped lists that were never verified are the usual culprit. Worse: some old addresses become spam traps — dormant addresses specifically used to catch senders who did not verify their lists.',
    { h: '5. What the message looks like' },
    { list: [
      '**Heavy HTML, images, buttons.** These are the visual signature of bulk marketing. A cold email should look like a person typed it.',
      '**Link shorteners.** Strongly associated with hiding destinations. Use full URLs or none.',
      '**Too many links.** One is fine. Four looks like a campaign.',
      '**Large attachments** on a first contact — unusual, and treated with suspicion.',
      '**Spam-trigger phrasing.** Less decisive than folklore suggests, but stacking "free", "guarantee", "act now", "risk-free" and excessive capitals in one message still contributes.',
    ]},
    { h: '6. What recipients do' },
    'This is the one nobody controls directly and everyone underestimates. If people mark your mail as spam, delete it unread, or never reply, providers learn that mail from you is unwanted. Conversely, replies are the strongest positive signal available.',
    'Which leads somewhere uncomfortable but true: **badly targeted outreach is a deliverability problem, not just a conversion problem.** Writing to people with no plausible reason to care generates the exact behaviour that teaches providers to filter you.',
    { note: 'Diagnose in this order. It is tempting to start with the message because that is the part you enjoy editing, but if the cause is item one, you can rewrite forever and change nothing.' },
  ],
  faq: [
    { q: 'How do I know if my emails are going to spam?', a: 'Send test messages to addresses you control across several major providers and check where they land. Watch your reply rate over time — a sudden drop with no other change usually means placement changed. And use the free seed-testing tools that show inbox placement across providers, which is more reliable than guessing from silence.' },
    { q: 'Do certain words automatically trigger spam filters?', a: 'Not automatically, and the folklore around word lists is mostly outdated. Modern filters weigh many signals together, and authentication and reputation dominate. That said, stacking a lot of promotional language in one short message contributes alongside everything else — it is a small factor, not the main one.' },
    { q: 'Can one bad campaign ruin a domain permanently?', a: 'It can do lasting damage, especially on a young domain with little positive history to offset it. Recovery means stopping, fixing the cause, and rebuilding slowly over weeks. This is precisely the argument for a separate sending domain — so that the domain at risk is never the one carrying your invoices.' },
    { q: 'Does using a shared sending platform help or hurt?', a: 'It depends who else is on it. Shared IP pools mean you inherit an average of everyone using them — good if the platform polices its users strictly, bad if it does not. Sending from your own domain and infrastructure means your reputation is entirely yours, which is riskier if you are careless and better if you are not.' },
  ],
  related: [
    ['/cold-email-deliverability-checklist/', 'The full deliverability checklist'],
    ['/spf-dkim-dmarc-explained/', 'SPF, DKIM and DMARC explained'],
    ['/building-an-ideal-customer-profile/', 'Building an ideal customer profile'],
  ],
},

{
  slug: 'how-to-write-a-cold-email',
  title: 'How to Write a Cold Email That Gets Replies — Structure and Examples',
  description: 'A practical structure for cold emails that get answered: how to open without flattery, how to earn the ask, what length works, and the patterns that get messages deleted.',
  keywords: 'how to write a cold email, cold email template, cold email that gets replies, B2B cold email writing',
  eyebrow: 'Writing',
  short: 'Writing a cold email',
  h1: 'How to write a cold email <span style="color:var(--grey-4);font-weight:300;">that gets answered.</span>',
  cta: 'product',
  body: [
    { lead: 'A cold email is an interruption. The person did not ask for it, does not know you, and owes you nothing. Everything that follows comes from taking that seriously — not as an apology, but as a design constraint.' },
    { h: 'The structure' },
    { steps: [
      '**Open with something only true of them.** Not "I love what you are doing" — that is filler anyone could send to anyone. Something specific: a service they list, a job they posted, a recent piece of work, a gap you noticed on their site. This sentence is the entire proof that a person wrote to a person.',
      '**Connect it to a problem worth having.** One sentence. What that observation implies about their situation, stated without drama.',
      '**Say what you do, plainly.** One sentence, no jargon, no vision statement. If you cannot describe it in one line, the problem is upstream in your positioning.',
      '**Make the ask small.** Not "book a 30-minute discovery call". Ask a question they can answer in one line, or offer something concrete and low-commitment. The goal of a first email is a reply, not a sale.',
      '**Sign as a person.** Real name, real business, real reply address. No footer designed to look like a marketing department.',
    ]},
    { h: 'Length' },
    'Under 150 words. Ideally under 100. Long enough to be specific, short enough to read on a phone between two other things — which is where most first reads happen. Every sentence that does not earn its place makes the ones that do less likely to be read.',
    { h: 'What gets deleted' },
    { list: [
      '**Flattery openers.** "I came across your website and was really impressed" signals a template immediately, because it is one.',
      '**Your company story.** Nobody in a cold email cares when you were founded or what your mission is.',
      '**Unverifiable numbers.** "We increase revenue by 40%" from a stranger reads as noise. If you have a real, specific, checkable result, use it. If not, leave it out.',
      '**Multiple asks.** Book a call, reply, download this, follow us. One ask.',
      '**Fake familiarity.** "Just circling back" on a first email, or pretending you met. It is transparent and it costs you the benefit of the doubt.',
      '**Fake personalisation.** A merged company name in a template that is otherwise identical to a thousand others. People can tell, and it is worse than no personalisation because it reveals the deception.',
    ]},
    { h: 'The uncomfortable part' },
    'Most cold email fails before writing begins, in the choice of who to write to. A perfect message to someone with no plausible reason to care will not work. A clumsy message to someone with an urgent, relevant problem often will.',
    'If your reply rate is near zero, look at your targeting before your copy. [Building a real ideal customer profile](/building-an-ideal-customer-profile/) usually moves the number more than any rewrite.',
    { note: 'A test worth applying before sending: could this exact email be sent to any other company on your list without changing more than the name? If yes, it is not a cold email, it is a mail-out — and it will perform like one.' },
  ],
  faq: [
    { q: 'How long should a cold email be?', a: 'Under 150 words, ideally under 100. The first read almost always happens on a phone, quickly, between other tasks. Length competes directly with the chance of being read at all.' },
    { q: 'Should I personalise every email individually?', a: 'The opening line, yes — genuinely, not with a merged field. That single sentence is what separates a message from a mail-out. The rest can follow a consistent structure. Doing this by hand takes eight to twelve minutes per company, which is exactly why it gets abandoned and why automating the research is worth more than automating the sending.' },
    { q: 'What subject line should I use?', a: 'Short, lowercase, specific, and no promise the body does not keep. Two to five words that read like internal mail rather than marketing. Subject lines matter less than the folklore suggests and matter not at all if your mail is being filtered before delivery.' },
    { q: 'Should I include a link or attachment in the first email?', a: 'At most one link, and no attachments. Multiple links look like a campaign, and attachments from strangers are treated with suspicion by both filters and people. Save the detail for after they reply.' },
  ],
  related: [
    ['/cold-email-subject-lines/', 'Subject lines that get opened'],
    ['/cold-email-follow-up/', 'How to follow up without being annoying'],
    ['/personalisation-at-scale/', 'Personalisation at scale'],
    ['/building-an-ideal-customer-profile/', 'Building an ideal customer profile'],
  ],
},

{
  slug: 'cold-email-subject-lines',
  title: 'Cold Email Subject Lines — What Works, What Fails, and Why',
  description: 'What makes a cold email subject line get opened: the principles behind short lowercase specific lines, the patterns that read as marketing, and why subject lines matter less than most guides claim.',
  keywords: 'cold email subject lines, best subject lines cold email, email subject line examples B2B',
  eyebrow: 'Writing',
  short: 'Subject lines',
  h1: 'Subject lines. <span style="color:var(--grey-4);font-weight:300;">Less important than you have been told.</span>',
  cta: 'product',
  body: [
    { lead: 'Subject lines get more attention in outreach advice than any other element, and they deserve maybe a tenth of it. A great subject line on a message that lands in spam achieves nothing. A great subject line on an irrelevant message buys you an opening and a deletion. Get the first two right, then spend five minutes here.' },
    { h: 'The principles' },
    { list: [
      '**Short.** Two to five words. Long subject lines truncate on phones, which is where they are read.',
      '**Lowercase, or sentence case.** Title Case Reads As Marketing. lowercase reads as a colleague.',
      '**Specific to them.** Their company name, their city, their trade, the thing you noticed. Generic subjects get generic treatment.',
      '**No promise the body does not keep.** Curiosity gaps work once and cost you the relationship. "Quick question" when there is no question is a small lie that sets the tone for everything after.',
      '**No punctuation theatre.** Exclamation marks, all caps, emoji, [URGENT] brackets. All of it reads as bulk.',
    ]},
    { h: 'Patterns that tend to work' },
    'These are shapes rather than templates — fill them with something true, or leave them alone:',
    { cards: [
      { t: 'The observation', d: 'Reference the specific thing you noticed. "your quoting page" · "the Northland job". It proves the email is about them before it is opened.' },
      { t: 'The plain question', d: 'An actual question you actually ask in the body. "who handles quotes?" Only works if the body delivers it.' },
      { t: 'The bare noun', d: 'Just the topic. "after-hours quotes" · "boat surveys". Reads like internal mail, which is the point.' },
    ]},
    { h: 'Patterns that fail' },
    { list: [
      '**"Quick question"** with no question in the body. Overused to the point of being a template signature.',
      '**"Following up"** on a first contact. Manufactured familiarity, immediately transparent.',
      '**Anything with a number and a percentage.** "Increase revenue 40%" reads as an advertisement because it is one.',
      '**"Re:" prefixes on new threads.** This is a deception designed to look like an existing conversation. It works occasionally and permanently damages trust with everyone who notices — which is most people.',
    ]},
    { h: 'Why this matters less than you think' },
    'Open rates are close to unmeasurable now. Privacy features in mail clients pre-fetch tracking pixels automatically, inflating opens until the number means nothing. Optimising a metric you cannot measure is a poor use of attention.',
    '**Replies are the only number worth watching**, and replies are driven by relevance and timing far more than by the words above the message. If you have twenty minutes to improve outreach, spend fifteen on who you are writing to and five here.',
  ],
  faq: [
    { q: 'Should I use the recipient name in the subject line?', a: 'Usually not. It is a well-known merge-field pattern and reads as automated to anyone who has received outreach before. Their company name, or a specific detail about their work, is more convincing than their first name.' },
    { q: 'Do emoji in subject lines help or hurt?', a: 'In business-to-business cold email, they hurt. They read as consumer marketing, which is the category you are trying not to be sorted into.' },
    { q: 'Should I A/B test subject lines?', a: 'At small volumes, no — you will not reach statistical significance and will draw conclusions from noise. At small volumes the honest approach is to pick something plain and specific and put your effort into targeting. Testing becomes meaningful at volumes where each variant gets hundreds of sends.' },
    { q: 'What about no subject line at all?', a: 'It occasionally gets opened out of curiosity and often gets filtered, since missing subjects are a mild spam signal. The novelty is not worth the deliverability risk.' },
  ],
  related: [
    ['/how-to-write-a-cold-email/', 'How to write a cold email'],
    ['/cold-email-metrics-to-track/', 'The metrics worth tracking'],
  ],
},

{
  slug: 'cold-email-follow-up',
  title: 'Cold Email Follow-Up — How Many, How Often, and When to Stop',
  description: 'How to follow up on cold email without becoming a nuisance: how many messages, spacing, what each one should add, and the honest case for stopping earlier than most advice suggests.',
  keywords: 'cold email follow up, follow up sequence, how many follow ups, cold email cadence',
  eyebrow: 'Sequencing',
  short: 'Following up',
  h1: 'Following up <span style="color:var(--grey-4);font-weight:300;">without becoming the person they mute.</span>',
  cta: 'product',
  body: [
    { lead: 'Most replies to cold outreach do not come from the first message. That fact is used to justify seven-step sequences that pester people into silence. The useful version is narrower: two follow-ups, each adding something, then stop.' },
    { h: 'The shape' },
    { table: {
      head: ['Message', 'Timing', 'What it does'],
      rows: [
        ['First', 'Day 0', 'The specific observation, the plain ask.'],
        ['Second', 'Day 4 – 5', 'Adds something new — an example, a relevant detail. Not "just bumping this".'],
        ['Third', 'Day 12 – 14', 'Short, closes the loop, makes it easy to say no or to come back later.'],
      ],
    }},
    { h: 'The rule that matters' },
    '**Every follow-up must add something.** A message whose entire content is "checking in" or "bumping this to the top of your inbox" tells the recipient that you value their attention less than your pipeline. It is also the most common reason people mark outreach as spam — which damages your domain, not just that conversation.',
    'Things that legitimately add something: a specific example relevant to their situation, a piece of work you have just published, a change in their circumstances you noticed, a genuinely useful observation. Things that do not: your enthusiasm, the passage of time, a third restatement of your offer.',
    { h: 'The last message' },
    'Close honestly rather than with manufactured scarcity. Something close to: *"I will leave it here — if this becomes relevant later, my details are below."*',
    'This does two things. It respects the person, which occasionally produces a reply on its own from people who appreciate not being chased. And it leaves the door genuinely open, which matters because timing is the largest uncontrollable factor in outreach. The prospect who ignored you in July may have an urgent problem in November.',
    { note: 'Avoid the "breakup email" that performs disappointment — *"I guess this is not a priority for you"*. It is a manipulation, most people recognise it, and it converts a neutral non-response into a negative impression.' },
    { h: 'When to stop entirely' },
    { list: [
      '**They said no.** Thank them and remove them. A no honoured well is worth more than a maybe extracted badly.',
      '**They asked not to be contacted.** Permanently, across every campaign, forever. In most jurisdictions this is also a legal obligation.',
      '**Three messages with no response.** Silence is an answer. Continuing past it converts indifference into irritation.',
      '**The email bounced.** Remove the address rather than retrying — repeated bounces damage your sending reputation directly.',
    ]},
  ],
  faq: [
    { q: 'How many follow-ups should I send?', a: 'Two after the initial message, so three in total. Longer sequences do produce marginally more replies in aggregate, but they also produce more spam complaints — and complaints damage the domain that carries all your future outreach. The trade is rarely worth it for a small business.' },
    { q: 'Should follow-ups be in the same email thread?', a: 'Yes. It gives the recipient context without re-explaining, keeps your inbox coherent, and reads more like normal correspondence than a new campaign message.' },
    { q: 'What if they open but never reply?', a: 'Treat it as no signal at all. Open tracking is unreliable now that mail clients pre-fetch images automatically, and acting on inflated open data leads to chasing people who never actually read anything. Replies are the only trustworthy signal.' },
    { q: 'Can I contact someone again months later?', a: 'If they never asked you to stop, yes — a genuinely new reason to write, months later, is legitimate outreach rather than a continuation of the old sequence. If they said no or asked not to be contacted, that is permanent regardless of how much time passes.' },
  ],
  related: [
    ['/how-to-write-a-cold-email/', 'How to write a cold email'],
    ['/cold-email-metrics-to-track/', 'The metrics worth tracking'],
    ['/cold-email-mistakes/', 'The mistakes that cost the most'],
  ],
},

{
  slug: 'personalisation-at-scale',
  title: 'Personalisation at Scale — Why Merge Fields Are Not Personalisation',
  description: 'What genuine personalisation in cold outreach requires, why merge tags fail, how AI changes the economics of research, and the line between researched and creepy.',
  keywords: 'email personalisation at scale, personalised cold email, AI cold email personalisation, merge tags',
  eyebrow: 'Method',
  short: 'Personalisation at scale',
  h1: 'Personalisation at scale. <span style="color:var(--grey-4);font-weight:300;">Merge fields do not count.</span>',
  cta: 'product',
  body: [
    { lead: 'Inserting a company name into an otherwise identical template is not personalisation. It is a template with a hole in it, and recipients recognise the shape immediately — often faster than they would have spotted a message that made no attempt at all. Fake personalisation is worse than none, because it reveals that you tried to seem attentive without being it.' },
    { h: 'What genuine personalisation requires' },
    'One sentence that could only have been written to that specific company, demonstrating that someone looked. That is the whole standard.',
    { list: [
      'A service they list that is unusual for their trade.',
      'A job posting that reveals what they are struggling to cover.',
      'A piece of work, a project, a recent launch.',
      'Something visibly missing or broken — a booking widget that fails, prices published as an image, no mobile layout.',
      'A constraint of their market you actually understand.',
    ]},
    { h: 'Why it gets abandoned' },
    'Because doing it properly takes eight to twelve minutes per company — not for the writing, but for the reading that makes the writing possible. At twenty companies a day that is roughly three hours, every day, before anything else happens.',
    'Almost nobody sustains that. So outreach gets done in panicked bursts with generic copy, produces nothing, and gets abandoned entirely. The gap between what works and what people actually do is a time problem, not a knowledge problem.',
    { h: 'What changes with AI, and what does not' },
    'A language model can read a company\'s public pages and write a specific opening line in seconds rather than minutes. That genuinely collapses the cost of the research step, which is the step that made personalisation unaffordable.',
    'What it does not change:',
    { list: [
      '**Targeting.** A model writing beautifully to the wrong list produces well-written failure. Who you write to still dominates the outcome.',
      '**The truth requirement.** A model asked to be enthusiastic will produce plausible flattery. Constrain it to observations it can point to on the page, or it will invent things and you will send them.',
      '**Judgement about what matters.** Knowing that a missing booking system costs a winery more than a dated colour scheme is domain knowledge you supply.',
    ]},
    { note: 'A practical safeguard: before any batch goes out, compare every message against every other one. If two share so much as a six-word sequence, something has collapsed into a template and the batch needs rewriting. This is the difference between a hundred individual emails and one email sent a hundred times.' },
    { h: 'The line you should not cross' },
    'Personal life, family, health, anything from a personal social account, anything they did not publish in a professional context. It is unsettling, it damages you the moment it is noticed, and in jurisdictions with privacy legislation it can also be unlawful.',
    'The test is simple: **would you be comfortable if they asked how you knew that?** Public business information passes. Anything else does not.',
  ],
  faq: [
    { q: 'Can AI write personalised cold emails that do not sound artificial?', a: 'Yes, when constrained properly: give it the company\'s own published material, require it to reference something specific from that material, forbid flattery and superlatives, and check output for repeated phrasing across the batch. Left unconstrained, it produces confident, generic, slightly enthusiastic text that reads exactly like what it is.' },
    { q: 'How much personalisation is enough?', a: 'One genuinely specific sentence, usually the opener. The rest can follow a consistent structure without harm. The purpose is to demonstrate that a person considered this company — one true sentence does that, and five paragraphs of research does not do it five times better.' },
    { q: 'Is it obvious when a cold email is automated?', a: 'It is obvious when it is generic, which is not the same thing. A message that references something real about the business reads as human whether a person or a machine assembled it. A message that could have been sent to anyone reads as automated even if someone typed it by hand.' },
    { q: 'What information is acceptable to use?', a: 'Anything the business published about itself in a professional context: their website, their services, their job listings, their public work, their business social accounts. Not personal accounts, not personal circumstances, not data from breaches or scraped personal profiles. If you would be uncomfortable explaining how you found it, do not use it.' },
  ],
  related: [
    ['/how-to-write-a-cold-email/', 'How to write a cold email'],
    ['/finding-business-emails-ethically/', 'Finding business emails ethically'],
    ['/building-an-ideal-customer-profile/', 'Building an ideal customer profile'],
  ],
},

{
  slug: 'finding-business-emails-ethically',
  title: 'How to Find Business Email Addresses — Ethically and Accurately',
  description: 'Where business contact details legitimately come from, how to verify them before sending, which sources create legal and reputational risk, and why list quality decides your deliverability.',
  keywords: 'find business email addresses, B2B email list building, email finder, verify email addresses, lead sourcing',
  eyebrow: 'Sourcing',
  short: 'Finding business emails',
  h1: 'Finding business emails <span style="color:var(--grey-4);font-weight:300;">without buying a problem.</span>',
  cta: 'product',
  body: [
    { lead: 'Where your list comes from determines your bounce rate, your spam complaints, your legal exposure and ultimately your domain reputation. It is the least glamorous part of outbound and the one that most reliably decides whether any of it works.' },
    { h: 'Sources that hold up' },
    { list: [
      '**The company website.** Contact pages, team pages, service pages. Published deliberately for people to make contact — which is exactly what you are doing.',
      '**Business directories and trade associations.** Industry bodies, chambers of commerce, licensing registers. Businesses list themselves there specifically to be found.',
      '**Company registers.** Public filings in most countries include registered contact details.',
      '**Job listings.** Often name a hiring contact, and reveal what the business is currently struggling to cover — useful for both reaching and understanding them.',
      '**Professional networks,** used within their terms of service. Read those terms; automated scraping is generally prohibited and enforced.',
    ]},
    { h: 'Sources that create problems' },
    { list: [
      '**Purchased lists.** Stale, unverified, frequently containing spam traps, and the seller usually cannot tell you where the data came from. Bounce rates from bought lists are the fastest route to a flagged domain.',
      '**Data from breaches.** Unlawful in essentially every jurisdiction, regardless of how it is packaged or resold.',
      '**Scraped personal profiles.** Personal email addresses and personal social data carry the strongest privacy protections and the weakest business justification.',
      '**Guessed addresses at volume.** Pattern-guessing `firstname@company.com` and firing at all variants produces bounces and hits catch-all traps. Verification exists precisely so you do not have to guess.',
    ]},
    { h: 'Verification is not optional' },
    'Every address should be checked before it is sent to. Verification services confirm that a mailbox exists without sending anything, and they cost very little relative to the damage a high bounce rate does.',
    { steps: [
      '**Remove anything that does not resolve.** Non-existent addresses bounce, and bounce rate feeds directly into reputation.',
      '**Treat catch-all domains carefully.** These accept everything, so verification cannot confirm a real mailbox. Send to them sparingly, or find a named contact instead.',
      '**Drop role addresses for cold outreach** — `info@`, `sales@`, `admin@`. They are frequently monitored by several people, ignored, or configured as complaint traps. A named person is both more effective and safer.',
      '**Re-verify old lists.** Contact data decays quickly as people change roles. A list gathered six months ago is not the list you have today.',
    ]},
    { h: 'The part that matters legally' },
    'Sourcing rules differ by jurisdiction and are stricter than most outreach advice admits. In the European Union and the United Kingdom, personal data — which includes named business email addresses — falls under data protection law, and you need a lawful basis plus, in practice, a privacy notice explaining where you got it. Australia\'s Privacy Act limits using data for purposes other than why it was collected. New Zealand and the United States are more permissive for business-to-business contact but still require genuine sender identity and a working opt-out.',
    'Country-by-country detail: [New Zealand](/cold-email-law-new-zealand/) · [Australia](/cold-email-law-australia/) · [United States](/cold-email-law-united-states/) · [EU and GDPR](/cold-email-law-europe-gdpr/) · [United Kingdom](/cold-email-law-united-kingdom/).',
    { note: 'A reliable filter that keeps you out of most trouble: **would this business be surprised that you have this address?** A contact address published on their own website, no. A personal address obtained from a data broker, yes — and that surprise is what complaints are made of.' },
  ],
  faq: [
    { q: 'Is it legal to scrape business emails from websites?', a: 'It depends on jurisdiction and on what you scrape. Publicly published business contact details are generally acceptable for business-to-business contact in New Zealand, Australia and the United States, subject to identification and opt-out rules. In the EU and UK, named business addresses are personal data and require a lawful basis and transparency about the source. Automated scraping may also breach a site\'s terms of service independently of privacy law.' },
    { q: 'Should I use email finder tools?', a: 'The reputable ones aggregate public sources and verify deliverability, which is legitimate and saves real time. What matters is where their data comes from — a provider that cannot tell you is one whose data you should not use. Verify anything they give you before sending regardless.' },
    { q: 'What bounce rate is acceptable?', a: 'Under two percent. Above that, providers begin treating you as someone sending to an unverified list, which is exactly what is happening. If a campaign starts bouncing heavily, stop it rather than letting it run — every additional bounce compounds the damage.' },
    { q: 'Are role addresses like info@ worth contacting?', a: 'Rarely, for cold outreach. They are often monitored by several people, frequently ignored, and sometimes configured specifically to catch unsolicited mail. A named person at the same company is more likely to reply and less likely to generate a complaint.' },
  ],
  related: [
    ['/building-an-ideal-customer-profile/', 'Building an ideal customer profile'],
    ['/cold-email-law-new-zealand/', 'Cold email law in New Zealand'],
    ['/why-cold-emails-go-to-spam/', 'Why cold emails go to spam'],
  ],
},

{
  slug: 'building-an-ideal-customer-profile',
  title: 'Building an Ideal Customer Profile That Actually Improves Outreach',
  description: 'How to define an ICP specific enough to change your results: the difference between a segment and a profile, the signals worth filtering on, and why vague targeting produces well-written failure.',
  keywords: 'ideal customer profile, ICP definition, B2B targeting, customer profile template, lead qualification',
  eyebrow: 'Targeting',
  short: 'Ideal customer profile',
  h1: 'The ideal customer profile. <span style="color:var(--grey-4);font-weight:300;">Where outreach is actually won.</span>',
  cta: 'product',
  body: [
    { lead: 'If your reply rate is near zero, the copy is probably not the problem. Writing well to people with no reason to care produces well-written failure. Almost everything that determines whether outbound works is decided before a word is written, in who ends up on the list.' },
    { h: 'A segment is not a profile' },
    '"Marine businesses in New Zealand" is a segment. It tells you where to look and nothing about who to write to. "Independent boatbuilders in Northland with fewer than fifteen staff, no online booking, and a backlog long enough that they turn work away" is a profile. It tells you what to say, what to offer, and — crucially — who to leave out.',
    'The difference shows up immediately in the writing. Against a segment you can only write generalities. Against a profile you can write the specific sentence that makes someone reply.',
    { h: 'What to define' },
    { steps: [
      '**The trigger.** What has to be true right now for this to be worth their attention? A backlog, a hire they cannot fill, a season starting, a system visibly failing. Outreach without a trigger is a solution looking for a moment.',
      '**The constraint.** What is stopping them solving it themselves? No time, no technical person, a tool they already pay for that does not do this. This is usually where your actual value sits.',
      '**The size band.** Too small and there is no budget. Too large and you are talking to someone who cannot decide. Both ends waste the same effort as a wrong industry.',
      '**The decision-maker.** In a business of eight people it is the owner. At two hundred it is a manager with a budget and a boss. The same message cannot address both.',
      '**The disqualifiers.** Explicit reasons to skip a company. This is the most valuable list and the one nobody writes down.',
    ]},
    { h: 'Where the profile comes from' },
    'From customers you already have, if you have any. Look at who bought fastest, who was easiest to serve, who paid without friction, and who is still around. Then find what those have in common that is *observable from outside* — because a criterion you cannot check on a company\'s website cannot be used to build a list.',
    'If you have no customers yet, the profile is a hypothesis. Write it down anyway, send to a small batch, and revise it based on who replies. The people who answer are telling you what your profile actually is, which is usually not what you assumed.',
    { h: 'The test' },
    'Take your profile and apply it to twenty real companies. If you cannot confidently include or exclude each one in under a minute using only their public information, the profile is too vague to build a list from — and too vague to write a specific email from.',
    { note: 'The most common failure is a profile that describes an industry rather than a situation. "Restaurants" is an industry. "Restaurants that just opened a second location and are still doing rosters on paper" is a situation — and the second one writes its own opening line.' },
  ],
  faq: [
    { q: 'How narrow should an ideal customer profile be?', a: 'Narrow enough that you could write a genuinely different email to this group than to any other, and broad enough that enough companies exist to build a list. If your profile matches thirty companies in your market, it is a niche worth serving personally rather than a segment worth automating. If it matches thirty thousand, it is not a profile.' },
    { q: 'Can I have more than one ICP?', a: 'Yes, and running two or three separate campaigns against separate profiles works well. What does not work is merging them into one campaign with one message — the message ends up written for an average buyer who does not exist.' },
    { q: 'How do I know if my profile is wrong?', a: 'The replies tell you. If the people answering share a characteristic your profile does not mention, add it. If a group you targeted heavily never answers, remove them. Treat the first hundred sends as research, because that is what they are.' },
    { q: 'Does a tighter profile mean fewer prospects and less revenue?', a: 'Fewer prospects, usually more revenue. A hundred well-matched companies with a real trigger outperform a thousand vaguely relevant ones, and they cost less to reach — in sending volume, in domain risk, and in the hours spent writing to people who were never going to answer.' },
  ],
  related: [
    ['/finding-business-emails-ethically/', 'Finding business emails ethically'],
    ['/how-to-write-a-cold-email/', 'How to write a cold email'],
    ['/b2b-lead-generation-small-business/', 'B2B lead generation for small businesses'],
  ],
},

{
  slug: 'cold-email-metrics-to-track',
  title: 'Cold Email Metrics That Matter — And the Ones to Ignore',
  description: 'Which cold outreach numbers are worth watching: why open rates have become meaningless, what reply and positive-reply rates tell you, and the deliverability metrics that warn you before damage is done.',
  keywords: 'cold email metrics, email open rate meaningless, reply rate benchmark, cold email KPIs',
  eyebrow: 'Measurement',
  short: 'Metrics that matter',
  h1: 'The numbers worth watching. <span style="color:var(--grey-4);font-weight:300;">And the ones lying to you.</span>',
  cta: 'product',
  body: [
    { lead: 'Outreach dashboards are full of metrics that look like progress. Two of them tell you whether the thing is working, three warn you before you damage your domain, and the most prominently displayed one is close to fiction.' },
    { h: 'Ignore open rate' },
    'Modern mail clients pre-fetch remote images automatically to protect privacy, which means tracking pixels fire whether or not a human ever saw the message. Some corporate security systems open every link and image in incoming mail as a matter of policy.',
    'The result is an open rate inflated by an unknown amount, varying by recipient, that you cannot correct for. Optimising against it means optimising against noise — and worse, it produces false confidence: a campaign showing sixty percent opens and zero replies looks like a copy problem when it is usually a targeting problem or a deliverability problem.',
    { h: 'Watch these two' },
    { cards: [
      { t: 'Reply rate', d: 'Replies divided by messages delivered. Unfakeable, unaffected by tracking changes, and directly connected to the only thing outreach exists to produce. This is your primary number.' },
      { t: 'Positive reply rate', d: 'Replies that express actual interest, as a share of all replies. A campaign generating many replies that are all "no thanks" is reaching people successfully and targeting them badly — a distinction reply rate alone hides.' },
    ]},
    { h: 'And these three, as warnings' },
    { table: {
      head: ['Metric', 'Healthy', 'What it means when it moves'],
      rows: [
        ['Bounce rate', 'Under 2%', 'Rising means your list is stale or unverified. Stop and clean it — bounces damage reputation directly.'],
        ['Spam complaints', 'Effectively zero', 'Any at all means slow down and re-read who you are contacting. This is the fastest way to lose a domain.'],
        ['Unsubscribe / opt-out', 'Low and stable', 'A spike means your targeting has drifted to people with no reason to hear from you.'],
      ],
    }},
    { h: 'What good looks like' },
    'Published benchmarks for cold email reply rates vary so widely between sources, industries and definitions that quoting a number would be misleading. What is more useful is the direction and the diagnosis:',
    { list: [
      '**Replies near zero, deliverability fine** — targeting problem. Rebuild the [ideal customer profile](/building-an-ideal-customer-profile/).',
      '**Replies near zero, deliverability unknown** — check deliverability first. You may not be arriving at all.',
      '**Replies healthy, positive replies near zero** — you are reaching the right people with the wrong offer, or the right offer at the wrong moment.',
      '**Replies healthy, then falling with nothing changed** — deliverability is degrading. Check [why mail goes to spam](/why-cold-emails-go-to-spam/) before rewriting anything.',
    ]},
    { note: 'Measure against yourself over time, not against benchmarks from someone else\'s market. Your own trend line, tracked honestly, is worth more than any published average.' },
  ],
  faq: [
    { q: 'Why is open rate unreliable?', a: 'Open tracking works by embedding an invisible image that loads when the message is displayed. Privacy features in modern mail clients now pre-fetch those images automatically, and many corporate security systems scan every incoming message by opening its contents. Both fire the pixel with no human involved, inflating the number by an amount you cannot measure or correct.' },
    { q: 'What reply rate should I expect?', a: 'Published figures vary enormously depending on industry, offer, list quality and how "reply" is defined, so any single number quoted as a benchmark is close to meaningless. Track your own rate over time and judge changes against your own baseline. A campaign that doubles your previous rate is good news regardless of what someone else reports.' },
    { q: 'Should I track link clicks?', a: 'They are more reliable than opens, since a click usually requires intent — but security scanners do click links automatically, so the number is not clean either. In cold outreach, where you should be including at most one link, clicks are a weak signal compared with replies.' },
    { q: 'How long before I can judge a campaign?', a: 'At twenty messages a day, give it two to three weeks and at least a couple of hundred sends before drawing conclusions. Judging a campaign on thirty messages means reading noise. If deliverability metrics go wrong, however, act immediately — those do not need statistical significance.' },
  ],
  related: [
    ['/cold-email-deliverability-checklist/', 'The full deliverability checklist'],
    ['/building-an-ideal-customer-profile/', 'Building an ideal customer profile'],
    ['/cold-email-mistakes/', 'The mistakes that cost the most'],
  ],
},

{
  slug: 'cold-email-vs-linkedin-outreach',
  title: 'Cold Email vs LinkedIn Outreach — An Honest Comparison',
  description: 'Where cold email beats LinkedIn outreach and where it does not: reach, cost, platform risk, automation limits, and how the two work together rather than competing.',
  keywords: 'cold email vs linkedin, linkedin outreach, best outreach channel B2B, linkedin vs email prospecting',
  eyebrow: 'Channels',
  short: 'Email vs LinkedIn',
  h1: 'Cold email or LinkedIn? <span style="color:var(--grey-4);font-weight:300;">They answer different questions.</span>',
  cta: 'product',
  body: [
    { lead: 'These are usually presented as rivals. They are better understood as tools with different failure modes — and the decision is less about which converts better than about which one you can still be using in a year.' },
    { h: 'The comparison' },
    { table: {
      minWidth: 620,
      head: ['', 'Cold email', 'LinkedIn'],
      rows: [
        ['Who you can reach', 'Anyone with a business address', 'Only people active on the platform'],
        ['Who owns the channel', 'You — your domain, your list', 'The platform. Access can be limited or removed'],
        ['Automation', 'Legitimate, within volume and legal limits', 'Against platform terms; accounts get restricted'],
        ['Cost at volume', 'Domain plus sending, near-flat as you grow', 'Premium tiers, priced per seat'],
        ['Message length', 'As long as needed', 'Short, and connection requests shorter still'],
        ['Trade coverage', 'Strong — most businesses have email', 'Weak in trades, hospitality, manufacturing'],
      ],
    }},
    { h: 'Where LinkedIn genuinely wins' },
    { list: [
      '**Sectors that live on it.** Software, consulting, recruitment, finance, marketing. If your buyer checks it daily, a well-judged message there gets seen faster than email.',
      '**Warm context.** Shared connections, a group in common, a post they wrote. That context is visible and usable in a way it is not in email.',
      '**Research.** Even if you never send a message there, it is the best source for understanding who does what inside a company.',
      '**Low commitment.** A connection request is a smaller ask than an email, which suits long sales cycles where you are building familiarity over months.',
    ]},
    { h: 'Where cold email wins' },
    { list: [
      '**Reach.** An electrician in Whangārei, a boatbuilder in Northland, a winery on Waiheke — all have email; many have no meaningful platform presence.',
      '**You own it.** Your domain and your list cannot be restricted by a policy change. Anyone who has had an account limited understands what that is worth.',
      '**It scales legitimately.** Automating email within volume and legal limits is normal practice. Automating platform outreach violates the terms of service, and enforcement has become aggressive.',
      '**Room to be specific.** A connection request gives you a sentence. An email gives you a paragraph — enough to show you understood their situation.',
    ]},
    { h: 'The honest recommendation' },
    'If your buyers are on the platform, use both: research and warm signal there, the substantive approach by email. If your buyers are trades, hospitality, marine, manufacturing or most local businesses, email is not the better channel — it is close to the only one.',
    { note: 'The platform-risk asymmetry deserves weight. An email list you built is an asset you keep. A network on someone else\'s platform is access you are permitted, and permission can be withdrawn without appeal.' },
  ],
  faq: [
    { q: 'Can I automate LinkedIn outreach?', a: 'Tools exist, and using them breaches the platform\'s terms of service. Enforcement has become considerably more aggressive, and restrictions typically hit the account you have spent years building. Email automation, kept within volume and legal limits, carries no equivalent risk of losing the channel itself.' },
    { q: 'Which gets better response rates?', a: 'It varies so much by industry and audience that a general answer would mislead. The more useful question is where your specific buyers actually are. For trades and local businesses, email reaches people the platform never will; for software and consulting, a warm platform approach often outperforms a cold email.' },
    { q: 'Should I message someone on both channels?', a: 'Sequentially and with a light touch — a connection request, then an email that does not pretend the first did not happen. Simultaneous messages on both channels reads as pressure and is a common reason people disengage entirely.' },
    { q: 'Is LinkedIn worth paying for if I mainly use email?', a: 'Often yes, for research rather than messaging. Identifying the right person to write to, and understanding what a company actually does, is where it earns its cost even if every message you send goes by email.' },
  ],
  related: [
    ['/b2b-lead-generation-small-business/', 'B2B lead generation for small businesses'],
    ['/finding-business-emails-ethically/', 'Finding business emails ethically'],
  ],
},

{
  slug: 'cold-email-mistakes',
  title: 'Cold Email Mistakes That Cost the Most — Ranked by Damage',
  description: 'The outreach mistakes that do real damage, ordered by cost: burning your main domain, buying lists, sending in bursts, ignoring opt-outs, fake personalisation and mistaking volume for strategy.',
  keywords: 'cold email mistakes, outreach mistakes, cold email best practices, what not to do cold email',
  eyebrow: 'Mistakes',
  short: 'Costly mistakes',
  h1: 'The mistakes that cost most. <span style="color:var(--grey-4);font-weight:300;">In order of damage.</span>',
  cta: 'product',
  body: [
    { lead: 'Some outreach mistakes cost you a campaign. A few cost you assets you cannot easily replace — your domain, your reputation, occasionally a legal position. These are ordered by what they actually cost, not by how often they are mentioned.' },
    { h: '1. Sending from your main company domain' },
    'The most expensive mistake available, and the easiest to avoid. When deliverability degrades — and eventually something goes wrong — it takes your invoices, your client threads and your password resets with it. You discover this weeks later when a client says they never received something.',
    'A separate domain costs about twelve dollars a year. [Setting one up properly](/sending-domain-setup/) takes an afternoon.',
    { h: '2. Buying a list' },
    'Purchased lists are stale, unverified, and frequently contain spam traps — dormant addresses maintained specifically to catch senders who did not verify. Hitting one damages your reputation immediately, and no amount of good behaviour afterwards undoes it quickly. In the EU and UK, using bought personal data also puts you on the wrong side of data protection law.',
    { h: '3. Skipping authentication' },
    'No SPF, DKIM or DMARC means a large share of your mail is filtered before anyone reads it. People send for months without realising, conclude that cold email does not work, and abandon a channel that was never actually running. [Twenty minutes of setup.](/spf-dkim-dmarc-explained/)',
    { h: '4. Sending in bursts' },
    'Two hundred messages in an hour is a machine signature that no content disguises. Worse, it is usually the panic pattern — outreach neglected for weeks, then done all at once when a quiet month arrives. That is the version most likely to burn the domain.',
    { h: '5. Ignoring opt-outs' },
    'Someone asks not to be contacted and receives another message four months later because a different campaign pulled the same list. This generates complaints, which are the fastest reputational damage available, and in most jurisdictions it is unlawful. Opt-outs must be permanent and global across every campaign — not a per-campaign setting.',
    { h: '6. Fake personalisation' },
    'A merged company name inside an otherwise identical template. It is recognised instantly and lands worse than no personalisation, because it demonstrates you wanted to appear attentive without being it. [What genuine personalisation requires.](/personalisation-at-scale/)',
    { h: '7. Treating volume as strategy' },
    'When results are poor, the instinct is to send more. If a hundred well-targeted emails produce nothing, a thousand produce nothing at greater risk. Volume multiplies whatever your targeting already is — which is an argument for fixing [the profile](/building-an-ideal-customer-profile/) first.',
    { h: '8. Chasing people who said no' },
    'A no honoured cleanly leaves a door open; a no ignored closes it permanently and often produces a complaint. The same applies to the fifth follow-up on silence. [Two follow-ups, then stop.](/cold-email-follow-up/)',
    { note: 'Notice that the top five are all infrastructure and process, not writing. Copy is the part people enjoy working on, which is why it absorbs attention disproportionate to its effect. The mistakes that actually cost money are made before the first sentence is written.' },
  ],
  faq: [
    { q: 'What is the single most damaging cold email mistake?', a: 'Sending from the domain your business depends on. Every other mistake on this list costs you a campaign or a period of poor results. That one can take down the email your invoices, contracts and client relationships travel through, and you often do not notice until real damage has been done.' },
    { q: 'Can a domain recover from a bad campaign?', a: 'Sometimes, with weeks of stopped sending, a fixed root cause and a slow rebuild. Often it is faster and cheaper to start with a fresh domain — twelve dollars against weeks of uncertain recovery. Which is the argument for never risking a domain that matters in the first place.' },
    { q: 'How do I make opt-outs permanent across campaigns?', a: 'Keep a single exclusion list at the level of your whole operation, not inside individual campaigns, and check every send against it. Any tool that treats unsubscribes as a per-campaign setting will eventually email someone who asked you to stop — and that is a complaint waiting to happen.' },
    { q: 'Is it worth doing cold outreach at all given these risks?', a: 'Yes, if done at moderate volume with the infrastructure right. The risks concentrate almost entirely in shortcuts: bought lists, skipped authentication, burst sending, a shared domain. A separate domain, verified records, twenty messages a day and a real profile is a durable channel rather than a gamble.' },
  ],
  related: [
    ['/cold-email-deliverability-checklist/', 'The full deliverability checklist'],
    ['/why-cold-emails-go-to-spam/', 'Why cold emails go to spam'],
    ['/cold-email-follow-up/', 'How to follow up properly'],
  ],
},

{
  slug: 'b2b-lead-generation-small-business',
  title: 'B2B Lead Generation for Small Businesses — What Works Without a Sales Team',
  description: 'How a small business generates B2B leads without hiring: comparing referrals, inbound content, paid ads and outbound on cost, speed and control — and what to do first with limited time.',
  keywords: 'B2B lead generation small business, lead generation without sales team, small business prospecting, get more clients B2B',
  eyebrow: 'Strategy',
  short: 'B2B lead generation',
  h1: 'Lead generation <span style="color:var(--grey-4);font-weight:300;">when you are the sales team.</span>',
  cta: 'product',
  body: [
    { lead: 'A small business has four realistic ways to generate business-to-business leads. They differ enormously in how fast they work, how much control you have, and what they cost — and the right first move depends less on which is best in principle than on which one you can actually sustain.' },
    { h: 'The four channels' },
    { table: {
      minWidth: 640,
      head: ['Channel', 'Time to first result', 'Control', 'Real cost'],
      rows: [
        ['Referrals', 'Immediate, then unpredictable', 'None — you cannot turn it up', 'Free, but caps out'],
        ['Inbound content', '6 – 12 months', 'High once it works', 'Hours, sustained for months'],
        ['Paid ads', 'Days', 'High while you pay', 'Money, continuously'],
        ['Outbound', '2 – 6 weeks', 'Complete', 'Hours, or software'],
      ],
    }},
    { h: 'Referrals' },
    'The best leads you will ever get, and the ones you cannot control. They arrive warm, close fast, and negotiate less. They also arrive when they arrive — which means a business dependent on referrals is a business whose pipeline is set by other people\'s timing.',
    'Worth actively cultivating: ask satisfied clients directly, stay in contact after work ends. Not worth relying on as the only channel, because the failure mode is a quiet quarter you cannot do anything about.',
    { h: 'Inbound content' },
    'Writing that ranks in search and brings people who are already looking. Genuinely excellent when it works: the leads are warm, the cost per lead falls over time, and the asset keeps producing.',
    'The honest problem is the timeline. Six to twelve months of consistent publishing before meaningful traffic, and most small businesses stop at month three because nothing has happened yet. It is the right long game and the wrong answer to "I need clients this quarter".',
    { h: 'Paid advertising' },
    'Fastest to start, and the only channel that stops completely the moment you stop paying. For business-to-business with long consideration cycles, costs per acquisition are frequently higher than small businesses expect. Useful for testing whether a message resonates before investing months in it; expensive as a permanent foundation.',
    { h: 'Outbound' },
    'You decide who to contact and when. Results in weeks rather than months, no dependence on someone else\'s algorithm or timing, and the list you build is yours.',
    'The real cost is time, and it is larger than people expect: finding companies, researching each one, writing something specific, following up. At twenty companies a day that is roughly three hours daily — which is why most small businesses attempt outbound, do it for two weeks, and stop.',
    { h: 'What to do first' },
    { steps: [
      '**Ask your existing clients for referrals this week.** It is free, immediate, and almost nobody does it systematically.',
      '**Start outbound for the near term.** It is the only channel where effort this month produces conversations this month, and where you control the timing.',
      '**Begin publishing in parallel, quietly.** One useful piece a month compounds into the channel that eventually reduces your dependence on outbound.',
      '**Consider ads only to test a message,** not as a foundation. If a message does not work in outbound, paying to amplify it does not fix it.',
    ]},
    { note: 'The pattern that works for most small businesses: outbound generates the pipeline now, content builds the pipeline for later, and referrals compound from clients the first two brought in. The mistake is picking one and waiting.' },
  ],
  faq: [
    { q: 'How long before outbound produces results?', a: 'Two to six weeks in practice: one to two weeks to set up a sending domain and warm it, then a couple of weeks of consistent sending before replies accumulate into meaningful conversations. Faster than content, slower than ads, and the only one of the three where you control who hears from you.' },
    { q: 'Should a small business hire a salesperson instead?', a: 'A salesperson costs a salary before producing anything and takes months to become effective. For a small business the sequence that usually makes sense is to prove the channel works first — that the message lands and the offer converts — then hire someone to run a system that is already producing, rather than hiring someone to discover whether one exists.' },
    { q: 'Can I do outbound without any software?', a: 'Yes. A spreadsheet, a separate sending domain and disciplined manual sending works, and it is how most people should start — you learn what your market responds to before automating anything. What breaks is sustaining it: eight to twelve minutes per company, every day, is what stops most people by week three.' },
    { q: 'What if my market is too small for outbound?', a: 'Then outbound is even more suited to it, done by hand. If there are eighty companies you could serve, that is not a campaign — it is a list you work through personally over a few weeks, with genuine research on each. Automation earns its place when the list is large enough that personal attention does not scale.' },
  ],
  related: [
    ['/building-an-ideal-customer-profile/', 'Building an ideal customer profile'],
    ['/cold-email-vs-linkedin-outreach/', 'Cold email vs LinkedIn'],
    ['/how-to-write-a-cold-email/', 'How to write a cold email'],
  ],
},

];
