/* IA par métier — Polynésie française.
 *
 * Trois guides sectoriels : hôtellerie-pensions, commerce de Papeete,
 * prestataires nautiques. Même principe que industries.mjs côté EN :
 * chaque page part de la journée réelle du métier, pas d’un template
 * à variables. Si un paragraphe pouvait servir tel quel à un autre
 * secteur, il n’a rien à faire ici. */

export default [

{
  slug: 'ia-hotellerie-pensions-polynesie',
  lang: 'fr',
  title: 'IA pour l’hôtellerie et les pensions de famille en Polynésie française',
  description: 'Ce que l’automatisation change réellement pour un hôtel ou une pension de famille polynésienne : réservations multi-canaux, acomptes, no-shows, réponses bilingues FR/EN et avis — avec les limites à connaître.',
  keywords: 'IA hôtellerie Polynésie, automatisation pension de famille Tahiti, réservations OTA Polynésie française, no-show pension Tahiti, réponse avis hôtel IA',
  eyebrow: 'Polynésie française',
  short: 'IA · Hôtellerie & pensions',
  h1: 'L’IA en hôtellerie et pension de famille. <span style="color:var(--grey-4);font-weight:300;">La réservation d’abord.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Un hôtel de Punaauia et une pension de famille de Fakarava n’ont ni la même taille ni les mêmes moyens, mais leurs journées se ressemblent sur un point : les demandes arrivent par cinq canaux à la fois, la réponse attend la fin du service, et chaque réponse tardive est une nuit qui part ailleurs — ou qui revient par une plateforme, commission déduite.' },
    { h: 'La vitesse de réponse, c’est de la marge' },
    'Les plateformes de réservation prélèvent généralement entre 15 et 25 % du séjour. Sur trois nuits à 12 000 F la nuit — un ordre de grandeur courant en pension —, cela représente 5 000 à 9 000 F CFP qui quittent le fenua à chaque réservation. La demande directe, par mail ou par message, coûte zéro commission… à condition d’y répondre avant que le voyageur ne retourne sur la plateforme.',
    'C’est exactement ce qu’un système bien réglé sait faire : **accuser réception immédiatement, dans la langue du message, avec les vraies disponibilités**, puis préparer la réponse complète pour que vous n’ayez qu’à la relire. Le voyageur qui reçoit une réponse en dix minutes réserve rarement ailleurs.',
    { h: 'Cinq canaux, une seule file' },
    'Booking, le mail direct, Messenger, WhatsApp, le téléphone : chaque canal a sa logique, et aucune n’attend les autres. Les deux accidents classiques en découlent — la demande oubliée dans un canal qu’on consulte peu, et la surréservation quand deux canaux vendent la même nuit.',
    'Si vous avez déjà un channel manager, gardez-le : il synchronise les calendriers, c’est son métier. Ce qu’il ne traite pas, c’est **le texte libre** — « vous avez de la place pour 4 autour du 15 ? », « on peut décaler d’un jour ? », « vous faites le transfert depuis l’aéroport ? ». C’est cette couche-là que l’IA absorbe : chaque message lu, classé, versé dans une file unique avec un brouillon de réponse prêt.',
    { h: 'Acomptes et no-shows' },
    'Une réservation confirmée sans acompte est une intention, pas une réservation. Le mécanisme qui protège vos nuits tient en quatre gestes automatiques : le lien de paiement part avec la confirmation, un rappel part avant l’échéance, la chambre se libère si l’acompte n’arrive pas, et le message pré-arrivée collecte le numéro de vol ou l’horaire du bateau — ce qui, pour une pension qui va chercher ses hôtes, évite les allers-retours à vide.',
    { h: 'Le bilingue, sans y laisser ses soirées' },
    'La clientèle anglophone est structurelle en Polynésie française, et répondre en anglais après une journée de service est le genre de tâche qui glisse au lendemain. Un assistant qui rédige la réponse dans la langue du client — vous relisez, vous signez — supprime ce délai sans rien enlever à votre voix.',
    'La limite mérite d’être posée : la traduction automatique est devenue très fiable entre français et anglais, mais **tout ce qui engage — tarifs, conditions d’annulation, ce qui est inclus — se relit avant de partir**. Un malentendu sur une condition d’annulation coûte plus cher que le temps de relecture.',
    { h: 'Les avis et la saison creuse' },
    { table: {
      minWidth: 560,
      head: ['Automatisation', 'Ce que ça change'],
      rows: [
        ['Réponse aux avis, dans la langue de l’avis', 'Chaque avis reçoit une réponse personnelle sous 48 h — relue par vous. Les voyageurs lisent les réponses autant que les avis.'],
        ['Relance des anciens hôtes en saison creuse', 'La haute saison porte de mai à octobre ; le fichier des hôtes passés, résidents compris, est le levier le moins cher pour remplir le reste.'],
        ['Message pré-arrivée et post-départ', 'Numéro de vol collecté avant, demande d’avis après — deux messages que personne n’a le temps d’envoyer à la main.'],
        ['Tableau de bord d’occupation', 'Taux de remplissage et provenance des réservations, assemblés chaque semaine depuis vos canaux — pour décider avec des chiffres, pas de mémoire.'],
      ],
    }},
    'Un mot sur les données : votre fichier d’hôtes contient des données personnelles de voyageurs — passeports, contacts, habitudes. Elles peuvent rester chez vous : des systèmes tournent sur votre propre machine, sans transiter par un service tiers — c’est le sujet de [l’IA en local](/ia-locale-entreprise/).',
    { note: 'Ce qu’il ne faut pas automatiser : l’accueil lui-même. On choisit une pension pour la table d’hôte et pour la personne qui reçoit ; le jour où vos messages sentent la machine, vous avez perdu davantage que le temps gagné. Le partage qui fonctionne : **le système prépare, l’hôte relit et signe.**' },
  ],
  faq: [
    { q: 'Un chatbot sur mon site est-il le bon point de départ ?', a: 'Rarement. Vos demandes arrivent déjà par mail, Messenger et WhatsApp : traiter vite et bien ces canaux existants rapporte plus qu’un widget de plus sur le site. Le chatbot se justifie ensuite, quand le volume de questions répétitives le mérite — pas comme premier chantier.' },
    { q: 'L’IA peut-elle répondre à mes clients en anglais ?', a: 'Oui, et c’est l’un des usages les plus rentables en hôtellerie polynésienne : la réponse est rédigée dans la langue du message, vous la relisez avant envoi. Gardez la relecture systématique pour tout ce qui engage — tarifs, conditions, prestations incluses.' },
    { q: 'Combien ça coûte pour une pension de famille ?', a: 'Un premier workflow — accusé de réception avec disponibilités, acomptes, message pré-arrivée — se situe entre 120 000 et 480 000 F CFP, précédé d’un audit gratuit en visio. Les fourchettes détaillées du marché polynésien sont dans [notre guide des prix](/automatisation-ia-polynesie-francaise/). Commencer par un seul processus permet de mesurer avant d’étendre.' },
    { q: 'Vous n’êtes pas installés en Polynésie — comment ça se passe ?', a: 'Nous travaillons depuis Nouméa et Auckland, en visio et par écrit ; les systèmes sont déployés à distance dans vos outils et tournent chez vous, 24 h/24. Le décalage horaire se gère : vos fins de matinée et débuts d’après-midi tombent dans nos heures de bureau. Si vous préférez un prestataire présent physiquement, des agences existent à Tahiti — et c’est un vrai critère de choix, pas un détail.' },
  ],
  related: [
    ['/ia-prestataires-nautiques-polynesie/', 'IA pour les prestataires nautiques'],
    ['/ia-commerce-papeete/', 'IA pour les commerces de Papeete'],
    ['/automatisation-ia-tahiti/', 'Notre page Polynésie française'],
    ['/combien-coute-automatisation-ia/', 'Combien ça coûte, vraiment'],
  ],
},

{
  slug: 'ia-commerce-papeete',
  lang: 'fr',
  title: 'IA pour les commerces et services de Papeete — stock, relances, concurrence de l’import',
  description: 'Automatisation pour les commerçants de Papeete : gérer le stock quand le réassort prend des semaines de fret, lire les factures fournisseurs, prévenir les clients, et tenir face à l’achat en ligne.',
  keywords: 'IA commerce Papeete, automatisation commerce Polynésie, gestion stock fret Tahiti, relance client commerce Papeete, concurrence import Polynésie française',
  eyebrow: 'Polynésie française',
  short: 'IA · Commerces de Papeete',
  h1: 'L’IA pour les commerces de Papeete. <span style="color:var(--grey-4);font-weight:300;">Le stock décide de tout.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Les logiciels de commerce sont écrits pour des boutiques dont le fournisseur livre en trois jours. À Papeete, le réassort traverse un océan : selon la provenance et la ligne, comptez plusieurs semaines de fret, parfois deux mois porte à porte. Cette contrainte-là change l’ordre des priorités — et c’est par elle qu’il faut commencer.' },
    { h: 'Le stock quand le réassort traverse un océan' },
    'La rupture de stock qui se répare en trois jours en métropole se répare en six semaines ici : six semaines de ventes perdues, et un client parti commander en ligne qui ne reviendra peut-être pas. À l’inverse, sur-stocker immobilise une trésorerie que le coût du fret a déjà entamée.',
    'La réponse utile n’est pas une prédiction magique des ventes — personne ne prédit une saison touristique mieux que vous. C’est plus terre à terre : **des seuils d’alerte par produit, calés sur le délai réel de chaque fournisseur**, recalculés depuis l’historique de vente, avec une proposition de commande que vous validez ou corrigez. Un fournisseur à six semaines de mer exige six semaines d’avance ; un carnet ou un tableur ne tient pas ce calcul à jour sur des centaines de références, un système oui.',
    { h: 'Les factures fournisseurs, lues au lieu d’être ressaisies' },
    'Chaque conteneur arrive avec sa liasse : factures, bons de livraison, documents de fret. La double saisie vers la caisse et la comptabilité est le gisement mécanique le plus sûr du commerce — l’extraction automatique lit les pièces, verse les données dans vos outils, et signale les écarts entre ce qui a été commandé, facturé et réellement reçu. Sur du fret longue distance, ces écarts existent, et les repérer à la réception vaut mieux que les découvrir à l’inventaire.',
    'Des pièces propres et rapprochées simplifient aussi la suite : les déclarations de TVA polynésienne — dont les taux varient selon les produits, votre comptable ou la DICP faisant foi — et le dossier que vous transmettez au cabinet chaque mois.',
    { h: 'Prévenir le client, systématiquement' },
    'Avec des délais pareils, le client qui a commandé un article a souvent cessé d’y penser quand l’article arrive. Le prévenir le jour du déballage — pas la semaine suivante — transforme un carton en vente conclue. Même mécanique pour la réparation prête, l’entretien récurrent d’un équipement vendu, ou la relance d’un devis resté sans réponse. Aucune de ces relances n’est difficile ; elles sont simplement innombrables, et c’est pour cela qu’elles ne se font pas à la main.',
    'Pour les prestataires de services de la place — ateliers, agences, professions libérales —, ajoutez les relances d’impayés progressives et polies, et la génération de devis et factures conformes, numéro TAHITI et mentions fiscales comprises.',
    { h: 'L’achat en ligne se combat sur son terrain' },
    'Vos clients comparent vos prix avec des sites étrangers. Ce que ces sites ne peuvent pas offrir : l’article aujourd’hui, sans semaines d’attente ni taxes à l’arrivée. Cet avantage ne joue que si le client **sait** que vous avez l’article — d’où trois chantiers concrets :',
    { cards: [
      { t: 'Le stock visible', d: 'Une page à jour depuis la caisse qui répond à la seule question qui compte : « c’est disponible en magasin ? ». Pas une boutique en ligne complète — une vitrine du stock réel.' },
      { t: 'La réponse en minutes', d: 'Les messages « vous l’avez en ce moment ? » sur Messenger ou WhatsApp reçoivent une réponse immédiate, avec l’état du stock. Dix minutes de délai gardent la vente ; deux jours la perdent.' },
      { t: 'Le retrait simplifié', d: 'Mise de côté confirmée par message, l’article attend au comptoir. Le confort de la commande en ligne, sans le fret ni l’attente.' },
    ]},
    { h: 'Le pilotage, sans le vendredi soir de saisie' },
    'Recettes journalières consolidées, meilleures ventes de la semaine, comparaison d’un mois sur l’autre, écarts de caisse signalés : autant de chiffres qui existent déjà dans vos outils et que personne n’assemble. Un rapport hebdomadaire construit automatiquement depuis la caisse rend la décision de commande — la vraie décision du métier, vu les délais — un peu moins dépendante de la mémoire.',
    { note: 'L’ordre des chantiers compte. Les seuils de réassort et la lecture des factures d’abord : c’est mécanique, mesurable, et personne ne regrettera la ressaisie. La visibilité en ligne ensuite, une fois que le stock affiché est fiable — une page de stock fausse fait plus de dégâts que pas de page du tout.' },
  ],
  faq: [
    { q: 'Mon commerce est petit — c’est rentable pour moi ?', a: 'Souvent plus que pour une grande enseigne, qui a du personnel pour absorber l’administratif. Dans une boutique où la même personne tient la caisse, les commandes et la comptabilité, chaque heure de ressaisie supprimée est une heure rendue au métier. Commencez par un seul chantier — les factures fournisseurs ou les seuils de stock — et mesurez sur un mois.' },
    { q: 'L’IA peut-elle prévoir mes ventes ?', a: 'Pas mieux que vous sur l’essentiel : vous connaissez vos saisons, vos clients et les à-coups du tourisme. Ce que le système fait mieux, c’est la tenue à jour — recalculer les seuils produit par produit selon les délais réels de chaque fournisseur, sans fatigue et sans oubli. La décision de commander reste la vôtre, mais elle arrive préparée.' },
    { q: 'Est-ce que ça fonctionne avec ma caisse actuelle ?', a: 'Dans la plupart des cas, oui — par les exports ou les connexions que votre caisse propose déjà. C’est précisément le point à cadrer pendant l’audit : la connexion aux outils existants représente l’essentiel du travail, davantage que l’IA elle-même, et c’est elle qui fait varier le devis.' },
    { q: 'Quel budget prévoir ?', a: 'Un premier workflow — seuils de réassort ou extraction des factures — se situe entre 120 000 et 480 000 F CFP, avec un audit gratuit au départ pour identifier celui qui rapporte le plus. Les fourchettes complètes du marché polynésien sont détaillées dans [notre guide des prix](/automatisation-ia-polynesie-francaise/).' },
  ],
  related: [
    ['/ia-hotellerie-pensions-polynesie/', 'IA pour l’hôtellerie et les pensions'],
    ['/ia-prestataires-nautiques-polynesie/', 'IA pour les prestataires nautiques'],
    ['/exemples-automatisation-pme/', '10 exemples d’automatisation'],
    ['/automatisation-ia-tahiti/', 'Notre page Polynésie française'],
  ],
},

{
  slug: 'ia-prestataires-nautiques-polynesie',
  lang: 'fr',
  title: 'IA pour les prestataires nautiques en Polynésie française — plongée, excursions, charter',
  description: 'Automatisation pour les clubs de plongée, excursions lagon et charters polynésiens : annulations météo gérées en minutes, acomptes qui protègent les sorties, planning bateaux et guides, devis groupes.',
  keywords: 'IA plongée Polynésie, automatisation excursion lagon Tahiti, charter Polynésie gestion réservations, annulation météo prestataire nautique, acompte sortie bateau',
  eyebrow: 'Polynésie française',
  short: 'IA · Prestataires nautiques',
  h1: 'L’IA pour les prestataires nautiques. <span style="color:var(--grey-4);font-weight:300;">La météo décide, le système suit.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Plongée, excursions lagon, charter : le calendrier de ces métiers appartient à la météo. Quand le maramu se lève et qu’une matinée de sorties tombe, la journée se transforme en standard téléphonique — prévenir, reprogrammer, rembourser, recaser. C’est ce jour-là, précisément, que l’automatisation se rembourse.' },
    { h: 'Le jour où la sortie s’annule' },
    'Une annulation météo, ce n’est pas un message : c’est douze réservations à prévenir, souvent en deux langues, chacune avec sa question — report, remboursement, autre créneau —, des acomptes à faire suivre et une liste d’attente à recaser sur les places qui se libèrent. Fait à la main, cela mange la demi-journée que la météo venait déjà de prendre.',
    'La bonne répartition des rôles : **vous décidez d’annuler, le système exécute.** Chaque client reçoit un message personnalisé avec les créneaux de report réellement disponibles ; l’acompte est basculé ou remboursé selon votre politique écrite ; la liste d’attente est contactée dans l’ordre. Vingt minutes de supervision au lieu d’un après-midi de téléphone — et aucun client oublié dans la bousculade, ce qui est la vraie source des mauvais avis.',
    { h: 'L’acompte, ou le bateau à moitié vide' },
    'Un bateau qui sort à six au lieu de dix coûte exactement le même carburant et le même skipper — seule la recette change. Et la réservation d’un voyageur qui « confirmera selon le temps » ne protège rien du tout. À 10 000 F la place, deux défections par semaine représentent, sur une saison, l’équivalent d’un mois entier de sorties offert.',
    'Le remède est connu de tous et appliqué par peu, parce qu’il demande une discipline de suivi : **lien de paiement envoyé à la réservation, rappel avant échéance, place remise en vente si l’acompte n’arrive pas.** Automatisé, ce circuit tourne sans friction et sans la gêne d’avoir à réclamer — le message poli part toujours, ce qui n’est jamais le cas quand il faut l’écrire soi-même après une journée en mer.',
    { h: 'Bateaux, guides, niveaux : le planning réel' },
    'Le planning d’un club n’est pas une liste de créneaux : c’est un problème à contraintes. La capacité de chaque bateau, les moniteurs disponibles, le niveau des plongeurs — un baptême et des plongeurs confirmés ne vont pas au même endroit —, les tailles de matériel, les rotations du matin et de l’après-midi. En saison des baleines, de juillet à novembre, tout cela sature en même temps.',
    'L’automatisation utile ici est modeste et quotidienne : **la fiche de sortie assemblée seule** — qui embarque, quel niveau, quel matériel, quel bateau, quel moniteur — depuis les réservations, au lieu du tableau recopié chaque soir. La modification de dernière minute se répercute partout d’un coup, y compris dans les messages aux clients concernés.',
    { h: 'Les devis groupes, partis le jour même' },
    'Hôtels, séminaires, mariages, passagers de croisière : les demandes de groupe sont les plus rentables du métier et arrivent par un mail sans structure — « on serait une quinzaine, plutôt fin de matinée, avec deux enfants ». Un devis paramétré — nombre de personnes, durée, bateau, prestation — mis en forme et prêt à relire dans l’heure fait souvent la différence, car l’organisateur écrit rarement à un seul prestataire.',
    { h: 'Les formalités avant le quai' },
    { table: {
      minWidth: 560,
      head: ['Situation', 'À la main', 'Automatisé'],
      rows: [
        ['Annulation météo (12 réservations)', 'Une demi-journée de messages et d’appels', 'Vingt minutes de supervision, personne d’oublié'],
        ['Acompte non réglé', 'On découvre le no-show au quai', 'Rappel envoyé, place remise en vente avant la sortie'],
        ['Fiches et certificats plongeurs', 'Remplis sur le quai, 20 minutes de départ perdues', 'Collectés en ligne avant l’arrivée, résumé remis au moniteur'],
        ['Devis groupe', 'Rédigé le soir, parti à J+2', 'Assemblé dans l’heure, relu et envoyé le jour même'],
      ],
    }},
    'Les fiches de renseignement, certificats de niveau, décharges et contraintes médicales collectés avant le jour J font gagner le quart d’heure de quai que tout le monde connaît — et surtout, rien n’est oublié : le document manquant se signale la veille, pas au moment d’embarquer.',
    { note: 'Ce que le système ne décide jamais : sortir ou pas. La lecture du plan d’eau, la sécurité, le seuil au-delà duquel on annule — c’est le jugement du patron, et il n’est pas automatisable. Tout ce qui est décrit ici exécute une décision humaine ; rien ne la remplace.' },
  ],
  faq: [
    { q: 'Peut-on vraiment automatiser une annulation météo ?', a: 'On automatise l’exécution, pas la décision. Vous jugez les conditions et vous annulez ; le système prévient chaque réservation dans sa langue, propose les créneaux de report réels, applique votre politique d’acompte et recase la liste d’attente. La distinction compte : personne ne veut d’un système qui annule des sorties à votre place sur la foi d’un bulletin.' },
    { q: 'Mes clients réservent par WhatsApp et Instagram — c’est compatible ?', a: 'Oui, et c’est même le cas typique du métier : les demandes en texte libre sur les messageries sont lues, classées et versées dans une file unique avec les informations extraites — date souhaitée, nombre de personnes, niveau. Vous validez, le système confirme et envoie le lien d’acompte.' },
    { q: 'Quel budget pour une petite structure — deux bateaux, trois moniteurs ?', a: 'Le premier circuit — confirmation, acompte, rappel, fiche de sortie — se situe entre 120 000 et 480 000 F CFP, après un audit gratuit qui cadre le périmètre. Le guide complet des prix du marché polynésien est ici : [combien coûte l’automatisation](/automatisation-ia-polynesie-francaise/). Commencez par les acomptes : c’est le chantier dont l’effet se mesure en francs, pas en heures.' },
    { q: 'Et pour encaisser les acomptes en ligne ?', a: 'Les solutions de paiement en ligne acceptant les cartes internationales s’intègrent au message de confirmation sous forme de lien ; le client paie en quelques gestes, vous êtes notifié, la place est verrouillée. Comparez les frais par transaction avant de choisir — sur des acomptes modestes, ils pèsent — et vérifiez le délai de reversement sur votre compte.' },
  ],
  related: [
    ['/ia-hotellerie-pensions-polynesie/', 'IA pour l’hôtellerie et les pensions'],
    ['/ia-commerce-papeete/', 'IA pour les commerces de Papeete'],
    ['/automatisation-ia-tahiti/', 'Notre page Polynésie française'],
    ['/combien-coute-automatisation-ia/', 'Combien ça coûte, vraiment'],
  ],
},

];
