/* Guides « IA par métier » — Kanaky (Nouvelle-Calédonie).
 *
 * Six secteurs, six pages écrites chacune depuis la réalité du métier —
 * pas un gabarit décliné. Si un paragraphe pouvait servir tel quel à un
 * autre secteur, il n’a pas sa place ici. Nommage : « Kanaky
 * (Nouvelle-Calédonie) » dans le texte visible, « Nouvelle-Calédonie »
 * dans title/description/keywords (la forme cherchée sur Google). */

export default [

{
  slug: 'ia-btp-nouvelle-caledonie',
  lang: 'fr',
  title: 'IA pour le BTP en Nouvelle-Calédonie — devis, situations, avenants',
  description: 'Ce que l’IA change pour une entreprise du bâtiment calédonienne : devis rendus le jour même, situations de travaux suivies et relancées, avenants tracés — dans un secteur qui manque de bras depuis 2024.',
  keywords: 'IA BTP Nouvelle-Calédonie, automatisation construction Nouméa, devis bâtiment automatique NC, logiciel entreprise BTP Nouvelle-Calédonie, relance situation de travaux',
  eyebrow: 'Kanaky (Nouvelle-Calédonie)',
  short: 'IA · BTP',
  h1: 'L’IA dans le BTP calédonien. <span style="color:var(--grey-4);font-weight:300;">Le chantier avance, le bureau suit.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Le BTP de Kanaky (Nouvelle-Calédonie) sort de deux années rudes : carnets vidés en 2024, puis une reprise tirée par la reconstruction — avec moins de bras qu’avant, une partie des ouvriers qualifiés ayant quitté le territoire. Quand chaque conducteur de travaux compte double, les soirées passées sur les devis et les situations sont exactement ce qu’il faut aller récupérer.' },
    { h: 'Le devis rendu à J+8 est un chantier qui file' },
    'La mécanique est connue de toutes les entreprises du bâtiment : la visite se fait entre deux interventions, le métré tient sur un carnet, et le chiffrage attend le soir — puis le week-end. Pendant ce temps, le client a reçu deux autres propositions.',
    'Dicter le descriptif en quittant le terrain — surfaces, prestations, contraintes d’accès — et récupérer un devis structuré en XPF, monté sur **votre** bibliothèque de prix, avec la mention TGC correspondant à votre régime : voilà le premier réflexe à installer. Vous relisez, vous ajustez, ça part le soir même. Sur une rénovation à 2,5 millions de francs, être le premier devis arrivé pèse souvent plus lourd qu’être le moins cher.',
    { h: 'Les situations de travaux, nerf de la trésorerie' },
    'Une entreprise de construction meurt rarement d’un manque de chantiers : elle meurt d’encaissements qui glissent. La situation mensuelle envoyée en retard, jamais relancée, la retenue de garantie oubliée deux ans — chaque maillon qui lâche coûte des semaines de trésorerie.',
    'L’automatisation tient ce fil sans état d’âme : la situation part à date fixe, la relance suit un calendrier progressif et référencé — numéro de situation, montant, échéance contractuelle — et la retenue de garantie revient dans votre tableau de bord à sa date de libération au lieu de sombrer dans un classeur.',
    { h: 'L’avenant oral est un litige en préparation' },
    '« On rajoute une cloison, on s’arrange sur le prix, on verra à la fin. » Tout le monde a déjà vécu la fin en question. La note vocale prise sur le chantier, transformée en avenant daté et envoyé au client pour accord, prend trois minutes — et c’est elle qui tranche quand le décompte final se discute. Ce ne sont pas les gros avenants qui rongent la marge : ce sont les petits, accumulés, jamais écrits.',
    { h: 'Quatre postes, ce que ça change' },
    { table: {
      minWidth: 580,
      head: ['Poste', 'Aujourd’hui', 'Automatisé'],
      rows: [
        ['Devis de rénovation', 'Deux ou trois soirées après les journées de chantier', 'Dicté sur place, relu en vingt minutes, parti le soir'],
        ['Situation mensuelle et relances', 'Une demi-journée, et la gêne de réclamer', 'Émise à date fixe, relancée sans y penser'],
        ['Avenants', 'Convenus à l’oral, écrits rarement', 'Trace datée systématique, accord client conservé'],
        ['Dossier d’appel d’offres', 'Pièces rassemblées la veille du dépôt', 'Attestations et références pré-assemblées depuis vos dossiers'],
      ],
    }},
    { h: 'La pénurie de main-d’œuvre change le calcul' },
    'On ne remplace pas un coffreur ou un grutier par une annonce en ce moment — beaucoup sont partis, et ceux qui restent choisissent. L’IA ne coulera jamais une dalle ; ce qu’elle rend, ce sont les heures d’encadrement : celles du gérant et du conducteur de travaux, précisément les profils les plus difficiles à embaucher. Dix heures administratives récupérées par semaine dans une équipe de cinq, c’est un quart de poste qualifié que le marché ne fournit plus.',
    'Côté budget : un premier chantier d’automatisation — le devis dicté, ou le suivi des situations — se règle entre **80 000 et 250 000 F** à notre [tarif reprise](/prix-automatisation-ia-nouvelle-caledonie/), audit préalable gratuit. Sur chaque paiement encaissé au pays, [10 % repartent vers une association calédonienne](/engagement-local/). Et si vos prix, vos marges et vos fichiers clients ne doivent croiser aucun serveur étranger, [le système peut tourner sur une machine au dépôt](/ia-locale-entreprise/).',
    { note: 'Une entreprise du bâtiment n’a pas besoin d’un « plan de transformation numérique ». Elle a besoin que le devis parte le jour de la visite, que la situation soit relancée sans gêne et que l’avenant existe par écrit. Trois choses bornées, mesurables — et qui se lisent directement dans la trésorerie.' },
  ],
  faq: [
    { q: 'L’IA connaît-elle les prix du BTP calédonien ?', a: 'Non, et méfiez-vous de qui prétend le contraire : entre le fret, les matériaux importés et les écarts d’un fournisseur à l’autre, les prix pratiqués ici ne ressemblent à aucune base métropolitaine. Le chiffrage s’appuie sur votre propre bibliothèque de prix, que le système applique et met en forme. L’IA rédige et structure ; les prix restent les vôtres, et la relecture aussi.' },
    { q: 'Relancer une situation impayée ne va-t-il pas froisser le donneur d’ordre ?', a: 'Une relance factuelle — numéro de situation, montant, échéance contractuelle — est un acte de gestion, pas un reproche, et les services comptables en reçoivent tous les jours. Ce qui abîme la relation, c’est le coup de téléphone tendu après quatre mois de silence. L’escalade progressive et polie évite justement d’en arriver là, et chaque message peut vous être soumis avant envoi.' },
    { q: 'Est-ce pertinent pour une entreprise de trois personnes ?', a: 'C’est là que l’effet est le plus net : sans personne au bureau pour absorber l’administratif, chaque heure rendue revient au gérant. Le devis dicté change les soirées à lui seul — commencez par lui, mesurez un mois, et décidez de la suite sur les chiffres.' },
    { q: 'Et pour les appels d’offres publics ?', a: 'La partie mécanique s’assemble : attestations RIDET, CAFAT et fiscales à jour, références de chantiers comparables tirées de vos dossiers, trame du mémoire technique montée depuis vos réalisations. Le chiffrage et la stratégie de réponse restent votre métier — mais déposer un dossier complet sans y passer la nuit précédente devient la norme, pas l’exploit.' },
  ],
  related: [
    ['/ia-services-techniques-nouvelle-caledonie/', 'IA pour la clim, l’élec et la plomberie'],
    ['/prix-automatisation-ia-nouvelle-caledonie/', 'Les tarifs au pays'],
    ['/exemples-automatisation-pme/', '10 exemples d’automatisation'],
    ['/ia-locale-entreprise/', 'L’IA en local'],
  ],
},

{
  slug: 'ia-commerce-noumea',
  lang: 'fr',
  title: 'IA pour les commerces de Nouméa — stock, fichier clients, croisiéristes',
  description: 'Automatiser un commerce de Nouméa : réassort avec six semaines de mer, fichier clients enfin travaillé, jours d’escale préparés — et ce que l’import en ligne ne fera jamais.',
  keywords: 'IA commerce Nouméa, automatisation boutique Nouvelle-Calédonie, gestion stock commerce Nouméa, relance clients magasin NC, commerce croisiéristes Nouméa',
  eyebrow: 'Kanaky (Nouvelle-Calédonie)',
  short: 'IA · Commerce Nouméa',
  h1: 'L’IA en boutique à Nouméa. <span style="color:var(--grey-4);font-weight:300;">Ce que le colis ne fera pas.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Un commerce de Nouméa se bat sur deux fronts qui ne se ressemblent pas : le colis commandé en ligne qui atterrit en dix jours, et son propre réassort qui met six semaines de bateau. Entre les deux, un fichier clients qui dort dans la caisse, des messages Facebook lus à la fermeture, et des samedis d’escale où tout le monde court.' },
    { h: 'Le réassort avec six semaines de mer devant soi' },
    'La rupture de stock en boutique ne pardonne pas : le client reparti commander en ligne ne revient pas à l’arrivée du conteneur. À l’inverse, le surstock immobilise une trésorerie que personne n’a de reste en ce moment.',
    'Votre caisse enregistre depuis des années le rythme réel de chaque référence. Croiser ces sorties avec les délais maritimes donne une chose simple : l’alerte de commande au moment où il faut la passer, ni avant ni après — en intégrant la saison, les fêtes et les pics d’escale. La décision reste la vôtre ; ce qui disparaît, c’est la commande passée trop tard un dimanche de fin de mois.',
    { h: 'Le fichier clients est l’actif le moins travaillé du commerce' },
    'Cartes de fidélité, tickets, numéros pris au comptoir : la matière existe, elle n’est presque jamais exploitée. La cliente qui passait tous les mois et qu’on n’a pas revue depuis avril mérite un message — pas une campagne de masse, un message. Repérer ces silences dans l’historique et préparer la relance, c’est le travail dont aucun commerçant n’a le temps et que le système fait sans effort. Avec le consentement recueilli proprement et un désabonnement en un geste, évidemment.',
    { h: 'Les escales se préparent, elles ne se subissent pas' },
    'Le calendrier des touchées de paquebots est connu longtemps à l’avance, et la fréquentation d’un jour d’escale n’a rien de comparable avec une matinée ordinaire. Ce qui s’anticipe : le planning de l’équipe, le réassort des références qui partent fort ces jours-là, l’étiquetage et les réponses en anglais aux questions qui reviennent — détaxe, tailles, expédition. Le flux se gère au comptoir ; la préparation, en amont.',
    { h: 'Ce que le colis ne fera jamais' },
    { table: {
      minWidth: 580,
      head: ['Le colis en ligne', 'Votre boutique', 'Ce que l’automatisation y ajoute'],
      rows: [
        ['Le prix bas', 'Le conseil et la confiance', 'Du temps de vente en plus, l’administratif étant absorbé'],
        ['Le choix infini', 'L’article disponible tout de suite', 'Un réassort piloté qui tient la promesse « en rayon aujourd’hui »'],
        ['La relance algorithmique permanente', 'Une relation réelle', 'Un fichier clients enfin travaillé, message par message'],
        ['Dix jours de livraison', 'L’article dans la main ce soir', 'Un catalogue en ligne simple et le retrait en boutique'],
      ],
    }},
    'On ne bat pas une plateforme mondiale sur le prix, et il ne faut pas essayer. On la bat sur la disponibilité immédiate, le conseil et la relation — trois promesses qui exigent du temps humain. L’automatisation ne remplace pas la personne au comptoir : elle lui rend les heures que mangeaient la saisie, les relances et les commandes.',
    'Un premier chantier bien borné — le pilotage du réassort ou la reprise du fichier clients — se situe entre **80 000 et 250 000 F** : [la grille reprise appliquée au pays](/prix-automatisation-ia-nouvelle-caledonie/) le détaille, et un dixième de chaque facture réglée ici [finance une association du territoire](/engagement-local/). L’historique de caisse et le fichier clients peuvent rester [sur une machine dans l’arrière-boutique](/ia-locale-entreprise/) plutôt que chez un tiers.',
    { note: 'Avant de dépenser un franc : exportez un an de tickets de caisse et regardez ce qui tourne, ce qui dort et qui a cessé de venir. La plupart des caisses de Nouméa contiennent des années de réponses que personne n’a jamais lues — et cet examen-là est gratuit.' },
  ],
  faq: [
    { q: 'Ai-je le droit d’envoyer des SMS ou des mails de relance à mes clients ?', a: 'Oui, avec leur consentement et une désinscription simple — la loi Informatique et libertés s’applique en Kanaky (Nouvelle-Calédonie) et la CNIL y est compétente. Concrètement : recueillir l’accord au moment de la carte de fidélité ou du passage en caisse, et cesser au premier stop. Bien fait, ce canal est apprécié ; c’est le message de masse non sollicité qui use.' },
    { q: 'La prévision de réassort fonctionne-t-elle avec des délais aussi longs ?', a: 'C’est justement quand le délai est long qu’elle rapporte : à six semaines de mer, une commande ratée se paie six semaines de rayon vide. Le système propose des quantités à partir de vos sorties réelles et de la saisonnalité ; vous arbitrez, notamment sur les nouveautés que l’historique ne connaît pas encore.' },
    { q: 'Je tiens ma boutique seule. Par où commencer ?', a: 'Par une seule chose, et probablement la relance clients : elle crée du passage sans rien changer à vos journées. Le pilotage du stock vient ensuite, quand la première automatisation a fait ses preuves — deux chantiers à moitié menés valent moins qu’un seul qui tourne.' },
    { q: 'Faut-il un vrai site e-commerce ?', a: 'Rarement en premier. Un catalogue en ligne à jour avec retrait en boutique capte déjà l’achat décidé le soir sur un téléphone, sans logistique de livraison ni plateforme coûteuse. Si la demande en ligne devient réelle, vous le saurez — et vous construirez alors sur des chiffres, pas sur une intuition.' },
  ],
  related: [
    ['/ia-hotellerie-tourisme-nouvelle-caledonie/', 'IA pour l’hôtellerie et le tourisme'],
    ['/prix-automatisation-ia-nouvelle-caledonie/', 'Les tarifs au pays'],
    ['/combien-coute-automatisation-ia/', 'Les prix en détail'],
    ['/exemples-automatisation-pme/', '10 exemples d’automatisation'],
  ],
},

{
  slug: 'ia-hotellerie-tourisme-nouvelle-caledonie',
  lang: 'fr',
  title: 'IA pour l’hôtellerie et le tourisme en Nouvelle-Calédonie — résas, no-shows, avis',
  description: 'Hôtels, gîtes et prestataires en Nouvelle-Calédonie : centraliser les demandes multi-canaux, réduire les no-shows, répondre en anglais et soigner les avis — pendant que le tourisme se reconstruit.',
  keywords: 'IA hôtellerie Nouvelle-Calédonie, automatisation gîte NC, réservations tourisme Nouvelle-Calédonie, no-show hôtel, avis clients tourisme Nouméa',
  eyebrow: 'Kanaky (Nouvelle-Calédonie)',
  short: 'IA · Hôtellerie-tourisme',
  h1: 'L’IA en hôtellerie et tourisme. <span style="color:var(--grey-4);font-weight:300;">Répondre vite, dans les deux langues.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Une demande de séjour peut arriver par Booking, par mail, par Messenger, par WhatsApp ou par un appel en plein service du petit-déjeuner. Dans un tourisme calédonien qui se reconstruit visiteur par visiteur, celle qui attend quarante-huit heures est déjà repartie — parfois vers un autre établissement, souvent vers une autre destination.' },
    { h: 'Cinq canaux, un seul planning' },
    'Le vrai problème du multi-canal n’est pas le volume, c’est la dispersion : la même case du planning se retrouve promise sur deux fils de discussion, la demande de groupe attend dans une messagerie que personne ne relève le dimanche. Centraliser tout ce qui entre, répondre immédiatement avec les disponibilités réelles, collecter dates, effectif et attentes avant qu’un humain n’ouvre le dossier : la réservation se gagne dans la première heure.',
    { table: {
      minWidth: 580,
      head: ['Canal', 'Là où ça se perd', 'Ce qui change'],
      rows: [
        ['Plateformes (Booking, Expedia)', 'Commission sur chaque nuit, client jamais vraiment « à vous »', 'Le client satisfait est invité à réserver en direct la fois suivante'],
        ['Mail direct', 'Réponse le soir, après le service', 'Accusé immédiat avec disponibilités réelles et proposition datée'],
        ['Messenger et WhatsApp', 'Lus à 22 h, répondus le lendemain', 'Qualification immédiate, main passée à l’humain dès que ça sort du cadre'],
        ['Téléphone en plein service', 'Interrompt l’accueil ou sonne dans le vide', 'La demande est captée, tracée, rappelée à l’heure promise'],
      ],
    }},
    { h: 'Les no-shows se traitent avant l’arrivée, pas après' },
    'Un gîte qui perd deux nuits par semaine à 12 000 F la nuit laisse plus d’un million de francs par an dans les réservations fantômes. Le remède est connu et demande surtout de la constance : un acompte par lien de paiement à la réservation, une confirmation à J-7 puis à J-2, des conditions d’annulation dites clairement dès le premier échange. Aucune de ces étapes n’exige un humain — et c’est leur régularité qui fait leur efficacité.',
    { h: 'L’anglais des visiteurs, sans attendre le retour du gérant' },
    'Australiens, Néo-Zélandais, Japonais : une partie de la clientèle écrit en anglais, et la réponse attend trop souvent la seule personne qui le parle. Les demandes standard — disponibilités, tarifs, accès, navettes — se traitent correctement dans les deux langues avec relecture ; le reste est signalé pour une réponse humaine. Et pour les prestataires d’activités dépendants de la météo, prévenir et reprogrammer toute une journée de clients en quelques minutes vaut de l’or les jours de coup de vent.',
    { h: 'Les avis façonnent la prochaine saison' },
    'La demande d’avis part au bon moment, deux jours après le séjour ; un brouillon de réponse se prépare sur chaque avis reçu, appuyé sur ce que le client a réellement écrit — et c’est vous qui validez. Une réponse générique se repère au premier coup d’œil par tous les futurs visiteurs qui lisent ; une plainte, elle, ne reçoit jamais de réponse automatique.',
    { h: 'Ce que ça coûte, et où vivent les données' },
    'Un premier chantier — la centralisation des demandes ou la mécanique anti no-show — se chiffre entre **80 000 et 250 000 F** ([le détail de la grille reprise](/prix-automatisation-ia-nouvelle-caledonie/)), et [une part de chaque règlement encaissé au pays revient à une association locale](/engagement-local/). Quant aux fiches de vos hôtes, elles n’ont pas vocation à voyager plus qu’eux : [l’IA locale](/ia-locale-entreprise/) les garde dans l’établissement.',
    { note: 'Des gîtes en tribu aux hôtels de l’Anse Vata, le produit reste l’accueil — personne ne traverse la moitié du globe pour parler à un robot. L’automatisation travaille en coulisses : plannings, acomptes, relances, traductions. Le mot de bienvenue et le café du matin, eux, ne se délèguent pas.' },
  ],
  faq: [
    { q: 'Comment réduire concrètement les no-shows ?', a: 'Trois habitudes, tenues sans exception : un acompte par lien de paiement dès la réservation — même modeste, il change le taux de présence —, des confirmations échelonnées avant l’arrivée, et des conditions d’annulation énoncées dès le premier message. L’automatisation ne fait rien d’extraordinaire ici : elle fait que ces trois gestes ont lieu à chaque réservation, pas seulement quand quelqu’un y pense.' },
    { q: 'Un client peut-il sentir qu’une réponse est automatisée ?', a: 'Sur une demande de disponibilités, la rapidité prime et personne ne s’en offusque. Sur une demande particulière — un anniversaire, une inquiétude, un besoin d’accessibilité — la main doit passer à un humain, et vite. La règle qui tient : l’automatisation répond aux questions dont la réponse est dans le planning ou la grille tarifaire ; tout le reste est un signal pour vous.' },
    { q: 'Faut-il chercher à quitter Booking ?', a: 'Non — la visibilité internationale des plateformes ne se remplace pas. L’enjeu est ailleurs : que le client qui a déjà séjourné chez vous réserve la deuxième fois en direct. Une invitation au bon moment, un avantage simple, et la commission économisée sur chaque fidèle finance largement le système qui l’a rendue possible.' },
    { q: 'Et quand la connexion coupe, en brousse ou dans les îles ?', a: 'C’est une contrainte de conception, pas un détail : les confirmations et relances se mettent en file et partent au retour du réseau, et un système installé sur une machine de l’établissement continue de tenir le planning hors ligne. Le montage est décrit dans [notre guide de l’IA locale](/ia-locale-entreprise/).' },
  ],
  related: [
    ['/ia-commerce-noumea/', 'IA pour les commerces de Nouméa'],
    ['/ia-agriculture-peche-nouvelle-caledonie/', 'IA côté producteurs et pêcheurs'],
    ['/prix-automatisation-ia-nouvelle-caledonie/', 'Les tarifs au pays'],
    ['/exemples-automatisation-pme/', '10 exemples d’automatisation'],
  ],
},

{
  slug: 'ia-professions-liberales-nouvelle-caledonie',
  lang: 'fr',
  title: 'IA pour les professions libérales en Nouvelle-Calédonie — documents, secret professionnel',
  description: 'IA pour comptables, avocats et géomètres en Nouvelle-Calédonie : documents répétitifs, recherche dans ses propres dossiers, honoraires — et pourquoi l’IA locale règle la question du secret professionnel.',
  keywords: 'IA professions libérales Nouvelle-Calédonie, IA cabinet comptable Nouméa, IA avocat confidentialité, automatisation cabinet Nouvelle-Calédonie, secret professionnel IA',
  eyebrow: 'Kanaky (Nouvelle-Calédonie)',
  short: 'IA · Professions libérales',
  h1: 'L’IA en cabinet. <span style="color:var(--grey-4);font-weight:300;">Le secret professionnel décide de tout.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Un cabinet — expertise comptable, avocat, géomètre-expert — vend du jugement mais produit du document : liasses, conclusions, actes, plans, rapports, courriers. La question n’est plus de savoir si l’IA peut aider à les produire ; elle le peut, largement. La vraie question, pour des professions tenues au secret, est de savoir **où passent les dossiers pendant qu’elle aide** — et c’est elle qui se pose en premier.' },
    { h: 'Le répétitif du cabinet, poste par poste' },
    { list: [
      '**L’extraction** : pièces comptables, relevés bancaires, actes et annexes lus automatiquement, leurs données versées dans vos outils au lieu d’être ressaisies.',
      '**Le premier jet** : courriers, trames d’actes, sections récurrentes de rapports, montés depuis vos propres modèles et précédents.',
      '**La recherche interne** : retrouver en quelques secondes la clause négociée il y a trois ans dans un dossier voisin, ou le traitement retenu sur un cas comparable.',
      '**Les obligations de calendrier** : échéances fiscales et sociales de chaque client, suivies et rappelées sans tableur héroïque.',
    ]},
    { h: 'La confidentialité décide de l’architecture' },
    'Trois montages existent, et ils ne se valent pas pour une profession réglementée :',
    { table: {
      minWidth: 580,
      head: ['Montage', 'Où vont les dossiers', 'Lecture pour un cabinet'],
      rows: [
        ['Assistant grand public gratuit', 'Serveurs à l’étranger, conditions d’utilisation mouvantes', 'À proscrire pour toute pièce client'],
        ['Offre professionnelle sous contrat', 'Chez un tiers, dans un cadre contractuel', 'Défendable, après analyse et selon votre déontologie'],
        ['IA locale, au cabinet', 'Nulle part : rien ne sort de vos murs', 'La question du transfert cesse de se poser'],
      ],
    }},
    'Le troisième montage a un mérite particulier : il ne demande pas de faire confiance, il retire le sujet. [Le guide de l’IA locale](/ia-locale-entreprise/) en détaille le matériel et les limites.',
    { h: 'Ce que les modèles ignorent du droit calédonien' },
    'Les grands modèles connaissent le droit métropolitain de façon inégale, et les particularités du pays — la TGC, le statut civil coutumier, le droit du travail applicable localement, les compétences respectives du gouvernement de la Nouvelle-Calédonie et de l’État — de façon franchement lacunaire. Conséquence pratique : la valeur ne vient pas du savoir du modèle mais de **vos** fonds documentaires — modèles d’actes, précédents, doctrine que vous versez au système. C’est plutôt une bonne nouvelle : votre bibliothèque devient un levier, pas un simple archivage.',
    { h: 'Les honoraires : saisis, facturés, relancés' },
    'Le temps passé se capture au fil du dossier au lieu de se reconstituer en fin de mois — chacun sait ce que la reconstitution laisse en route. La note d’honoraires se génère, la relance suit un rythme courtois et progressif. Relancer un client qu’on conseille encore est désagréable, et c’est précisément pour cela que personne ne le fait : confier la constance à la machine préserve la relation, et la trésorerie avec.',
    { h: 'Le coût, dit simplement' },
    'L’audit d’opportunités est gratuit et vous en gardez les conclusions. Un premier workflow — extraction de pièces, chaîne d’honoraires — se situe dans la [fourchette reprise de 80 000 à 250 000 F](/prix-automatisation-ia-nouvelle-caledonie/) ; une installation locale complète, matériel compris, se chiffre sur devis. Comme pour tous nos clients du pays, [10 % de chaque paiement vont à une association calédonienne](/engagement-local/).',
    { note: 'Rien ne part signé sans relecture. En droit comme en chiffre, l’erreur vraisemblable est la plus dangereuse : un montant cohérent mais faux, une référence plausible mais inventée traversent une relecture pressée. Le gain se prend sur le premier jet, l’extraction et la recherche — jamais sur la signature, qui reste votre acte et votre responsabilité.' },
  ],
  faq: [
    { q: 'L’usage de l’IA est-il compatible avec le secret professionnel ?', a: 'Tout dépend du montage. Envoyer des pièces client vers un assistant grand public est indéfendable. Un service professionnel sous contrat peut l’être, après analyse de vos obligations déontologiques. Un système local, lui, ne transmet rien à personne : le dossier ne quitte jamais le cabinet, ce qui transforme une question de conformité permanente en question réglée une fois pour toutes.' },
    { q: 'L’IA peut-elle rédiger des conclusions ou monter une liasse ?', a: 'Elle produit un premier jet sérieux à partir de vos modèles, de vos précédents et des pièces du dossier — et ce premier jet fait gagner un temps réel. Elle ne plaide pas, ne certifie pas, n’engage aucune responsabilité : la vôtre couvre chaque document qui sort. Le professionnel qui relit un jet avancé travaille plus vite que celui qui part d’une page blanche ; il ne travaille pas moins sérieusement.' },
    { q: 'Quel budget pour un cabinet de petite taille ?', a: 'L’audit est gratuit. Un premier chantier utile — souvent l’extraction de pièces ou la chaîne honoraires-relances — tient dans la fourchette reprise de 80 000 à 250 000 F. Une installation entièrement locale, machine comprise, coûte davantage à l’entrée puis supprime tout coût par utilisation — un profil qui convient bien aux volumes réguliers d’un cabinet.' },
    { q: 'Devons-nous informer nos clients de l’usage de l’IA ?', a: 'La transparence est une bonne pratique, et certaines déontologies la commandent. L’information est nettement plus simple à donner quand le traitement est local : « vos pièces sont traitées au cabinet, sur nos machines, et n’en sortent pas » est une phrase que tout client comprend — et qui se vérifie.' },
  ],
  related: [
    ['/ia-locale-entreprise/', 'L’IA en local'],
    ['/prix-automatisation-ia-nouvelle-caledonie/', 'Les tarifs au pays'],
    ['/ia-btp-nouvelle-caledonie/', 'IA pour le BTP calédonien'],
    ['/combien-coute-automatisation-ia/', 'Les prix en détail'],
  ],
},

{
  slug: 'ia-services-techniques-nouvelle-caledonie',
  lang: 'fr',
  title: 'IA pour la clim, l’élec et la plomberie en Nouvelle-Calédonie — devis vocaux, tournées, impayés',
  description: 'Clim, électricité, plomberie en Nouvelle-Calédonie : devis dictés depuis le terrain, tournées regroupées, rappels d’entretien avant la saison chaude et relances d’impayés qui tournent seules.',
  keywords: 'IA climatisation Nouméa, automatisation artisan Nouvelle-Calédonie, devis vocal électricien NC, planning interventions plomberie, relance facture artisan',
  eyebrow: 'Kanaky (Nouvelle-Calédonie)',
  short: 'IA · Métiers techniques',
  h1: 'L’IA pour les métiers techniques. <span style="color:var(--grey-4);font-weight:300;">Le devis se dicte, la tournée se calcule.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'En décembre à Nouméa, un frigoriste ne cherche pas du travail : il cherche des heures. Le téléphone sonne pendant les interventions, les devis s’empilent dans un coin du fourgon, et les factures de dépannage partent avec des semaines de retard — quand elles partent. Pour la clim, l’élec et la plomberie du pays, l’enjeu n’est pas de trouver des clients : c’est d’arrêter d’en perdre par débordement.' },
    { h: 'La saison chaude concentre tout' },
    'De novembre à avril, la demande explose exactement quand la capacité manque : pannes de clim en série, chambres froides en alerte, urgences qui s’intercalent entre les rendez-vous posés. Le reste de l’année, les journées respirent — et c’est là que se préparent les contrats d’entretien qui lisseront la saison suivante. Une organisation qui épouse ce cycle vaut mieux qu’un outil de plus : capter sans faille pendant le rush, remplir le creux avec l’entretien programmé.',
    { cards: [
      { t: 'Le devis dicté du parking', d: 'Le remplacement de split décrit à voix haute en remontant dans le fourgon ; le devis chiffré en XPF revient pour relecture et part dans l’heure — pendant que le concurrent chiffrera dimanche soir.' },
      { t: 'La tournée qui tient debout', d: 'Les interventions regroupées par secteur — Ducos le matin, Dumbéa l’après-midi — plutôt que trois traversées de l’agglomération par jour. Le carburant et les heures de volant se lisent en fin de mois.' },
      { t: 'L’entretien rappelé avant la chaleur', d: 'L’historique déclenche les rappels en septembre-octobre : le split entretenu avant l’été ne lâche pas un 24 décembre, et son propriétaire reste votre client au lieu de composer le premier numéro venu.' },
      { t: 'La facture qui suit l’intervention', d: 'Le bon de travail devient facture le jour même, puis les relances suivent un rythme poli et régulier. L’impayé se règle par la constance — pas par le coup de fil qu’on repousse.' },
    ]},
    { h: 'Trier l’urgence du devis, sans perdre ni l’un ni l’autre' },
    'La chambre froide d’un snack en panne un vendredi et la demande de devis pour un split résidentiel n’appellent pas la même réponse — mais elles sonnent sur le même téléphone, souvent pendant que vous avez les mains dans une armoire électrique. Un tri automatique des demandes entrantes accuse réception de tout, fait préciser la nature de la panne, route l’urgence vers votre poche et met le devis en file pour le soir. Rien ne se perd, et vous ne lâchez plus une intervention pour un appel qui pouvait attendre.',
    { h: 'Les impayés se comptent en centaines de milliers' },
    'Quinze factures de dépannage à 45 000 F oubliées dans l’année, c’est 675 000 F de travail réalisé et non payé — souvent sans mauvaise volonté du client, simplement parce que personne n’a relancé. La chaîne facture-rappel-relance tourne seule, s’arrête au premier règlement, et vous n’avez plus jamais à choisir entre votre trésorerie et votre gêne.',
    { h: 'Les contrats professionnels, l’étage au-dessus' },
    'Syndics, hôtels, commerces climatisés, restaurants avec du froid alimentaire : ces clients-là signent des contrats d’entretien à l’année et préfèrent payer un peu plus pour un prestataire qui répond. Les trouver et leur écrire un par un est un travail que personne ne tient à la main — c’est exactement ce que fait [une machine de prospection](/machine-prospection-commerciale/), à un rythme prudent et avec des messages réellement personnalisés.',
    'Un premier chantier — le devis vocal ou la chaîne de relances — se monte entre **80 000 et 250 000 F** au [tarif reprise en vigueur au pays](/prix-automatisation-ia-nouvelle-caledonie/), et [une part de chaque règlement finance une association d’ici](/engagement-local/).',
    { note: 'Le dépannage remplit la semaine ; l’entretien remplit l’année. De toutes les automatisations de cette page, le rappel d’entretien branché sur l’historique est la seule qui crée du chiffre d’affaires au lieu d’en protéger — chaque rappel envoyé est une intervention programmée qui n’ira pas ailleurs. S’il ne fallait en retenir qu’une, c’est elle.' },
  ],
  faq: [
    { q: 'Comment marche un devis vocal, concrètement ?', a: 'Vous décrivez l’intervention à voix haute — matériel, métrage, accès, main-d’œuvre — comme vous le diriez à un collègue. Le système structure, applique votre grille tarifaire, monte le document avec vos mentions et votre régime de TGC, et vous le soumet. Vous corrigez ce qui doit l’être, puis vous envoyez. La différence ne se joue pas sur la qualité du devis : elle se joue sur le fait qu’il part le jour même.' },
    { q: 'Mes clients vont-ils mal prendre les relances ?', a: 'L’expérience montre l’inverse : une relance courte, polie, arrivée au bon moment est perçue comme du sérieux. Ce qui crispe, c’est la facture surgie de nulle part après six mois, ou le ton sec d’un artisan à bout. La progression — rappel aimable, deuxième rappel, mise en demeure en dernier recours seulement — protège la relation précisément parce qu’elle évite l’accumulation.' },
    { q: 'Je travaille seul. Est-ce que ça vaut le coût ?', a: 'Un artisan seul est celui qui paie chaque heure administrative sur sa soirée ou son dimanche. Le devis vocal rend l’essentiel à lui seul : commencez là, au tarif reprise, mesurez un mois de délais de devis et de taux de signature, et laissez les chiffres décider de la suite.' },
    { q: 'Et sur les chantiers sans réseau ?', a: 'La dictée fonctionne hors ligne et le devis part quand le téléphone retrouve du signal — au pire en fin de journée, ce qui reste sans commune mesure avec le devis du week-end suivant. Et pour l’atelier, un système qui tourne [sur une machine locale](/ia-locale-entreprise/) ne dépend ni de la liaison ni d’un serveur lointain.' },
  ],
  related: [
    ['/ia-btp-nouvelle-caledonie/', 'IA pour le BTP calédonien'],
    ['/prix-automatisation-ia-nouvelle-caledonie/', 'Les tarifs au pays'],
    ['/machine-prospection-commerciale/', 'La machine de prospection'],
    ['/exemples-automatisation-pme/', '10 exemples d’automatisation'],
  ],
},

{
  slug: 'ia-agriculture-peche-nouvelle-caledonie',
  lang: 'fr',
  title: 'IA pour l’agriculture et la pêche en Nouvelle-Calédonie — traçabilité, vente directe',
  description: 'Agriculture, pêche et aquaculture en Nouvelle-Calédonie : traçabilité dictée au fil de l’eau, vente directe organisée, facturation des circuits professionnels et réaction météo en quelques minutes.',
  keywords: 'IA agriculture Nouvelle-Calédonie, automatisation pêche NC, traçabilité aquaculture Nouvelle-Calédonie, vente directe producteur Nouméa, IA exploitation agricole',
  eyebrow: 'Kanaky (Nouvelle-Calédonie)',
  short: 'IA · Agriculture-pêche',
  h1: 'L’IA aux champs et en mer. <span style="color:var(--grey-4);font-weight:300;">La paperasse ne monte pas à bord.</span>',
  cta: 'service-fr',
  body: [
    { lead: 'Entre le champ, le bateau et le bassin, le producteur calédonien exerce un second métier que personne n’a choisi : registres sanitaires, bons de livraison, commandes Messenger, factures aux restaurateurs. La crevette part à l’export avec son dossier de traçabilité, le poisson au marché avec sa glace — et l’administratif se fait à la lampe, après la journée. C’est ce second métier qu’on automatise. Pas la terre, pas la mer.' },
    { h: 'La traçabilité se dicte au fil de l’eau' },
    'Lots, traitements, températures, dates de récolte ou de sortie : la traçabilité n’est pas une option, surtout quand la production part à l’export ou vers la restauration. La différence entre un registre tenu au jour le jour et un registre reconstitué la veille d’un contrôle, tout le monde la connaît. Dicter l’information au moment où elle existe — « bassin 3, relevé du matin, distribution à telle heure » — et la retrouver rangée, datée, exportable : c’est le geste qui transforme la contrainte en routine de trente secondes.',
    { h: 'La vente directe est devenue un canal à part entière' },
    'Du champ en tribu au marché municipal, en passant par le bord de route et les groupes Facebook, la vente directe s’est imposée — et avec elle une charge invisible : répondre vingt fois aux mêmes questions, tenir la liste de ce qui est disponible cette semaine, noter les commandes sur trois supports différents. La liste de la semaine diffusée une seule fois sur tous les canaux, les commandes collectées et récapitulées par tournée de livraison, les habitués prévenus quand leur produit revient : rien de spectaculaire — des heures rendues chaque semaine.',
    { h: 'Restaurateurs, revendeurs, marché de gros : le circuit pro' },
    'La vente aux professionnels se perd rarement sur la qualité du produit — elle se perd sur le suivi : le bon de livraison égaré, la facture partie tard, le tarif propre à chaque client que plus personne ne retrouve. Le bon devient facture le jour de la livraison, chaque client garde son prix et ses conditions, la relance part sans fâcherie. Un producteur qui livre douze restaurants exerce un métier de gestionnaire qu’il n’a jamais demandé ; autant que la machine le porte.',
    { h: 'La météo ne se négocie pas — la réaction, si' },
    'Dépression qui se creuse, alerte cyclonique, coup d’ouest : l’information existe, officielle et fiable. Ce qui manque le jour même, c’est le temps d’en tirer les conséquences — prévenir quarante clients de l’annulation du marché, décaler les livraisons, reprogrammer une sortie. Brancher vos actions sur les bulletins officiels — un message type validé par vous, envoyé à tous en deux minutes — transforme une soirée de téléphone en un seul geste.',
    { h: 'Quatre circuits, une même mécanique' },
    { table: {
      minWidth: 580,
      head: ['Circuit', 'Ce qui mange les soirées', 'Ce qui s’automatise'],
      rows: [
        ['Vente directe (marché, bord de route, réseaux)', 'Répondre un par un, tenir la liste des disponibilités', 'Liste hebdomadaire diffusée partout d’un coup, commandes récapitulées par tournée'],
        ['Restaurateurs et revendeurs', 'Bons, factures, relances, tarifs par client', 'Facturation depuis le bon de livraison, relances progressives'],
        ['Marché de gros et coopérative', 'Documents de lots, écarts de pesée', 'Dossiers de lot préparés, écarts signalés au lieu d’être découverts'],
        ['Export', 'Un dossier de traçabilité exigeant', 'Registre dicté au jour le jour, dossier assemblé au moment de l’expédition'],
      ],
    }},
    'Un premier chantier — la traçabilité dictée ou la chaîne de facturation — se situe entre **80 000 et 250 000 F**, [détail de la grille reprise ici](/prix-automatisation-ia-nouvelle-caledonie/), audit gratuit d’abord. [Un dixième de chaque paiement reçu au pays est reversé à une association calédonienne](/engagement-local/) — et pour une exploitation loin de tout, [un système qui tourne sur place, sans dépendre de la liaison](/ia-locale-entreprise/), n’est pas un raffinement : c’est la condition pour que ça marche.',
    { note: 'L’IA ne fait ni pluie ni beau temps : elle ne remplacera ni les bulletins officiels ni le coup d’œil du pêcheur au ciel, et elle ne fera pousser aucune igname. Son territoire, c’est la conséquence : l’information saisie une fois, la liste diffusée partout, le client prévenu à temps. Le reste — la terre, la mer, la saison — ne lui appartient pas.' },
  ],
  faq: [
    { q: 'Je vends déjà tout ce que je produis. À quoi ça me sert ?', a: 'À récupérer vos soirées, d’abord : la traçabilité, la facturation et les commandes se font aujourd’hui sur votre temps de repos. Ensuite à mieux vendre la même production : un circuit pro bien suivi paie plus régulièrement, la liste de la semaine écoule les surplus avant qu’ils ne se perdent, et un registre toujours à jour change un contrôle en formalité.' },
    { q: 'La connexion est mauvaise chez moi. C’est bloquant ?', a: 'Non, à condition de le prévoir dès la conception. La dictée fonctionne hors ligne, les messages partent en file dès que le réseau revient, et un système installé sur une machine de l’exploitation continue de travailler sans liaison — en brousse comme dans les îles. C’est exactement le cas d’usage de [l’IA locale](/ia-locale-entreprise/).' },
    { q: 'Quel budget pour une petite exploitation ?', a: 'L’audit ne coûte rien et vous en gardez les conclusions. Un premier chantier utile tient dans la fourchette reprise de 80 000 à 250 000 F — souvent remboursé par les seuls impayés récupérés du circuit restaurateurs, ou par une saison de commandes mieux tenues. Commencez par un seul processus et jugez sur pièces.' },
    { q: 'L’IA peut-elle prévoir la météo ou les cours ?', a: 'Non, et prudence avec quiconque le promet. Elle exploite ce qui existe — bulletins officiels, vos historiques de prix et de volumes — pour préparer des décisions et déclencher des actions convenues d’avance. La prévision reste aux organismes qui en ont les moyens ; la réaction rapide, elle, est à votre portée.' },
  ],
  related: [
    ['/ia-hotellerie-tourisme-nouvelle-caledonie/', 'IA pour l’hôtellerie et le tourisme'],
    ['/ia-commerce-noumea/', 'IA pour les commerces de Nouméa'],
    ['/prix-automatisation-ia-nouvelle-caledonie/', 'Les tarifs au pays'],
    ['/exemples-automatisation-pme/', '10 exemples d’automatisation'],
  ],
},

];
